import { uuid } from '../id';
import type { FileSystem } from '../host';
import type { LifeTimeline, TimelineEvent } from '../schemas';
import { getTimeline, saveTimeline } from './storyService';

/**
 * The timeline studio (64 §16.2) — the chronology spine, finally first-class.
 *
 * `Book.timeline` has been generated by the foundations pass, written to `timeline.enc` and carried to the
 * renderer inside the bundle since the beginning — and read by nothing. `TimelineEvent.userEdited` exists
 * specifically to protect a hand-fixed event from AI overwrite, and until now nothing has ever set it. This
 * module makes the timeline editable, makes those edits durable, and (via `storyCorpus` + the structure
 * pass) makes them actually shape the book (#292).
 *
 * All deterministic — no AI, no metering, no new storage.
 */

/** The outcome of a timeline edit — never throws on a vanished id, so a stale UI degrades honestly. */
export interface TimelineEditResult {
  ok: boolean;
  message?: string;
}

const NOT_FOUND = 'That moment is no longer on your timeline.';

/** A tiny, stable, non-cryptographic string hash (djb2) — the `storyFreshness` helper, same job. */
function hashString(value: string): string {
  let h = 5381;
  for (let i = 0; i < value.length; i += 1) h = (h * 33) ^ value.charCodeAt(i);
  return (h >>> 0).toString(36);
}

/**
 * The identity of a moment, for matching a re-proposal to what the person already has. Case, punctuation
 * and spacing are noise ("Born in Ohio" / "born in ohio." / "Born  in  Ohio" are one moment).
 */
export function normalizeMoment(label: string): string {
  return label
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, '')
    .replace(/\s+/g, ' ');
}

/**
 * The id a GENERATED moment gets: derived from its normalized label, so the same moment keeps the same id
 * across passes. Fresh uuids per pass would (a) let a renamed event's re-proposal slip past the merge, (b)
 * orphan any `source` exclusion the person set on it, and (c) drift every citing chapter's freshness
 * signature into `stale`, queueing a paid rewrite for nothing.
 */
export function generatedEventId(label: string): string {
  return `tl-${hashString(normalizeMoment(label))}`;
}

/**
 * Sort key for an event: a real `date` first (ISO or a partial `YYYY`/`YYYY-MM`), then a fuzzy `approx`
 * label, then undated. Partial dates sort naturally as strings, which is why they're kept as strings.
 */
function sortKey(event: TimelineEvent): [number, string] {
  if (event.date?.trim()) return [0, event.date.trim()];
  if (event.approx?.trim()) return [1, event.approx.trim()];
  return [2, event.label];
}

/** Dated events first (earliest → latest, lexical on the ISO/partial string), then the `approx` ones
 *  (sorted lexically — "early 2000s" lands before "mid-90s"), then undated. */
export function sortTimeline(events: TimelineEvent[]): TimelineEvent[] {
  return [...events].sort((a, b) => {
    const [ra, ka] = sortKey(a);
    const [rb, kb] = sortKey(b);
    return ra !== rb ? ra - rb : ka.localeCompare(kb);
  });
}

async function withTimeline(
  fs: FileSystem,
  key: Uint8Array,
  personId: string,
  bookId: string,
  edit: (timeline: LifeTimeline) => TimelineEditResult,
): Promise<TimelineEditResult> {
  // A book whose foundations haven't run yet has no timeline file — start one rather than refusing, so a
  // person can lay out their own chronology before the biographer proposes anything.
  const timeline = (await getTimeline(fs, key, personId, bookId)) ?? {
    schemaVersion: 1 as const,
    events: [],
  };
  const res = edit(timeline);
  // Persist SORTED, so the stored order and the rendered order agree — otherwise a moment added out of
  // sequence jumps on the next reload.
  if (res.ok) {
    await saveTimeline(fs, key, personId, bookId, {
      ...timeline,
      events: sortTimeline(timeline.events),
    });
  }
  return res;
}

/** Add a moment the person remembers. Always `userEdited` — they typed it. */
export async function addTimelineEvent(
  fs: FileSystem,
  key: Uint8Array,
  personId: string,
  bookId: string,
  args: { label: string; date?: string | undefined; approx?: string | undefined },
): Promise<TimelineEditResult> {
  const label = args.label.trim();
  if (!label) return { ok: false, message: 'A moment needs a name.' };
  return withTimeline(fs, key, personId, bookId, (timeline) => {
    // Adding it back clears any tombstone — they changed their mind, and the biographer may fill it in.
    const marker = normalizeMoment(label);
    if (timeline.removed?.includes(marker)) {
      timeline.removed = timeline.removed.filter((r) => r !== marker);
    }
    timeline.events.push({
      id: uuid(),
      label,
      ...(args.date?.trim() ? { date: args.date.trim() } : {}),
      ...(args.approx?.trim() ? { approx: args.approx.trim() } : {}),
      userEdited: true,
    });
    return { ok: true };
  });
}

/**
 * Correct a moment — its name, its date, or its fuzzy era. Stamps `userEdited`, which is what stops a later
 * foundations/refresh pass from overwriting the correction (§16.2). Passing an empty `date`/`approx` clears
 * that field, so "actually I don't know the year" is expressible.
 */
export async function updateTimelineEvent(
  fs: FileSystem,
  key: Uint8Array,
  personId: string,
  bookId: string,
  args: {
    eventId: string;
    label?: string | undefined;
    date?: string | undefined;
    approx?: string | undefined;
  },
): Promise<TimelineEditResult> {
  return withTimeline(fs, key, personId, bookId, (timeline) => {
    const event = timeline.events.find((e) => e.id === args.eventId);
    if (!event) return { ok: false, message: NOT_FOUND };
    if (args.label !== undefined) {
      const label = args.label.trim();
      if (!label) return { ok: false, message: 'A moment needs a name.' };
      event.label = label;
    }
    if (args.date !== undefined) {
      const date = args.date.trim();
      if (date) event.date = date;
      else delete event.date;
    }
    if (args.approx !== undefined) {
      const approx = args.approx.trim();
      if (approx) event.approx = approx;
      else delete event.approx;
    }
    event.userEdited = true;
    return { ok: true };
  });
}

/** Remove a moment. Only the timeline entry goes — the source material it came from is untouched. */
export async function removeTimelineEvent(
  fs: FileSystem,
  key: Uint8Array,
  personId: string,
  bookId: string,
  args: { eventId: string },
): Promise<TimelineEditResult> {
  return withTimeline(fs, key, personId, bookId, (timeline) => {
    const index = timeline.events.findIndex((e) => e.id === args.eventId);
    if (index < 0) return { ok: false, message: NOT_FOUND };
    const [gone] = timeline.events.splice(index, 1);
    // Tombstone it, so a later pass can't re-propose the moment they just took out.
    if (gone) {
      const marker = normalizeMoment(gone.label);
      timeline.removed = [...new Set([...(timeline.removed ?? []), marker])];
    }
    return { ok: true };
  });
}

/**
 * Fold a freshly-generated timeline into the stored one, **preserving every hand-edited event** (§16.2).
 *
 * This is the promise `TimelineEvent.userEdited` has always encoded and nothing has ever honoured: a person
 * who corrects "1985" to "1987" must not have that correction quietly reverted by the next foundations or
 * refresh pass. A generated event is dropped when a user-edited event already carries the same label
 * (case-insensitive), since that's the same moment the person has already put right.
 */
export function mergeGeneratedTimeline(
  stored: LifeTimeline | null,
  generated: TimelineEvent[],
): LifeTimeline {
  const kept = stored?.events ?? [];
  const userEdited = kept.filter((e) => e.userEdited);
  // Claim by ID as well as label: a person who RENAMED a moment keeps the id derived from the label the
  // biographer used, so the re-proposal collapses onto their version instead of coming back beside it with
  // the wording (and date) they corrected away.
  const claimed = new Set([
    ...userEdited.map((e) => e.id),
    ...userEdited.map((e) => normalizeMoment(e.label)),
  ]);
  // A moment the person DELETED stays deleted — otherwise "this is wrong, take it out" is undone by the
  // next pass, which is the most likely reason anyone opens this panel at all.
  const removed = new Set(stored?.removed ?? []);
  const fresh = generated.filter(
    (e) =>
      !claimed.has(e.id) &&
      !claimed.has(normalizeMoment(e.label)) &&
      !removed.has(normalizeMoment(e.label)),
  );
  return {
    schemaVersion: 1,
    events: sortTimeline([...userEdited, ...fresh]),
    ...(removed.size > 0 ? { removed: [...removed] } : {}),
  };
}

/** A compact "1985 — Born in Ohio" line per event, for the corpus + the structure prompt. */
export function timelineLines(timeline: LifeTimeline | null): string[] {
  return sortTimeline(timeline?.events ?? []).map((event) => {
    const when = event.date?.trim() || event.approx?.trim();
    return when ? `${when} — ${event.label}` : event.label;
  });
}
