import { bankFamily, buildBank, type Bank, type BankFamily } from '../bank';

/**
 * 74 §3.6.8 — the PET-NAME bank: what the two of you call each other, across 24 registers from the
 * warmest to the furthest, every one marked TWICE (being called it, and calling them it).
 *
 * Separate from the phrase bank because it is answered in its own phase, before the vocabulary, and
 * because a name is a different kind of thing: a vocative, usable in any generated line, where a phrase
 * can only be quoted. `phase: 'names'` is what keeps these out of the deck and in that phase.
 *
 * **Boundary (absolute):** consensual adults; every roleplay register — kinship, authority, innocence,
 * age gap — is PRE-AGREED ROLEPLAY between adults, never a real relative, never anyone underage, never
 * anything illegal. Carried by the content and the model, never a keyword filter.
 *
 * Each name carries a line showing it in use, in its register's voice, so a bare word is never the whole
 * row. The lines were composed from per-register frames rather than written one by one — at this size that
 * is the honest way to get a consistent voice, and it is stated here rather than implied.
 */

const nameFamily = (id: string, label: string, note: string): BankFamily => ({
  id,
  label,
  kind: 'word',
  directions: ['hear', 'say'],
  // Marked in the pet-name phase, never in the deck (74 §3.6.8).
  phase: 'names',
  note,
});

export const DIRTY_TALK_NAMES: Bank = buildBank([
  bankFamily(
    nameFamily(
      'names-warm',
      'Names — warm & sweet',
      'The ones that work outside the bedroom too. Some people want these all the way through; some want them nowhere near sex.',
    ),
    {
      1: [
        { text: 'baby', ex: 'come here, baby' },
        { text: 'babe', ex: 'look at me, babe' },
        { text: 'beautiful', ex: 'you feel so good, beautiful' },
        { text: 'gorgeous', ex: 'hi, gorgeous' },
        { text: 'sweet girl', ex: 'hey, sweet girl', addresses: 'girl' },
        { text: 'sweet boy', ex: 'come here, sweet boy', addresses: 'man' },
        { text: 'cutie', ex: 'come closer, cutie' },
      ],
      2: [
        { text: 'beautiful girl', ex: "that's it, beautiful girl", addresses: 'girl' },
        { text: 'beautiful boy', ex: "I've got you, beautiful boy", addresses: 'man' },
        { text: 'gorgeous girl', ex: 'morning, gorgeous girl', addresses: 'girl' },
        { text: 'pretty girl', ex: 'stay right there, pretty girl', addresses: 'girl' },
        { text: 'pretty boy', ex: 'come closer, pretty boy', addresses: 'man' },
        { text: 'pretty thing', ex: 'I missed you, pretty thing' },
        { text: 'sweet thing', ex: "you're perfect, sweet thing" },
        { text: 'lover', ex: 'I missed you, lover' },
        { text: 'doll face', ex: "you're perfect, doll face" },
        { text: 'gorgeous thing', ex: "I've got you, gorgeous thing" },
        { text: 'beautiful thing', ex: 'hi, beautiful thing' },
        { text: 'my pretty', ex: 'I missed you, my pretty' },
        { text: 'pretty face', ex: 'stay right there, pretty face' },
        { text: 'angel face', ex: 'come closer, angel face' },
        { text: 'babydoll', ex: 'I missed you, babydoll' },
        { text: 'baby doll', ex: "you're perfect, baby doll" },
        { text: 'sweet cheeks', ex: 'you feel so good, sweet cheeks' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-yours',
      'Names — yours',
      'Belonging without the power framing. This is the register your “my girl” example sits in.',
    ),
    {
      1: [
        { text: 'mine', ex: 'come here, mine' },
        { text: 'my girl', ex: 'say it — my girl', addresses: 'girl' },
        { text: 'my baby', ex: "you'll always be my baby" },
        { text: 'my babe', ex: "say you're my babe" },
        { text: 'my sweetheart', ex: "you know you're my sweetheart" },
      ],
      2: [
        { text: 'all mine', ex: "that's it, all mine" },
        { text: 'my woman', ex: 'look at me, my woman', addresses: 'girl' },
        { text: 'my man', ex: 'all night, my man', addresses: 'man' },
        { text: 'my boy', ex: "you're my boy", addresses: 'man' },
        { text: 'my sweet girl', ex: 'all night, my sweet girl', addresses: 'girl' },
        { text: 'my sweet boy', ex: "you're my sweet boy", addresses: 'man' },
        { text: 'wifey', ex: 'say it — wifey', addresses: 'girl' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-praise',
      'Names — praise',
      "Being told you're good at it — the single most-loved register in most profiles.",
    ),
    {
      2: [
        { text: 'good girl', ex: "that's it, good girl", addresses: 'girl' },
        { text: 'good boy', ex: 'good — good boy', addresses: 'man' },
        { text: 'best girl', ex: 'there she is, best girl', addresses: 'girl' },
        { text: 'best boy', ex: 'perfect, best boy', addresses: 'man' },
        { text: 'perfect girl', ex: 'well done, perfect girl', addresses: 'girl' },
        { text: 'perfect boy', ex: 'so good for me, perfect boy', addresses: 'man' },
        { text: 'my perfect one', ex: "you're my perfect one" },
        { text: 'golden girl', ex: "that's it, golden girl", addresses: 'girl' },
        { text: 'golden boy', ex: 'look at you, golden boy', addresses: 'man' },
        { text: 'my precious thing', ex: 'perfect, my precious thing' },
        { text: 'my dream girl', ex: "you're my dream girl", addresses: 'girl' },
        { text: 'my dream boy', ex: 'there he is — my dream boy', addresses: 'man' },
        { text: 'my good thing', ex: "that's it, my good thing" },
        { text: 'my very good girl', ex: 'good — my very good girl', addresses: 'girl' },
        { text: 'my very good boy', ex: 'look at you, my very good boy', addresses: 'man' },
        {
          text: 'my favourite girl',
          ex: "you're doing so well, my favourite girl",
          addresses: 'girl',
        },
        { text: 'my favourite boy', ex: "that's it, my favourite boy", addresses: 'man' },
        { text: 'my favourite thing', ex: 'good — my favourite thing' },
        { text: 'my pearl', ex: 'perfect, my pearl' },
      ],
      3: [
        { text: 'my perfect little thing', ex: "that's it — my perfect little thing" },
        { text: 'my flawless girl', ex: 'well done, my flawless girl', addresses: 'girl' },
        { text: 'my flawless boy', ex: 'so good for me, my flawless boy', addresses: 'man' },
        { text: 'my good little thing', ex: "you're doing so well, my good little thing" },
        { text: 'my obedient girl', ex: 'just like that, my obedient girl', addresses: 'girl' },
        { text: 'my obedient boy', ex: 'there he is, my obedient boy', addresses: 'man' },
        { text: 'my well-behaved girl', ex: 'perfect, my well-behaved girl', addresses: 'girl' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-soft-power',
      'Names — looked after',
      'The cared-for side of a power dynamic. Adults only, and the framing stays adult throughout.',
    ),
    {
      2: [
        { text: 'little one', ex: 'look at me, little one' },
        { text: 'little angel', ex: 'look at me, little angel' },
        { text: 'sweet baby', ex: 'good, sweet baby' },
      ],
      3: [
        { text: 'princess', ex: 'come here, princess', addresses: 'girl' },
        { text: 'babygirl', ex: 'good, babygirl', addresses: 'girl' },
        { text: 'boy', ex: 'up here, boy', addresses: 'man' },
        { text: 'baby boy', ex: 'on your knees, baby boy', addresses: 'man' },
        { text: 'girl', ex: 'easy, girl', addresses: 'girl' },
        { text: 'little miss', ex: 'stay there, little miss', addresses: 'girl' },
        { text: 'little sir', ex: 'sweet little thing — little sir', addresses: 'man' },
        { text: 'kitten', ex: 'come here, kitten' },
        { text: 'kitty', ex: "that's it, kitty" },
        { text: 'good kitty', ex: 'good, good kitty' },
        { text: 'bunny', ex: 'up here, bunny' },
        { text: 'pet', ex: 'come here, pet' },
        { text: 'good pet', ex: 'good, good pet' },
        { text: 'my sub', ex: 'on your knees, my sub' },
        { text: 'my sweet sub', ex: 'easy, my sweet sub' },
        { text: 'my good kitten', ex: "that's my good kitten" },
        { text: 'little kitten', ex: 'good, little kitten' },
        { text: 'my sweet pet', ex: 'come here, my sweet pet' },
        { text: 'my little pet', ex: "that's it, my little pet" },
        { text: 'my precious pet', ex: 'good, my precious pet' },
        { text: 'my baby bunny', ex: 'on your knees, my baby bunny' },
        { text: 'puppy girl', ex: 'sweet little thing — puppy girl', addresses: 'girl' },
        { text: 'puppy boy', ex: 'come here, puppy boy', addresses: 'man' },
        { text: 'my little puppy', ex: 'sweet little thing — my little puppy' },
        { text: 'my sweet puppy', ex: "you're my sweet puppy" },
        { text: 'kitty cat', ex: 'on your knees, kitty cat' },
        { text: 'my sweet kitty', ex: 'come here, my sweet kitty' },
        { text: 'mouse', ex: 'stay there, mouse' },
        { text: 'little prince', ex: 'come here, little prince', addresses: 'man' },
        { text: 'my little princess', ex: 'good, my little princess', addresses: 'girl' },
        { text: 'my little shadow', ex: 'look at me, my little shadow' },
        { text: 'my baby kitten', ex: "you're my baby kitten" },
        { text: 'baby girl', ex: 'up here, baby girl', addresses: 'girl' },
        { text: 'my little baby', ex: 'good, my little baby' },
        { text: 'tiny thing', ex: 'stay there, tiny thing' },
        { text: 'my small one', ex: 'easy, my small one' },
        { text: 'little thing', ex: 'come here, little thing' },
        { text: 'my delicate thing', ex: 'sweet little thing — my delicate thing' },
        { text: 'my fragile thing', ex: "you're my fragile thing" },
        { text: 'my sweet little pet', ex: "that's my sweet little pet" },
        { text: 'my darling pet', ex: "you're mine, my darling pet" },
        { text: 'pretty pet', ex: 'look at me, pretty pet' },
        { text: 'my quiet one', ex: 'up here, my quiet one' },
        { text: 'my good little pet', ex: 'on your knees, my good little pet' },
        { text: 'my soft one', ex: 'easy, my soft one' },
        { text: 'my sweet cub', ex: "you're mine, my sweet cub" },
        { text: 'bunny girl', ex: 'good, bunny girl', addresses: 'girl' },
      ],
      4: [
        { text: 'doll', ex: 'up here, doll' },
        { text: 'dolly', ex: 'easy, dolly' },
        { text: 'brat', ex: 'sweet little thing — brat' },
        { text: 'little brat', ex: "that's it, little brat" },
        { text: 'spoiled brat', ex: 'good, spoiled brat' },
        { text: 'spoiled little thing', ex: 'up here, spoiled little thing' },
        { text: 'my ward', ex: 'stay there, my ward' },
        { text: 'my charge', ex: 'sweet little thing — my charge' },
        { text: 'my sweet brat', ex: 'up here, my sweet brat' },
        { text: 'my needy girl', ex: 'on your knees, my needy girl', addresses: 'girl' },
        { text: 'my needy boy', ex: 'easy, my needy boy', addresses: 'man' },
        { text: 'my little doll', ex: 'stay there, my little doll' },
        { text: 'my rag doll', ex: 'sweet little thing — my rag doll' },
        { text: 'my obedient pet', ex: 'good, my obedient pet' },
        { text: 'pillow princess', ex: 'up here, pillow princess', addresses: 'girl' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-hard-power',
      'Names — in charge',
      'Titles. These matter in both directions — the one you want to be called and the one you want to use.',
    ),
    {
      3: [
        { text: 'sir', ex: 'yes, sir', addresses: 'man' },
        { text: "ma'am", ex: "please, ma'am", addresses: 'girl' },
        { text: 'miss', ex: 'thank you, miss', addresses: 'girl' },
        { text: 'mistress', ex: "I'm yours, mistress", addresses: 'girl' },
        { text: 'daddy', ex: 'of course, daddy', addresses: 'man' },
        { text: 'mommy', ex: 'please, mommy', addresses: 'girl' },
        { text: 'king', ex: 'as you say, king', addresses: 'man' },
        { text: 'queen', ex: 'whatever you want, queen', addresses: 'girl' },
        { text: 'goddess', ex: 'yes, goddess', addresses: 'girl' },
        { text: 'boss', ex: 'please, boss' },
        { text: 'my dom', ex: 'as you say, my dom' },
        { text: 'my domme', ex: "I'm yours, my domme", addresses: 'girl' },
        { text: 'madam', ex: 'as you say, madam', addresses: 'girl' },
      ],
      4: [
        { text: 'master', ex: 'anything you want, master', addresses: 'man' },
        { text: 'my god', ex: "you're my god", addresses: 'man' },
        { text: 'owner', ex: 'of course, owner' },
        { text: 'alpha', ex: 'as you say, alpha' },
        { text: 'my director', ex: "you're my director" },
        { text: 'dominatrix', ex: 'of course, dominatrix', addresses: 'girl' },
      ],
      5: [],
    },
  ),

  bankFamily(
    nameFamily(
      'names-worship',
      'Names — worship',
      'Not praise for what you did — devotion for what you are. A distinct register, and a common one for the person on top.',
    ),
    {
      2: [],
      3: [
        { text: 'my obsession', ex: 'look at you, my obsession' },
        { text: 'my weakness', ex: "you're my weakness" },
        { text: 'my idol', ex: 'look at you, my idol' },
        { text: 'my heaven', ex: 'god, my heaven' },
        { text: 'my paradise', ex: 'look at you, my paradise' },
        { text: 'my guilty pleasure', ex: "that's what you are — my guilty pleasure" },
        { text: 'my nectar', ex: "you'll be the end of me, my nectar" },
      ],
      4: [
        { text: 'my religion', ex: 'god, my religion' },
        { text: 'my addiction', ex: 'come here, my addiction' },
        { text: 'my drug', ex: "I can't get enough, my drug" },
        { text: 'my ruin', ex: 'you are my ruin' },
        { text: 'my undoing', ex: "that's what you are — my undoing" },
        { text: 'my vice', ex: "I can't get enough, my vice" },
        { text: 'my sin', ex: "you're my sin" },
        { text: 'my favourite sin', ex: 'you are my favourite sin' },
        { text: 'my drug of choice', ex: "you'll be the end of me, my drug of choice" },
        { text: 'my high', ex: 'god, my high' },
        { text: 'my fix', ex: 'look at you, my fix' },
        { text: 'my madness', ex: 'come here, my madness' },
        { text: 'my intoxication', ex: "you're my intoxication" },
        { text: 'my poison', ex: 'you are my poison' },
        { text: 'my venom', ex: "that's what you are — my venom" },
      ],
      5: [],
    },
  ),
  bankFamily(
    nameFamily(
      'names-rough-mild',
      'Names — rough, mild',
      'Naughty rather than degrading. For a lot of people this is as far as the rough register goes.',
    ),
    {
      2: [
        { text: 'my little freak', ex: 'behave, my little freak' },
        { text: 'freak', ex: 'get over here, freak' },
        { text: 'flirt', ex: "you're such a flirt" },
        { text: 'cheeky thing', ex: 'come here, cheeky thing' },
      ],
      3: [
        { text: 'naughty girl', ex: 'come here, naughty girl', addresses: 'girl' },
        { text: 'naughty boy', ex: "you're such a naughty boy", addresses: 'man' },
        { text: 'bad girl', ex: 'look at you, bad girl', addresses: 'girl' },
        { text: 'bad boy', ex: "someone's been a bad boy", addresses: 'man' },
        { text: 'dirty girl', ex: 'you little dirty girl', addresses: 'girl' },
        { text: 'dirty boy', ex: 'behave, dirty boy', addresses: 'man' },
        { text: 'filthy little thing', ex: "that's it, filthy little thing" },
        { text: 'greedy girl', ex: 'get over here, greedy girl', addresses: 'girl' },
        { text: 'greedy boy', ex: 'come here, greedy boy', addresses: 'man' },
        { text: 'little tease', ex: "you're such a little tease" },
        { text: 'tease', ex: 'look at you, tease' },
        { text: 'cocktease', ex: "someone's been a cocktease" },
        { text: 'minx', ex: 'you little minx', addresses: 'girl' },
        { text: 'little devil', ex: 'behave, little devil' },
        { text: 'little demon', ex: "that's it, little demon" },
        { text: 'wicked girl', ex: 'get over here, wicked girl', addresses: 'girl' },
        { text: 'wicked thing', ex: 'come here, wicked thing' },
        { text: 'little liar', ex: 'look at you, little liar' },
        { text: 'filthy girl', ex: "someone's been a filthy girl", addresses: 'girl' },
        { text: 'filthy boy', ex: 'you little filthy boy', addresses: 'man' },
        { text: 'naughty thing', ex: 'behave, naughty thing' },
        { text: 'naughty little thing', ex: "that's it, naughty little thing" },
        { text: 'dirty little thing', ex: 'get over here, dirty little thing' },
        { text: 'filthy thing', ex: 'come here, filthy thing' },
        { text: 'bad thing', ex: "you're such a bad thing" },
        { text: 'wicked little thing', ex: 'look at you, wicked little thing' },
        { text: 'sinful thing', ex: "someone's been a sinful thing" },
        { text: 'sinner', ex: 'you little sinner' },
        { text: 'little sinner', ex: 'behave, little sinner' },
        { text: 'little flirt', ex: 'look at you, little flirt' },
        { text: 'temptress', ex: 'get over here, temptress', addresses: 'girl' },
        { text: 'seductress', ex: "you're such a seductress", addresses: 'girl' },
        { text: 'siren', ex: 'look at you, siren', addresses: 'girl' },
        { text: 'naughty kitten', ex: "you're such a naughty kitten" },
        { text: 'bad kitten', ex: 'look at you, bad kitten' },
        { text: 'bad pet', ex: "someone's been a bad pet" },
        { text: 'sneaky thing', ex: 'get over here, sneaky thing' },
        { text: 'little sneak', ex: "you're such a little sneak" },
        { text: 'my little cheat', ex: "that's my little cheat for you" },
        { text: 'my spoiled girl', ex: 'come here, my spoiled girl', addresses: 'girl' },
        { text: 'my spoiled thing', ex: "you're my spoiled thing" },
        { text: 'my greedy thing', ex: 'look at you, my greedy thing' },
        { text: 'my hungry girl', ex: "you're my hungry girl", addresses: 'girl' },
        { text: 'my hungry thing', ex: "you're my hungry thing" },
        { text: 'my eager thing', ex: 'behave, my eager thing' },
        { text: 'my eager one', ex: "that's it, my eager one" },
        { text: 'my shameless thing', ex: 'get over here, my shameless thing' },
        { text: 'my brazen girl', ex: "you're my brazen girl", addresses: 'girl' },
        { text: 'brazen thing', ex: 'behave, brazen thing' },
        { text: 'my bold one', ex: 'come here, my bold one' },
        { text: 'my daring one', ex: "you're my daring one" },
        { text: 'my reckless one', ex: 'look at you, my reckless one' },
        { text: 'my flirty thing', ex: 'get over here, my flirty thing' },
        { text: 'spitfire', ex: 'look at you, spitfire' },
        { text: 'wildcat', ex: 'you little wildcat' },
        {
          text: 'naughty little minx',
          ex: "someone's been a naughty little minx",
          addresses: 'girl',
        },
        { text: 'my little minx', ex: 'look at you, my little minx', addresses: 'girl' },
        { text: 'saucy thing', ex: 'behave, saucy thing' },
        { text: 'saucy minx', ex: "that's it, saucy minx", addresses: 'girl' },
        { text: 'my saucy girl', ex: 'behave, my saucy girl', addresses: 'girl' },
        { text: 'my cheeky brat', ex: "that's my cheeky brat for you" },
        { text: 'my wicked one', ex: "you're my wicked one" },
        { text: 'my sinful one', ex: 'look at you, my sinful one' },
        { text: 'wayward girl', ex: 'get over here, wayward girl', addresses: 'girl' },
        { text: 'my wayward one', ex: 'behave, my wayward one' },
        { text: 'wild thing', ex: 'look at you, wild thing' },
        { text: 'my untamed one', ex: "you're my untamed one" },
        { text: 'my feisty one', ex: "you're my feisty one" },
        { text: 'feisty thing', ex: 'come here, feisty thing' },
        { text: 'my sassy girl', ex: "you're my sassy girl", addresses: 'girl' },
        { text: 'sassy thing', ex: 'look at you, sassy thing' },
        { text: 'my mouthy girl', ex: 'behave, my mouthy girl', addresses: 'girl' },
        { text: 'mouthy thing', ex: 'you little mouthy thing' },
        { text: 'my smart mouth', ex: 'get over here, my smart mouth' },
        { text: 'my back-talker', ex: "you're my back-talker" },
        { text: 'my little rebel', ex: "you're my little rebel" },
        { text: 'my stubborn girl', ex: 'behave, my stubborn girl', addresses: 'girl' },
        { text: 'my handful', ex: 'get over here, my handful' },
        { text: 'my little handful', ex: "you're my little handful" },
        { text: 'my little problem', ex: "that's my little problem for you" },
        { text: 'my bad influence', ex: 'come here, my bad influence' },
        { text: 'my dirty little secret', ex: "you're my dirty little secret" },
        { text: 'my guilty one', ex: 'look at you, my guilty one' },
        { text: 'my shameless flirt', ex: "you're my shameless flirt" },
        { text: 'my show-off', ex: 'behave, my show-off' },
        { text: 'my little show-off', ex: "that's it, my little show-off" },
        { text: 'my attention seeker', ex: 'get over here, my attention seeker' },
        { text: 'my greedy little thing', ex: "that's my greedy little thing for you" },
        { text: 'my impatient one', ex: 'come here, my impatient one' },
        { text: 'my restless one', ex: "you're my restless one" },
        { text: 'my little squirmer', ex: 'look at you, my little squirmer' },
        { text: 'my wriggler', ex: "you're my wriggler" },
        { text: 'my awful tease', ex: 'behave, my awful tease' },
        { text: 'my little firestarter', ex: "that's it, my little firestarter" },
        { text: 'my instigator', ex: 'get over here, my instigator' },
        { text: 'my bad habit', ex: "you're my bad habit" },
        { text: 'my indulgence', ex: "that's my indulgence for you" },
        { text: 'my little indulgence', ex: 'come here, my little indulgence' },
        { text: 'my treat', ex: "you're my treat" },
      ],
      4: [
        { text: 'tramp', ex: 'get over here, tramp' },
        { text: 'hussy', ex: 'you little hussy' },
        { text: 'jezebel', ex: 'you little jezebel', addresses: 'girl' },
        { text: 'harlot', ex: 'behave, harlot' },
        { text: 'trollop', ex: 'get over here, trollop' },
        { text: 'floozy', ex: 'come here, floozy' },
        { text: 'my wanton girl', ex: "you're my wanton girl", addresses: 'girl' },
        { text: 'wanton thing', ex: 'look at you, wanton thing' },
        { text: 'easy girl', ex: "someone's been a easy girl", addresses: 'girl' },
        { text: 'hellcat', ex: "that's it, hellcat" },
        { text: 'my feral girl', ex: "that's my feral girl for you", addresses: 'girl' },
        { text: 'feral thing', ex: "that's it, feral thing" },
        { text: 'my disobedient girl', ex: 'look at you, my disobedient girl', addresses: 'girl' },
        { text: 'disobedient thing', ex: "someone's been a disobedient thing" },
        { text: 'my defiant one', ex: "you're my defiant one" },
        { text: 'my little exhibitionist', ex: "you're my little exhibitionist" },
        { text: 'my forbidden one', ex: 'look at you, my forbidden one' },
        { text: 'my forbidden thing', ex: "you're my forbidden thing" },
        { text: 'my off-limits girl', ex: "you're my off-limits girl", addresses: 'girl' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-rough-heavy',
      'Names — rough, heavy',
      'Your “my little cum queen” lives here, along with the rest of the crude register.',
    ),
    {
      4: [
        { text: 'slut', ex: 'take it, slut' },
        { text: 'little slut', ex: 'look at you, little slut' },
        { text: 'good little slut', ex: 'you filthy good little slut' },
        { text: 'needy slut', ex: 'come here, needy slut' },
        { text: 'filthy slut', ex: 'on your knees, filthy slut' },
        { text: 'greedy little slut', ex: 'open up, greedy little slut' },
        { text: 'slut boy', ex: 'good, slut boy', addresses: 'man' },
        { text: 'manwhore', ex: 'take it, manwhore', addresses: 'man' },
        { text: 'attention whore', ex: 'look at you, attention whore' },
        { text: 'whore', ex: 'you filthy whore' },
        { text: 'little whore', ex: 'on your knees, little whore' },
        { text: 'dirty whore', ex: 'open up, dirty whore' },
        { text: 'whore boy', ex: 'take it, whore boy', addresses: 'man' },
        { text: 'bitch', ex: "that's it, bitch" },
        { text: 'cocksucker', ex: 'come here, cocksucker' },
        { text: 'cock worshipper', ex: 'open up, cock worshipper' },
        { text: 'size queen', ex: 'beg for it, size queen' },
        { text: 'dirty little slut', ex: 'beg for it, dirty little slut' },
        { text: 'filthy little slut', ex: "you're such a filthy little slut" },
        { text: 'nasty slut', ex: 'good, nasty slut' },
        { text: 'nasty girl', ex: 'take it, nasty girl', addresses: 'girl' },
        { text: 'mouthy slut', ex: 'open up, mouthy slut' },
        { text: 'dick sucker', ex: 'take it, dick sucker' },
        { text: 'my slutty girl', ex: "you're my slutty girl", addresses: 'girl' },
        { text: 'slutty little thing', ex: 'on your knees, slutty little thing' },
        { text: 'my perfect slut', ex: "say it — you're my perfect slut" },
        { text: 'my favourite slut', ex: 'you love being my favourite slut' },
        { text: 'my personal slut', ex: 'take it, my personal slut' },
        { text: 'my private whore', ex: "that's it, my private whore" },
        { text: 'my greedy slut', ex: "you're my greedy slut" },
        { text: 'my eager slut', ex: 'on your knees, my eager slut' },
        { text: 'my obedient slut', ex: 'open up, my obedient slut' },
        { text: 'my shameless slut', ex: 'you love being my shameless slut' },
        { text: 'my wanton slut', ex: 'take it, my wanton slut' },
        { text: 'my hungry slut', ex: "you're my hungry slut" },
        { text: 'my thirsty slut', ex: 'on your knees, my thirsty slut' },
        { text: 'my thirsty girl', ex: 'open up, my thirsty girl', addresses: 'girl' },
        { text: 'my needy little slut', ex: 'beg for it, my needy little slut' },
        { text: 'my wicked slut', ex: "you're my wicked slut" },
        { text: 'my sinful slut', ex: 'good, my sinful slut' },
        { text: 'tart', ex: 'good, tart' },
        { text: 'my little tart', ex: "you're my little tart" },
        { text: 'my dirty tart', ex: 'good, my dirty tart' },
        { text: 'my hoe', ex: 'come here, my hoe' },
        { text: 'my little hoe', ex: 'on your knees, my little hoe' },
        { text: 'my cock addict', ex: 'on your knees, my cock addict' },
        { text: 'my cock queen', ex: "you're my cock queen" },
        { text: 'my begging slut', ex: 'you love being my begging slut' },
        { text: 'my pleading slut', ex: 'take it, my pleading slut' },
        { text: 'my sex toy', ex: "that's what you are — my sex toy" },
        { text: 'my bed slut', ex: 'look at you, my bed slut' },
        { text: 'my bedroom slut', ex: "you're my bedroom slut" },
        { text: 'bimbo', ex: 'look at you, bimbo' },
        { text: 'my little bimbo', ex: 'open up, my little bimbo' },
        { text: 'my barbie', ex: "you're my barbie" },
        { text: 'my little barbie', ex: 'good, my little barbie' },
        { text: 'my vulgar girl', ex: 'take it, my vulgar girl', addresses: 'girl' },
      ],
      5: [
        { text: 'dumb slut', ex: 'beg for it, dumb slut' },
        { text: 'stupid slut', ex: "you're such a stupid slut" },
        { text: 'my filthy whore', ex: "you're my filthy whore" },
        { text: 'desperate little whore', ex: "you're such a desperate little whore" },
        { text: 'pathetic whore', ex: 'good, pathetic whore' },
        { text: 'cock hungry slut', ex: 'you filthy cock hungry slut' },
        { text: 'cum queen', ex: "you're such a cum queen" },
        { text: 'my little cum queen', ex: "that's it, my little cum queen" },
        { text: 'cum whore', ex: 'take it, cum whore' },
        { text: 'cum bucket', ex: "that's it, cum bucket" },
        { text: 'cockslut', ex: 'look at you, cockslut' },
        { text: 'cumslut', ex: 'you filthy cumslut' },
        { text: 'anal slut', ex: 'come here, anal slut' },
        { text: 'breeding slut', ex: 'on your knees, breeding slut' },
        { text: 'throat slut', ex: 'open up, throat slut' },
        { text: 'pathetic little slut', ex: "you're such a pathetic little slut" },
        { text: 'my greedy hole', ex: "that's what you are — my greedy hole" },
        { text: 'my ruined girl', ex: "say it — you're my ruined girl", addresses: 'girl' },
        { text: 'my wrecked girl', ex: 'you love being my wrecked girl', addresses: 'girl' },
        { text: 'my broken doll', ex: 'take it, my broken doll' },
        { text: 'my used girl', ex: "that's it, my used girl", addresses: 'girl' },
        { text: 'fucking slut', ex: 'come here, fucking slut' },
        { text: 'stupid whore', ex: 'open up, stupid whore' },
        { text: 'cheap slut', ex: 'look at you, cheap slut' },
        { text: 'cheap whore', ex: 'you filthy cheap whore' },
        { text: 'my worthless slut', ex: "say it — you're my worthless slut" },
        { text: 'my dirty little whore', ex: 'you love being my dirty little whore' },
        { text: 'brainless slut', ex: 'beg for it, brainless slut' },
        { text: 'cocksleeve', ex: 'good, cocksleeve' },
        { text: 'ass slut', ex: 'look at you, ass slut' },
        { text: 'throat whore', ex: 'you filthy throat whore' },
        { text: 'cockwhore', ex: 'open up, cockwhore' },
        { text: 'my little cockwhore', ex: "that's what you are — my little cockwhore" },
        { text: 'my dumb little slut', ex: 'look at you, my dumb little slut' },
        { text: 'my desperate slut', ex: 'come here, my desperate slut' },
        { text: 'my trained slut', ex: 'beg for it, my trained slut' },
        { text: 'my perfect little whore', ex: "you're my perfect little whore" },
        { text: 'my depraved girl', ex: 'good, my depraved girl', addresses: 'girl' },
        { text: 'depraved slut', ex: 'take it, depraved slut' },
        { text: 'my degenerate slut', ex: "say it — you're my degenerate slut" },
        { text: 'insatiable slut', ex: 'on your knees, insatiable slut' },
        { text: 'my starving slut', ex: 'come here, my starving slut' },
        { text: 'my whimpering slut', ex: "you're my whimpering slut" },
        { text: 'my mewling slut', ex: 'good, my mewling slut' },
        { text: 'my squirming slut', ex: "you're my squirming slut" },
        { text: 'my writhing slut', ex: "that's what you are — my writhing slut" },
        { text: 'my sobbing slut', ex: "say it — you're my sobbing slut" },
        { text: 'my drooling slut', ex: 'you love being my drooling slut' },
        { text: 'my leaking slut', ex: 'take it, my leaking slut' },
        { text: 'my dripping slut', ex: "that's it, my dripping slut" },
        { text: 'my soaking slut', ex: 'look at you, my soaking slut' },
        { text: 'my sloppy slut', ex: "you're my sloppy slut" },
        { text: 'my messy slut', ex: 'come here, my messy slut' },
        { text: 'my filthy little whore', ex: 'on your knees, my filthy little whore' },
        { text: 'my nasty little whore', ex: 'open up, my nasty little whore' },
        { text: 'my rotten girl', ex: 'beg for it, my rotten girl', addresses: 'girl' },
        { text: 'my slutty wife', ex: "you're my slutty wife", addresses: 'girl' },
        { text: 'my whore wife', ex: "that's what you are — my whore wife", addresses: 'girl' },
        { text: 'my mouth slut', ex: "say it — you're my mouth slut" },
        { text: 'my toy slut', ex: 'you love being my toy slut' },
        { text: 'my dumb whore', ex: 'take it, my dumb whore' },
        { text: 'my braindead slut', ex: "that's it, my braindead slut" },
        { text: 'my mindless slut', ex: 'look at you, my mindless slut' },
        { text: 'my broken slut', ex: "you're my broken slut" },
        { text: 'my ruined slut', ex: 'come here, my ruined slut' },
        { text: 'my used slut', ex: 'on your knees, my used slut' },
        { text: 'my well-fucked girl', ex: 'open up, my well-fucked girl', addresses: 'girl' },
        { text: 'slag', ex: 'look at you, slag' },
        { text: 'my little slag', ex: "say it — you're my little slag" },
        { text: 'my scrubber', ex: 'you love being my scrubber' },
        { text: 'my slapper', ex: 'take it, my slapper' },
        { text: 'skank', ex: 'beg for it, skank' },
        { text: 'my little skank', ex: "you're my little skank" },
        { text: 'my little cunt', ex: 'open up, my little cunt', body: 'vulva' },
        { text: 'my dirty cunt', ex: 'beg for it, my dirty cunt', body: 'vulva' },
        { text: 'my greedy cunt', ex: "you're my greedy cunt", body: 'vulva' },
        { text: 'fuckpig', ex: 'on your knees, fuckpig' },
        { text: 'my dirty pig', ex: "that's what you are — my dirty pig" },
        { text: 'my swine', ex: "say it — you're my swine" },
        { text: 'my creature', ex: 'you love being my creature' },
        { text: 'cum dumpster', ex: 'take it, cum dumpster' },
        { text: 'my spunk bucket', ex: 'look at you, my spunk bucket' },
        { text: 'my cum toilet', ex: "you're my cum toilet" },
        { text: 'my cock pig', ex: 'come here, my cock pig' },
        { text: 'my cock junkie', ex: 'open up, my cock junkie' },
        { text: 'my cock fiend', ex: 'beg for it, my cock fiend' },
        { text: 'my anal queen', ex: 'good, my anal queen' },
        { text: 'my throat queen', ex: "you're my throat queen" },
        { text: 'my deepthroat slut', ex: "that's what you are — my deepthroat slut" },
        { text: 'my gagging slut', ex: "say it — you're my gagging slut" },
        { text: 'my crying whore', ex: "that's it, my crying whore" },
        { text: 'my sobbing whore', ex: 'look at you, my sobbing whore' },
        { text: 'my broken whore', ex: "you're my broken whore" },
        { text: 'my wrecked whore', ex: 'come here, my wrecked whore' },
        { text: 'my destroyed slut', ex: 'on your knees, my destroyed slut' },
        { text: 'my personal fucktoy', ex: 'open up, my personal fucktoy' },
        { text: 'my private fucktoy', ex: 'beg for it, my private fucktoy' },
        { text: 'fuck puppet', ex: 'look at you, fuck puppet' },
        { text: 'my fuck pet', ex: "you're my fuck pet" },
        { text: 'sex slave', ex: 'open up, sex slave' },
        { text: 'my sex object', ex: 'take it, my sex object' },
        { text: 'my sex pet', ex: "that's it, my sex pet" },
        { text: 'my dumb bimbo', ex: 'beg for it, my dumb bimbo' },
        { text: 'my worthless whore', ex: "you're my worthless whore" },
        { text: 'my nasty whore', ex: "that's what you are — my nasty whore" },
        { text: 'my disgusting slut', ex: "say it — you're my disgusting slut" },
        { text: 'my vile thing', ex: 'you love being my vile thing' },
        { text: 'my willing hole', ex: "that's it, my willing hole" },
        { text: 'my eager hole', ex: 'look at you, my eager hole' },
        { text: 'my three-hole slut', ex: "you're my three-hole slut" },
        { text: 'my all-holes slut', ex: 'come here, my all-holes slut' },
        { text: "my daddy's slut", ex: "on your knees, my daddy's slut" },
        { text: "my daddy's whore", ex: "open up, my daddy's whore" },
        { text: "my master's slut", ex: "beg for it, my master's slut" },
        { text: "my owner's slut", ex: "you're my owner's slut" },
        { text: "my sir's slut", ex: "good, my sir's slut" },
        { text: "my king's whore", ex: "you're my king's whore" },
        { text: 'my street whore', ex: "that's what you are — my street whore" },
        { text: 'my back-alley slut', ex: "say it — you're my back-alley slut" },
        { text: 'my gutter slut', ex: 'you love being my gutter slut' },
        { text: 'my gutter trash', ex: 'take it, my gutter trash' },
        { text: 'my cheap little slut', ex: "that's it, my cheap little slut" },
        { text: 'my pussy slut', ex: 'look at you, my pussy slut' },
        { text: 'my mouth whore', ex: "you're my mouth whore" },
        { text: 'my toy whore', ex: 'come here, my toy whore' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-body',
      'Names — the body itself',
      'Being addressed AS a part of you, or as what your body is doing. The bank has plenty of anatomy lines and had no anatomy names at all.',
    ),
    {
      2: [
        { text: 'my body', ex: 'look at you, my body' },
        { text: 'my beautiful body', ex: 'god, my beautiful body' },
        { text: 'my soft body', ex: 'come here, my soft body' },
      ],
      3: [
        { text: 'my cock', ex: 'look at you, my cock', body: 'penis' },
        { text: 'my big cock', ex: "that's it, my big cock", body: 'penis' },
        { text: 'my big dick', ex: 'god, my big dick', body: 'penis' },
        { text: 'my dick', ex: 'come here, my dick', body: 'penis' },
        { text: 'my perfect cock', ex: "I can't stop looking at my perfect cock", body: 'penis' },
        { text: 'my beautiful cock', ex: 'all night, my beautiful cock', body: 'penis' },
        { text: 'my pretty cock', ex: 'right there, my pretty cock', body: 'penis' },
        { text: 'my pretty dick', ex: "you're my pretty dick", body: 'penis' },
        { text: 'my good cock', ex: "that's my good cock", body: 'penis' },
        { text: 'my good dick', ex: 'there it is — my good dick', body: 'penis' },
        { text: 'my favourite cock', ex: 'look at you, my favourite cock', body: 'penis' },
        { text: 'my pussy', ex: 'right there, my pussy', body: 'vulva' },
        { text: 'my perfect pussy', ex: "I can't stop looking at my perfect pussy", body: 'vulva' },
        { text: 'my pretty pussy', ex: 'all night, my pretty pussy', body: 'vulva' },
        { text: 'my beautiful pussy', ex: 'right there, my beautiful pussy', body: 'vulva' },
        { text: 'my sweet pussy', ex: "you're my sweet pussy", body: 'vulva' },
        { text: 'my sweet little pussy', ex: 'look at you, my sweet little pussy', body: 'vulva' },
        { text: 'my warm pussy', ex: "you're my warm pussy", body: 'vulva' },
        { text: 'my beautiful tits', ex: 'give me my beautiful tits' },
        { text: 'my soft tits', ex: 'right there, my soft tits' },
        { text: 'my sweet tits', ex: "you're my sweet tits" },
        { text: 'my pretty tits', ex: 'look at you, my pretty tits' },
        { text: 'my sweet ass', ex: 'all night, my sweet ass' },
        { text: 'my beautiful ass', ex: 'right there, my beautiful ass' },
        { text: 'my mouth', ex: "that's my mouth" },
        { text: 'my perfect body', ex: "that's it, my perfect body" },
      ],
      4: [
        { text: 'my hard cock', ex: 'give me my hard cock', body: 'penis' },
        { text: 'my hard dick', ex: "I can't stop looking at my hard dick", body: 'penis' },
        { text: 'my throbbing cock', ex: 'all night, my throbbing cock', body: 'penis' },
        { text: 'my throbbing dick', ex: 'right there, my throbbing dick', body: 'penis' },
        { text: 'my thick cock', ex: "you're my thick cock", body: 'penis' },
        { text: 'my thick dick', ex: "that's my thick dick", body: 'penis' },
        { text: 'my fat cock', ex: 'there it is — my fat cock', body: 'penis' },
        { text: 'my fat dick', ex: 'look at you, my fat dick', body: 'penis' },
        { text: 'my heavy cock', ex: "that's it, my heavy cock", body: 'penis' },
        { text: 'my huge cock', ex: 'god, my huge cock', body: 'penis' },
        { text: 'my massive cock', ex: 'come here, my massive cock', body: 'penis' },
        { text: 'my swollen cock', ex: "that's it, my swollen cock", body: 'penis' },
        { text: 'my aching cock', ex: 'god, my aching cock', body: 'penis' },
        { text: 'my straining cock', ex: 'come here, my straining cock', body: 'penis' },
        { text: 'my twitching cock', ex: 'give me my twitching cock', body: 'penis' },
        { text: 'my pulsing cock', ex: "I can't stop looking at my pulsing cock", body: 'penis' },
        { text: 'my needy cock', ex: "you're my needy cock", body: 'penis' },
        { text: 'my greedy cock', ex: "that's my greedy cock", body: 'penis' },
        { text: 'my hungry cock', ex: 'there it is — my hungry cock', body: 'penis' },
        { text: 'my ready cock', ex: 'look at you, my ready cock', body: 'penis' },
        { text: 'my rod', ex: 'god, my rod', body: 'penis' },
        { text: 'my weapon', ex: 'come here, my weapon', body: 'penis' },
        { text: 'my tight pussy', ex: "you're my tight pussy", body: 'vulva' },
        { text: 'my wet pussy', ex: "that's my wet pussy", body: 'vulva' },
        { text: 'my slick pussy', ex: 'there it is — my slick pussy', body: 'vulva' },
        { text: 'my greedy pussy', ex: 'god, my greedy pussy', body: 'vulva' },
        { text: 'my hungry pussy', ex: 'come here, my hungry pussy', body: 'vulva' },
        { text: 'my needy pussy', ex: 'give me my needy pussy', body: 'vulva' },
        { text: 'my little pussy', ex: "that's my little pussy", body: 'vulva' },
        { text: 'my tight little pussy', ex: 'there it is — my tight little pussy', body: 'vulva' },
        { text: 'my aching pussy', ex: 'give me my aching pussy', body: 'vulva' },
        { text: 'my hot pussy', ex: "that's my hot pussy", body: 'vulva' },
        { text: 'my good pussy', ex: 'there it is — my good pussy', body: 'vulva' },
        { text: 'my favourite pussy', ex: 'look at you, my favourite pussy', body: 'vulva' },
        { text: 'my tits', ex: 'god, my tits' },
        { text: 'my perfect tits', ex: 'come here, my perfect tits' },
        { text: 'my full tits', ex: 'all night, my full tits' },
        { text: 'my big tits', ex: "that's my big tits" },
        { text: 'my little tits', ex: 'there it is — my little tits' },
        { text: 'my nipples', ex: "that's it, my nipples" },
        { text: 'my hard nipples', ex: 'god, my hard nipples' },
        { text: 'my ass', ex: 'come here, my ass' },
        { text: 'my perfect ass', ex: 'give me my perfect ass' },
        { text: 'my tight ass', ex: "I can't stop looking at my tight ass" },
        { text: 'my round ass', ex: "you're my round ass" },
        { text: 'my fat ass', ex: "that's my fat ass" },
        { text: 'my juicy ass', ex: 'there it is — my juicy ass' },
        { text: 'my thick ass', ex: 'look at you, my thick ass' },
        { text: 'my little ass', ex: "that's it, my little ass" },
        { text: 'my wet girl', ex: "I can't stop looking at my wet girl", addresses: 'girl' },
        { text: 'my wet thing', ex: 'there it is — my wet thing' },
        { text: 'my aching girl', ex: 'look at you, my aching girl', addresses: 'girl' },
        { text: 'my squirming girl', ex: "that's it, my squirming girl", addresses: 'girl' },
        { text: 'my quivering girl', ex: 'give me my quivering girl', addresses: 'girl' },
        { text: 'my gasping girl', ex: 'all night, my gasping girl', addresses: 'girl' },
        { text: 'my panting girl', ex: 'right there, my panting girl', addresses: 'girl' },
        { text: 'my sweaty girl', ex: 'there it is — my sweaty girl', addresses: 'girl' },
        { text: 'my desperate girl', ex: 'all night, my desperate girl', addresses: 'girl' },
        { text: 'my begging girl', ex: 'right there, my begging girl', addresses: 'girl' },
        { text: 'my whimpering girl', ex: "you're my whimpering girl", addresses: 'girl' },
        { text: 'my moaning girl', ex: "that's my moaning girl", addresses: 'girl' },
        { text: 'my hard boy', ex: "that's it, my hard boy", addresses: 'man' },
        { text: 'my aching boy', ex: 'god, my aching boy', addresses: 'man' },
        { text: 'my straining boy', ex: 'come here, my straining boy', addresses: 'man' },
        { text: 'my desperate boy', ex: 'give me my desperate boy', addresses: 'man' },
      ],
      5: [
        { text: 'my monster cock', ex: 'give me my monster cock', body: 'penis' },
        { text: 'my dripping cock', ex: 'all night, my dripping cock', body: 'penis' },
        { text: 'my leaking cock', ex: 'right there, my leaking cock', body: 'penis' },
        { text: 'my angry cock', ex: "that's it, my angry cock", body: 'penis' },
        { text: 'my heavy balls', ex: 'give me my heavy balls', body: 'penis' },
        { text: 'my full balls', ex: "I can't stop looking at my full balls", body: 'penis' },
        { text: 'my swollen balls', ex: 'all night, my swollen balls', body: 'penis' },
        { text: 'my dripping pussy', ex: 'look at you, my dripping pussy', body: 'vulva' },
        { text: 'my soaked pussy', ex: "that's it, my soaked pussy", body: 'vulva' },
        { text: 'my fat pussy', ex: "that's it, my fat pussy", body: 'vulva' },
        { text: 'my puffy pussy', ex: 'god, my puffy pussy', body: 'vulva' },
        { text: 'my swollen pussy', ex: 'come here, my swollen pussy', body: 'vulva' },
        {
          text: 'my throbbing pussy',
          ex: "I can't stop looking at my throbbing pussy",
          body: 'vulva',
        },
        { text: 'my clenching pussy', ex: 'all night, my clenching pussy', body: 'vulva' },
        { text: 'my gripping pussy', ex: 'right there, my gripping pussy', body: 'vulva' },
        { text: 'my cunt', ex: "that's it, my cunt", body: 'vulva' },
        { text: 'my tight cunt', ex: 'god, my tight cunt', body: 'vulva' },
        { text: 'my wet cunt', ex: 'come here, my wet cunt', body: 'vulva' },
        { text: 'my slick cunt', ex: 'give me my slick cunt', body: 'vulva' },
        { text: 'my dripping cunt', ex: "I can't stop looking at my dripping cunt", body: 'vulva' },
        { text: 'my perfect cunt', ex: 'all night, my perfect cunt', body: 'vulva' },
        { text: 'my sweet cunt', ex: 'right there, my sweet cunt', body: 'vulva' },
        { text: 'my hot cunt', ex: "you're my hot cunt", body: 'vulva' },
        { text: 'my wet little cunt', ex: "that's my wet little cunt", body: 'vulva' },
        { text: 'my swollen clit', ex: 'there it is — my swollen clit', body: 'vulva' },
        { text: 'my hard clit', ex: 'look at you, my hard clit', body: 'vulva' },
        { text: 'my needy clit', ex: "that's it, my needy clit", body: 'vulva' },
        { text: 'my tight hole', ex: 'god, my tight hole' },
        { text: 'my wet hole', ex: 'come here, my wet hole' },
        { text: 'my sweet hole', ex: 'give me my sweet hole' },
        { text: 'my little hole', ex: "I can't stop looking at my little hole" },
        { text: 'my tight throat', ex: 'right there, my tight throat' },
        { text: 'my sweet throat', ex: "you're my sweet throat" },
        { text: 'my dripping girl', ex: 'give me my dripping girl', addresses: 'girl' },
        { text: 'my soaked girl', ex: 'all night, my soaked girl', addresses: 'girl' },
        { text: 'my slick girl', ex: 'right there, my slick girl', addresses: 'girl' },
        { text: 'my messy girl', ex: "you're my messy girl", addresses: 'girl' },
        { text: 'my dripping thing', ex: "that's my dripping thing" },
        { text: 'my stretched girl', ex: 'look at you, my stretched girl', addresses: 'girl' },
        { text: 'my filled girl', ex: "that's it, my filled girl", addresses: 'girl' },
        { text: 'my full girl', ex: 'god, my full girl', addresses: 'girl' },
        { text: 'my screaming girl', ex: 'there it is — my screaming girl', addresses: 'girl' },
        { text: 'my leaking boy', ex: "I can't stop looking at my leaking boy", addresses: 'man' },
        { text: 'my dripping boy', ex: 'all night, my dripping boy', addresses: 'man' },
      ],
    },
  ),
]);
