import { bankFamily, buildBank, type Bank, type BankFamily } from '../bank';

/**
 * 74 §3.6.8 — the PET-NAME bank: what the two of you call each other, across 24 registers from the
 * warmest to the furthest, every one marked TWICE (being called it, and calling them it).
 *
 * Separate from the phrase bank because it is answered in its own phase, before the vocabulary, and
 * because a name is a different kind of thing: a vocative, usable in any generated line, where a phrase
 * can only be quoted. `phase: 'names'` is what keeps these out of the deck and in that phase.
 *
 * **Boundary (absolute):** consensual adults; every roleplay register — kinship, authority, innocence,
 * age gap — is PRE-AGREED ROLEPLAY between adults, never a real relative, never anyone underage, never
 * anything illegal. Carried by the content and the model, never a keyword filter.
 *
 * Each name carries a line showing it in use, in its register's voice, so a bare word is never the whole
 * row. The lines were composed from per-register frames rather than written one by one — at this size that
 * is the honest way to get a consistent voice, and it is stated here rather than implied.
 */

const nameFamily = (id: string, label: string, note: string): BankFamily => ({
  id,
  label,
  kind: 'word',
  directions: ['hear', 'say'],
  // Marked in the pet-name phase, never in the deck (74 §3.6.8).
  phase: 'names',
  note,
});

export const DIRTY_TALK_NAMES: Bank = buildBank([
  bankFamily(
    nameFamily(
      'names-warm',
      'Names — warm & sweet',
      'The ones that work outside the bedroom too. Some people want these all the way through; some want them nowhere near sex.',
    ),
    {
      1: [
        { text: 'baby', ex: 'come here, baby' },
        { text: 'babe', ex: 'look at me, babe' },
        { text: 'beautiful', ex: 'you feel so good, beautiful' },
        { text: 'gorgeous', ex: 'hi, gorgeous' },
        { text: 'sweet girl', ex: 'hey, sweet girl', addresses: 'girl' },
        { text: 'cutie', ex: 'come closer, cutie' },
      ],
      2: [
        { text: 'beautiful girl', ex: "that's it, beautiful girl", addresses: 'girl' },
        { text: 'beautiful boy', ex: "I've got you, beautiful boy", addresses: 'man' },
        { text: 'gorgeous girl', ex: 'morning, gorgeous girl', addresses: 'girl' },
        { text: 'pretty girl', ex: 'stay right there, pretty girl', addresses: 'girl' },
        { text: 'pretty boy', ex: 'come closer, pretty boy', addresses: 'man' },
        { text: 'pretty thing', ex: 'I missed you, pretty thing' },
        { text: 'sweet thing', ex: "you're perfect, sweet thing" },
        { text: 'lover', ex: 'I missed you, lover' },
        { text: 'doll face', ex: "you're perfect, doll face" },
        { text: 'gorgeous thing', ex: "I've got you, gorgeous thing" },
        { text: 'beautiful thing', ex: 'hi, beautiful thing' },
        { text: 'my pretty', ex: 'I missed you, my pretty' },
        { text: 'pretty face', ex: 'stay right there, pretty face' },
        { text: 'angel face', ex: 'come closer, angel face' },
        { text: 'babydoll', ex: 'I missed you, babydoll' },
        { text: 'sweet cheeks', ex: 'you feel so good, sweet cheeks' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-yours',
      'Names — yours',
      'Belonging without the power framing. This is the register your “my girl” example sits in.',
    ),
    {
      1: [
        { text: 'mine', ex: 'come here, mine' },
        { text: 'my girl', ex: 'say it — my girl', addresses: 'girl' },
        { text: 'my baby', ex: "you'll always be my baby" },
        { text: 'my babe', ex: "say you're my babe" },
        { text: 'my sweetheart', ex: "you know you're my sweetheart" },
      ],
      2: [
        { text: 'all mine', ex: "that's it, all mine" },
        { text: 'my woman', ex: 'look at me, my woman', addresses: 'girl' },
        { text: 'my man', ex: 'all night, my man', addresses: 'man' },
        { text: 'my boy', ex: "you're my boy", addresses: 'man' },
        { text: 'my sweet girl', ex: 'all night, my sweet girl', addresses: 'girl' },
        { text: 'my sweet boy', ex: "you're my sweet boy", addresses: 'man' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-praise',
      'Names — praise',
      "Being told you're good at it — the single most-loved register in most profiles.",
    ),
    {
      2: [
        { text: 'good girl', ex: "that's it, good girl", addresses: 'girl' },
        { text: 'good boy', ex: 'good — good boy', addresses: 'man' },
        { text: 'best girl', ex: 'there she is, best girl', addresses: 'girl' },
        { text: 'perfect girl', ex: 'well done, perfect girl', addresses: 'girl' },
        { text: 'perfect boy', ex: 'so good for me, perfect boy', addresses: 'man' },
        { text: 'golden girl', ex: "that's it, golden girl", addresses: 'girl' },
        { text: 'golden boy', ex: 'look at you, golden boy', addresses: 'man' },
        { text: 'my precious thing', ex: 'perfect, my precious thing' },
        { text: 'my dream girl', ex: "you're my dream girl", addresses: 'girl' },
        { text: 'my dream boy', ex: 'there he is — my dream boy', addresses: 'man' },
        {
          text: 'my favourite girl',
          ex: "you're doing so well, my favourite girl",
          addresses: 'girl',
        },
        { text: 'my favourite boy', ex: "that's it, my favourite boy", addresses: 'man' },
        { text: 'my favourite thing', ex: 'good — my favourite thing' },
        { text: 'my pearl', ex: 'perfect, my pearl' },
      ],
      3: [
        { text: 'my perfect little thing', ex: "that's it — my perfect little thing" },
        { text: 'my flawless girl', ex: 'well done, my flawless girl', addresses: 'girl' },
        { text: 'my flawless boy', ex: 'so good for me, my flawless boy', addresses: 'man' },
        { text: 'my good little thing', ex: "you're doing so well, my good little thing" },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-soft-power',
      'Names — looked after',
      'The cared-for side of a power dynamic. Adults only, and the framing stays adult throughout.',
    ),
    {
      2: [{ text: 'little angel', ex: 'look at me, little angel' }],
      3: [
        { text: 'princess', ex: 'come here, princess', addresses: 'girl' },
        { text: 'babygirl', ex: 'good, babygirl', addresses: 'girl' },
        { text: 'boy', ex: 'up here, boy', addresses: 'man' },
        { text: 'girl', ex: 'easy, girl', addresses: 'girl' },
        { text: 'kitten', ex: 'come here, kitten' },
        { text: 'kitty', ex: "that's it, kitty" },
        { text: 'bunny', ex: 'up here, bunny' },
        { text: 'pet', ex: 'come here, pet' },
        { text: 'my sub', ex: 'on your knees, my sub' },
        { text: 'my sweet sub', ex: 'easy, my sweet sub' },
        { text: 'my sweet pet', ex: 'come here, my sweet pet' },
        { text: 'my little pet', ex: "that's it, my little pet" },
        { text: 'my precious pet', ex: 'good, my precious pet' },
        { text: 'kitty cat', ex: 'on your knees, kitty cat' },
        { text: 'my sweet kitty', ex: 'come here, my sweet kitty' },
        { text: 'mouse', ex: 'stay there, mouse' },
        { text: 'tiny thing', ex: 'stay there, tiny thing' },
        { text: 'my small one', ex: 'easy, my small one' },
        { text: 'little thing', ex: 'come here, little thing' },
        { text: 'my delicate thing', ex: 'sweet little thing — my delicate thing' },
        { text: 'my sweet little pet', ex: "that's my sweet little pet" },
        { text: 'my soft one', ex: 'easy, my soft one' },
        { text: 'bunny girl', ex: 'good, bunny girl', addresses: 'girl' },
      ],
      4: [
        { text: 'doll', ex: 'up here, doll' },
        { text: 'dolly', ex: 'easy, dolly' },
        { text: 'brat', ex: 'sweet little thing — brat' },
        { text: 'little brat', ex: "that's it, little brat" },
        { text: 'spoiled brat', ex: 'good, spoiled brat' },
        { text: 'spoiled little thing', ex: 'up here, spoiled little thing' },
        { text: 'my sweet brat', ex: 'up here, my sweet brat' },
        { text: 'my needy girl', ex: 'on your knees, my needy girl', addresses: 'girl' },
        { text: 'my needy boy', ex: 'easy, my needy boy', addresses: 'man' },
        { text: 'my little doll', ex: 'stay there, my little doll' },
        { text: 'my obedient pet', ex: 'good, my obedient pet' },
        { text: 'pillow princess', ex: 'up here, pillow princess', addresses: 'girl' },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-hard-power',
      'Names — in charge',
      'Titles. These matter in both directions — the one you want to be called and the one you want to use.',
    ),
    {
      3: [
        { text: 'sir', ex: 'yes, sir', addresses: 'man' },
        { text: "ma'am", ex: "please, ma'am", addresses: 'girl' },
        { text: 'miss', ex: 'thank you, miss', addresses: 'girl' },
        { text: 'mistress', ex: "I'm yours, mistress", addresses: 'girl' },
        { text: 'daddy', ex: 'of course, daddy', addresses: 'man' },
        { text: 'mommy', ex: 'please, mommy', addresses: 'girl' },
        { text: 'king', ex: 'as you say, king', addresses: 'man' },
        { text: 'queen', ex: 'whatever you want, queen', addresses: 'girl' },
        { text: 'goddess', ex: 'yes, goddess', addresses: 'girl' },
        { text: 'boss', ex: 'please, boss' },
        { text: 'my dom', ex: 'as you say, my dom' },
        { text: 'my domme', ex: "I'm yours, my domme", addresses: 'girl' },
        { text: 'madam', ex: 'as you say, madam', addresses: 'girl' },
      ],
      4: [
        { text: 'master', ex: 'anything you want, master', addresses: 'man' },
        { text: 'my god', ex: "you're my god", addresses: 'man' },
        { text: 'owner', ex: 'of course, owner' },
        { text: 'alpha', ex: 'as you say, alpha' },
        { text: 'my director', ex: "you're my director" },
        { text: 'dominatrix', ex: 'of course, dominatrix', addresses: 'girl' },
      ],
      5: [],
    },
  ),

  bankFamily(
    nameFamily(
      'names-worship',
      'Names — worship',
      'Not praise for what you did — devotion for what you are. A distinct register, and a common one for the person on top.',
    ),
    {
      2: [],
      3: [
        { text: 'my obsession', ex: 'look at you, my obsession' },
        { text: 'my weakness', ex: "you're my weakness" },
        { text: 'my idol', ex: 'look at you, my idol' },
        { text: 'my heaven', ex: 'god, my heaven' },
        { text: 'my paradise', ex: 'look at you, my paradise' },
        { text: 'my guilty pleasure', ex: "that's what you are — my guilty pleasure" },
        { text: 'my nectar', ex: "you'll be the end of me, my nectar" },
      ],
      4: [
        { text: 'my religion', ex: 'god, my religion' },
        { text: 'my addiction', ex: 'come here, my addiction' },
        { text: 'my drug', ex: "I can't get enough, my drug" },
        { text: 'my ruin', ex: 'you are my ruin' },
        { text: 'my undoing', ex: "that's what you are — my undoing" },
        { text: 'my vice', ex: "I can't get enough, my vice" },
        { text: 'my sin', ex: "you're my sin" },
        { text: 'my favourite sin', ex: 'you are my favourite sin' },
        { text: 'my drug of choice', ex: "you'll be the end of me, my drug of choice" },
        { text: 'my high', ex: 'god, my high' },
        { text: 'my fix', ex: 'look at you, my fix' },
        { text: 'my madness', ex: 'come here, my madness' },
        { text: 'my intoxication', ex: "you're my intoxication" },
        { text: 'my poison', ex: 'you are my poison' },
        { text: 'my venom', ex: "that's what you are — my venom" },
      ],
      5: [],
    },
  ),
  bankFamily(
    nameFamily(
      'names-rough-mild',
      'Names — rough, mild',
      'Naughty rather than degrading. For a lot of people this is as far as the rough register goes.',
    ),
    {
      2: [
        { text: 'my little freak', ex: 'behave, my little freak' },
        { text: 'freak', ex: 'get over here, freak' },
        { text: 'flirt', ex: "you're such a flirt" },
        { text: 'cheeky thing', ex: 'come here, cheeky thing' },
      ],
      3: [
        { text: 'naughty girl', ex: 'come here, naughty girl', addresses: 'girl' },
        { text: 'naughty boy', ex: "you're such a naughty boy", addresses: 'man' },
        { text: 'bad girl', ex: 'look at you, bad girl', addresses: 'girl' },
        { text: 'bad boy', ex: "someone's been a bad boy", addresses: 'man' },
        { text: 'dirty girl', ex: 'you little dirty girl', addresses: 'girl' },
        { text: 'dirty boy', ex: 'behave, dirty boy', addresses: 'man' },
        { text: 'filthy little thing', ex: "that's it, filthy little thing" },
        { text: 'greedy girl', ex: 'get over here, greedy girl', addresses: 'girl' },
        { text: 'greedy boy', ex: 'come here, greedy boy', addresses: 'man' },
        { text: 'little tease', ex: "you're such a little tease" },
        { text: 'tease', ex: 'look at you, tease' },
        { text: 'cocktease', ex: "someone's been a cocktease" },
        { text: 'minx', ex: 'you little minx', addresses: 'girl' },
        { text: 'little devil', ex: 'behave, little devil' },
        { text: 'little demon', ex: "that's it, little demon" },
        { text: 'wicked girl', ex: 'get over here, wicked girl', addresses: 'girl' },
        { text: 'wicked thing', ex: 'come here, wicked thing' },
        { text: 'little liar', ex: 'look at you, little liar' },
        { text: 'filthy girl', ex: "someone's been a filthy girl", addresses: 'girl' },
        { text: 'filthy boy', ex: 'you little filthy boy', addresses: 'man' },
        { text: 'naughty thing', ex: 'behave, naughty thing' },
        { text: 'naughty little thing', ex: "that's it, naughty little thing" },
        { text: 'dirty little thing', ex: 'get over here, dirty little thing' },
        { text: 'filthy thing', ex: 'come here, filthy thing' },
        { text: 'bad thing', ex: "you're such a bad thing" },
        { text: 'wicked little thing', ex: 'look at you, wicked little thing' },
        { text: 'sinful thing', ex: "someone's been a sinful thing" },
        { text: 'sinner', ex: 'you little sinner' },
        { text: 'little sinner', ex: 'behave, little sinner' },
        { text: 'little flirt', ex: 'look at you, little flirt' },
        { text: 'temptress', ex: 'get over here, temptress', addresses: 'girl' },
        { text: 'seductress', ex: "you're such a seductress", addresses: 'girl' },
        { text: 'naughty kitten', ex: "you're such a naughty kitten" },
        { text: 'bad kitten', ex: 'look at you, bad kitten' },
        { text: 'bad pet', ex: "someone's been a bad pet" },
        { text: 'little sneak', ex: "you're such a little sneak" },
        { text: 'my little cheat', ex: "that's my little cheat for you" },
        { text: 'my spoiled thing', ex: "you're my spoiled thing" },
        { text: 'my greedy thing', ex: 'look at you, my greedy thing' },
        { text: 'my hungry girl', ex: "you're my hungry girl", addresses: 'girl' },
        { text: 'my hungry thing', ex: "you're my hungry thing" },
        { text: 'my eager thing', ex: 'behave, my eager thing' },
        { text: 'my eager one', ex: "that's it, my eager one" },
        { text: 'my brazen girl', ex: "you're my brazen girl", addresses: 'girl' },
        { text: 'brazen thing', ex: 'behave, brazen thing' },
        { text: 'my bold one', ex: 'come here, my bold one' },
        { text: 'my daring one', ex: "you're my daring one" },
        { text: 'my reckless one', ex: 'look at you, my reckless one' },
        { text: 'my flirty thing', ex: 'get over here, my flirty thing' },
        { text: 'spitfire', ex: 'look at you, spitfire' },
        {
          text: 'naughty little minx',
          ex: "someone's been a naughty little minx",
          addresses: 'girl',
        },
        { text: 'my little minx', ex: 'look at you, my little minx', addresses: 'girl' },
        { text: 'saucy thing', ex: 'behave, saucy thing' },
        { text: 'saucy minx', ex: "that's it, saucy minx", addresses: 'girl' },
        { text: 'my cheeky brat', ex: "that's my cheeky brat for you" },
        { text: 'my feisty one', ex: "you're my feisty one" },
        { text: 'feisty thing', ex: 'come here, feisty thing' },
        { text: 'my mouthy girl', ex: 'behave, my mouthy girl', addresses: 'girl' },
        { text: 'mouthy thing', ex: 'you little mouthy thing' },
        { text: 'my back-talker', ex: "you're my back-talker" },
        { text: 'my little rebel', ex: "you're my little rebel" },
        { text: 'my handful', ex: 'get over here, my handful' },
        { text: 'my little handful', ex: "you're my little handful" },
        { text: 'my little problem', ex: "that's my little problem for you" },
        { text: 'my bad influence', ex: 'come here, my bad influence' },
        { text: 'my dirty little secret', ex: "you're my dirty little secret" },
        { text: 'my guilty one', ex: 'look at you, my guilty one' },
        { text: 'my little show-off', ex: "that's it, my little show-off" },
        { text: 'my attention seeker', ex: 'get over here, my attention seeker' },
        { text: 'my greedy little thing', ex: "that's my greedy little thing for you" },
        { text: 'my impatient one', ex: 'come here, my impatient one' },
        { text: 'my restless one', ex: "you're my restless one" },
        { text: 'my little squirmer', ex: 'look at you, my little squirmer' },
        { text: 'my awful tease', ex: 'behave, my awful tease' },
        { text: 'my little firestarter', ex: "that's it, my little firestarter" },
        { text: 'my instigator', ex: 'get over here, my instigator' },
        { text: 'my bad habit', ex: "you're my bad habit" },
        { text: 'my indulgence', ex: "that's my indulgence for you" },
        { text: 'my little indulgence', ex: 'come here, my little indulgence' },
      ],
      4: [
        { text: 'my little exhibitionist', ex: "you're my little exhibitionist" },
        { text: 'my forbidden one', ex: 'look at you, my forbidden one' },
        { text: 'my forbidden thing', ex: "you're my forbidden thing" },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-rough-heavy',
      'Names — rough, heavy',
      'Your “my little cum queen” lives here, along with the rest of the crude register.',
    ),
    {
      4: [
        { text: 'manwhore', ex: 'take it, manwhore', addresses: 'man' },
        { text: 'cock worshipper', ex: 'open up, cock worshipper' },
        { text: 'dick sucker', ex: 'take it, dick sucker' },
        { text: 'slutty little thing', ex: 'on your knees, slutty little thing' },
        { text: 'my private whore', ex: "that's it, my private whore" },
        { text: 'my cock addict', ex: 'on your knees, my cock addict' },
        { text: 'my cock queen', ex: "you're my cock queen" },
        { text: 'my sex toy', ex: "that's what you are — my sex toy" },
      ],
      5: [
        { text: 'my little cum queen', ex: "that's it, my little cum queen" },
        { text: 'anal slut', ex: 'come here, anal slut' },
        { text: 'my dirty little whore', ex: 'you love being my dirty little whore' },
        { text: 'ass slut', ex: 'look at you, ass slut' },
        { text: 'my perfect little whore', ex: "you're my perfect little whore" },
        { text: 'my dripping slut', ex: "that's it, my dripping slut" },
        { text: 'my little cunt', ex: 'open up, my little cunt', body: 'vulva' },
        { text: 'my anal queen', ex: 'good, my anal queen' },
        { text: 'my private fucktoy', ex: 'beg for it, my private fucktoy' },
        { text: 'fuck puppet', ex: 'look at you, fuck puppet' },
        { text: 'sex slave', ex: 'open up, sex slave' },
        { text: 'my sex object', ex: 'take it, my sex object' },
        { text: 'my sex pet', ex: "that's it, my sex pet" },
        { text: 'my three-hole slut', ex: "you're my three-hole slut" },
      ],
    },
  ),
  bankFamily(
    nameFamily(
      'names-body',
      'Names — the body itself',
      'Being addressed AS a part of you, or as what your body is doing. The bank has plenty of anatomy lines and had no anatomy names at all.',
    ),
    {
      2: [
        { text: 'my body', ex: 'look at you, my body' },
        { text: 'my beautiful body', ex: 'god, my beautiful body' },
        { text: 'my soft body', ex: 'come here, my soft body' },
      ],
      3: [
        { text: 'my cock', ex: 'look at you, my cock', body: 'penis' },
        { text: 'my big cock', ex: "that's it, my big cock", body: 'penis' },
        { text: 'my big dick', ex: 'god, my big dick', body: 'penis' },
        { text: 'my dick', ex: 'come here, my dick', body: 'penis' },
        { text: 'my perfect cock', ex: "I can't stop looking at my perfect cock", body: 'penis' },
        { text: 'my beautiful cock', ex: 'all night, my beautiful cock', body: 'penis' },
        { text: 'my pretty cock', ex: 'right there, my pretty cock', body: 'penis' },
        { text: 'my pretty dick', ex: "you're my pretty dick", body: 'penis' },
        { text: 'my good cock', ex: "that's my good cock", body: 'penis' },
        { text: 'my good dick', ex: 'there it is — my good dick', body: 'penis' },
        { text: 'my favourite cock', ex: 'look at you, my favourite cock', body: 'penis' },
        { text: 'my pussy', ex: 'right there, my pussy', body: 'vulva' },
        { text: 'my perfect pussy', ex: "I can't stop looking at my perfect pussy", body: 'vulva' },
        { text: 'my pretty pussy', ex: 'all night, my pretty pussy', body: 'vulva' },
        { text: 'my beautiful pussy', ex: 'right there, my beautiful pussy', body: 'vulva' },
        { text: 'my sweet pussy', ex: "you're my sweet pussy", body: 'vulva' },
        { text: 'my sweet little pussy', ex: 'look at you, my sweet little pussy', body: 'vulva' },
        { text: 'my warm pussy', ex: "you're my warm pussy", body: 'vulva' },
        { text: 'my beautiful tits', ex: 'give me my beautiful tits' },
        { text: 'my soft tits', ex: 'right there, my soft tits' },
        { text: 'my sweet tits', ex: "you're my sweet tits" },
        { text: 'my pretty tits', ex: 'look at you, my pretty tits' },
        { text: 'my sweet ass', ex: 'all night, my sweet ass' },
        { text: 'my beautiful ass', ex: 'right there, my beautiful ass' },
        { text: 'my perfect body', ex: "that's it, my perfect body" },
        { text: 'my mouth', ex: 'look at you, my mouth' },
      ],
      4: [
        { text: 'my hard cock', ex: 'give me my hard cock', body: 'penis' },
        { text: 'my hard dick', ex: "I can't stop looking at my hard dick", body: 'penis' },
        { text: 'my throbbing cock', ex: 'all night, my throbbing cock', body: 'penis' },
        { text: 'my throbbing dick', ex: 'right there, my throbbing dick', body: 'penis' },
        { text: 'my thick cock', ex: "you're my thick cock", body: 'penis' },
        { text: 'my thick dick', ex: "that's my thick dick", body: 'penis' },
        { text: 'my fat cock', ex: 'there it is — my fat cock', body: 'penis' },
        { text: 'my fat dick', ex: 'look at you, my fat dick', body: 'penis' },
        { text: 'my heavy cock', ex: "that's it, my heavy cock", body: 'penis' },
        { text: 'my huge cock', ex: 'god, my huge cock', body: 'penis' },
        { text: 'my massive cock', ex: 'come here, my massive cock', body: 'penis' },
        { text: 'my swollen cock', ex: "that's it, my swollen cock", body: 'penis' },
        { text: 'my aching cock', ex: 'god, my aching cock', body: 'penis' },
        { text: 'my twitching cock', ex: 'give me my twitching cock', body: 'penis' },
        { text: 'my pulsing cock', ex: "I can't stop looking at my pulsing cock", body: 'penis' },
        { text: 'my needy cock', ex: "you're my needy cock", body: 'penis' },
        { text: 'my greedy cock', ex: "that's my greedy cock", body: 'penis' },
        { text: 'my hungry cock', ex: 'there it is — my hungry cock', body: 'penis' },
        { text: 'my ready cock', ex: 'look at you, my ready cock', body: 'penis' },
        { text: 'my rod', ex: 'god, my rod', body: 'penis' },
        { text: 'my tight pussy', ex: "you're my tight pussy", body: 'vulva' },
        { text: 'my wet pussy', ex: "that's my wet pussy", body: 'vulva' },
        { text: 'my slick pussy', ex: 'there it is — my slick pussy', body: 'vulva' },
        { text: 'my greedy pussy', ex: 'god, my greedy pussy', body: 'vulva' },
        { text: 'my hungry pussy', ex: 'come here, my hungry pussy', body: 'vulva' },
        { text: 'my needy pussy', ex: 'give me my needy pussy', body: 'vulva' },
        { text: 'my little pussy', ex: "that's my little pussy", body: 'vulva' },
        { text: 'my tight little pussy', ex: 'there it is — my tight little pussy', body: 'vulva' },
        { text: 'my aching pussy', ex: 'give me my aching pussy', body: 'vulva' },
        { text: 'my hot pussy', ex: "that's my hot pussy", body: 'vulva' },
        { text: 'my good pussy', ex: 'there it is — my good pussy', body: 'vulva' },
        { text: 'my favourite pussy', ex: 'look at you, my favourite pussy', body: 'vulva' },
        { text: 'my tits', ex: 'god, my tits' },
        { text: 'my perfect tits', ex: 'come here, my perfect tits' },
        { text: 'my full tits', ex: 'all night, my full tits' },
        { text: 'my big tits', ex: "that's my big tits" },
        { text: 'my little tits', ex: 'there it is — my little tits' },
        { text: 'my nipples', ex: "that's it, my nipples" },
        { text: 'my hard nipples', ex: 'god, my hard nipples' },
        { text: 'my ass', ex: 'come here, my ass' },
        { text: 'my perfect ass', ex: 'give me my perfect ass' },
        { text: 'my tight ass', ex: "I can't stop looking at my tight ass" },
        { text: 'my round ass', ex: "you're my round ass" },
        { text: 'my fat ass', ex: "that's my fat ass" },
        { text: 'my juicy ass', ex: 'there it is — my juicy ass' },
        { text: 'my thick ass', ex: 'look at you, my thick ass' },
        { text: 'my little ass', ex: "that's it, my little ass" },
        { text: 'my wet girl', ex: "I can't stop looking at my wet girl", addresses: 'girl' },
        { text: 'my wet thing', ex: 'there it is — my wet thing' },
        { text: 'my quivering girl', ex: 'give me my quivering girl', addresses: 'girl' },
        { text: 'my gasping girl', ex: 'all night, my gasping girl', addresses: 'girl' },
        { text: 'my panting girl', ex: 'right there, my panting girl', addresses: 'girl' },
        { text: 'my desperate girl', ex: 'all night, my desperate girl', addresses: 'girl' },
        { text: 'my moaning girl', ex: "that's my moaning girl", addresses: 'girl' },
        { text: 'my hard boy', ex: "that's it, my hard boy", addresses: 'man' },
        { text: 'my desperate boy', ex: 'give me my desperate boy', addresses: 'man' },
        { text: 'my greedy mouth', ex: 'there it is — my greedy mouth' },
        { text: 'my clit', ex: 'right there, my clit', body: 'vulva' },
        { text: 'my balls', ex: 'god, my balls', body: 'penis' },
      ],
      5: [
        { text: 'my monster cock', ex: 'give me my monster cock', body: 'penis' },
        { text: 'my tight throat', ex: 'god, my tight throat' },
        { text: 'my dripping cock', ex: 'all night, my dripping cock', body: 'penis' },
        { text: 'my leaking cock', ex: 'right there, my leaking cock', body: 'penis' },
        { text: 'my angry cock', ex: "that's it, my angry cock", body: 'penis' },
        { text: 'my heavy balls', ex: 'give me my heavy balls', body: 'penis' },
        { text: 'my full balls', ex: "I can't stop looking at my full balls", body: 'penis' },
        { text: 'my swollen balls', ex: 'all night, my swollen balls', body: 'penis' },
        { text: 'my dripping pussy', ex: 'look at you, my dripping pussy', body: 'vulva' },
        { text: 'my soaked pussy', ex: "that's it, my soaked pussy", body: 'vulva' },
        { text: 'my fat pussy', ex: "that's it, my fat pussy", body: 'vulva' },
        { text: 'my puffy pussy', ex: 'god, my puffy pussy', body: 'vulva' },
        { text: 'my swollen pussy', ex: 'come here, my swollen pussy', body: 'vulva' },
        {
          text: 'my throbbing pussy',
          ex: "I can't stop looking at my throbbing pussy",
          body: 'vulva',
        },
        { text: 'my clenching pussy', ex: 'all night, my clenching pussy', body: 'vulva' },
        { text: 'my cunt', ex: "that's it, my cunt", body: 'vulva' },
        { text: 'my tight cunt', ex: 'god, my tight cunt', body: 'vulva' },
        { text: 'my wet cunt', ex: 'come here, my wet cunt', body: 'vulva' },
        { text: 'my slick cunt', ex: 'give me my slick cunt', body: 'vulva' },
        { text: 'my dripping cunt', ex: "I can't stop looking at my dripping cunt", body: 'vulva' },
        { text: 'my perfect cunt', ex: 'all night, my perfect cunt', body: 'vulva' },
        { text: 'my sweet cunt', ex: 'right there, my sweet cunt', body: 'vulva' },
        { text: 'my hot cunt', ex: "you're my hot cunt", body: 'vulva' },
        { text: 'my wet little cunt', ex: "that's my wet little cunt", body: 'vulva' },
        { text: 'my swollen clit', ex: 'there it is — my swollen clit', body: 'vulva' },
        { text: 'my hard clit', ex: 'look at you, my hard clit', body: 'vulva' },
        { text: 'my needy clit', ex: "that's it, my needy clit", body: 'vulva' },
        { text: 'my tight hole', ex: 'god, my tight hole' },
        { text: 'my wet hole', ex: 'come here, my wet hole' },
        { text: 'my sweet hole', ex: 'give me my sweet hole' },
        { text: 'my little hole', ex: "I can't stop looking at my little hole" },
        { text: 'my dripping girl', ex: 'give me my dripping girl', addresses: 'girl' },
        { text: 'my soaked girl', ex: 'all night, my soaked girl', addresses: 'girl' },
        { text: 'my slick girl', ex: 'right there, my slick girl', addresses: 'girl' },
        { text: 'my messy girl', ex: "you're my messy girl", addresses: 'girl' },
        { text: 'my dripping thing', ex: "that's my dripping thing" },
        { text: 'my stretched girl', ex: 'look at you, my stretched girl', addresses: 'girl' },
        { text: 'my filled girl', ex: "that's it, my filled girl", addresses: 'girl' },
        { text: 'my leaking boy', ex: "I can't stop looking at my leaking boy", addresses: 'man' },
        { text: 'my dripping boy', ex: 'all night, my dripping boy', addresses: 'man' },
      ],
    },
  ),
]);
