import { bankFamily, buildBank, type Bank, type BankFamily } from '../bank';

/**
 * 74-adaptive-tests §13 — the **Dirty Talk bank**: ~1,100 words and phrases across 36 families, tier 1 (tame)
 * → 5 (extreme). This is the deterministic, free, instant half of the test; the adaptive half probes what it
 * leaves ambiguous.
 *
 * **Boundary (absolute, and the only thing standing in front of any of it):** consensual adults; taboo
 * material strictly as **pre-agreed, safeworded roleplay** between adults who both know that is what it is —
 * which is where the ravishment/CNC register lives (`taboo`), worded as roleplay; never minors, never real
 * non-consent, never illegal acts. Carried by the content + the model, never a keyword filter (the
 * `@selfos/core/intimacy/topics` rule).
 *
 * Every family is rated in BOTH directions. What you love to HEAR and what you can get out of your own mouth
 * diverge wildly, and that gap is the single most useful thing this test finds (74 §3.2) — a `say` rating well
 * under its `hear` rating is what produces the `wantsToSay` goal list the practice session runs on.
 *
 * Anatomy is carried by the ENTRIES rather than resolved per person: the bank ships both forms ("stretch my
 * pussy" and "stretch my ass", giving and receiving) and everyone sees both, marking what applies. Per-person
 * resolution the way 46's `activityRows` does it for the onboarding matrix is a later refinement — stated here
 * rather than claimed, because an unverified claim in a comment is worse than none (CLAUDE.md §12).
 */

const word = (id: string, label: string, note?: string): BankFamily => ({
  id,
  label,
  kind: 'word',
  directions: ['hear', 'say'],
  ...(note ? { note } : {}),
});
const phrase = (id: string, label: string, note?: string): BankFamily => ({
  id,
  label,
  kind: 'phrase',
  directions: ['hear', 'say'],
  ...(note ? { note } : {}),
});

export const DIRTY_TALK_BANK: Bank = buildBank([
  bankFamily(
    { ...word('anatomy-her', 'Anatomy — her body'), addresses: 'girl' },
    {
      1: [
        { text: 'down there', ex: 'I want my mouth down there' },
        { text: 'between your legs', ex: 'let me get between your legs' },
        { text: 'your body', ex: "I can't keep my hands off your body" },
        { text: 'your chest', ex: 'your chest looks incredible in that' },
        { text: 'your curves', ex: 'I love every one of your curves' },
        { text: 'your waist', ex: 'hands on your waist, pulling you back' },
        { text: 'your hips', ex: 'I want to grab your hips and pull' },
      ],
      2: [
        { text: 'pussy', ex: 'your pussy is so wet for me', body: 'vulva' },
        { text: 'tits', ex: 'your tits look incredible right now' },
        { text: 'ass', ex: 'that ass was made for this' },
        { text: 'nipples', ex: 'your nipples are so hard' },
        { text: 'clit', ex: "I'm going to work your clit until you shake", body: 'vulva' },
        { text: 'thighs', ex: 'I want to bite your thighs' },
        { text: 'mouth', ex: 'open that mouth for me' },
        { text: 'throat', ex: 'I want the back of your throat' },
        { text: 'breasts', ex: 'your breasts are perfect' },
        { text: 'bum', ex: 'hands on your bum, pulling you closer' },
        { text: 'lips', ex: 'I want those lips everywhere' },
        { text: 'collarbone', ex: 'kissing all the way down your collarbone' },
      ],
      3: [
        { text: 'cunt', ex: 'your cunt is dripping for me', body: 'vulva' },
        { text: 'asshole', ex: 'I want to feel your asshole tighten' },
        {
          text: 'hole',
          ex: "that's all you are tonight \u2014 a hole for me to use",
          body: 'vulva',
          addresses: 'either',
        },
        { text: 'that ass', ex: 'bend over, I want that ass' },
        { text: 'those tits', ex: 'I want to come all over those tits' },
        { text: 'your slit', ex: 'running the tip up your slit', body: 'vulva' },
        { text: 'your opening', ex: 'just teasing your opening until you beg', body: 'vulva' },
        {
          text: 'your cunt lips',
          ex: 'spreading your cunt lips open with my fingers',
          body: 'vulva',
        },
        { text: 'your tight cunt', ex: 'your tight cunt is barely taking me', body: 'vulva' },
        { text: 'your little cunt', ex: 'this little cunt was made for my cock', body: 'vulva' },
        { text: 'your holes', ex: 'I want to use all your holes tonight', body: 'vulva' },
      ],
      4: [
        { text: 'your tight little ass', ex: "I'm going to stretch your tight little ass" },
        {
          text: 'that greedy cunt',
          ex: 'that greedy cunt is still asking for more',
          body: 'vulva',
        },
        { text: 'your slick cunt', ex: "you're so wet I can hear your slick cunt", body: 'vulva' },
        { text: 'your fuckhole', ex: "you're just my fuckhole tonight", body: 'vulva' },
        {
          text: 'your dripping hole',
          ex: 'look at your dripping hole, begging for it',
          body: 'vulva',
        },
        { text: 'your puffy lips', ex: 'your puffy lips are so swollen already', body: 'vulva' },
        {
          text: 'your swollen clit',
          ex: "I'm not stopping until your swollen clit gives out",
          body: 'vulva',
        },
        {
          text: 'that soaking cunt',
          ex: 'that soaking cunt is making a mess of me',
          body: 'vulva',
        },
        { text: 'your perfect tits', ex: 'your perfect tits bouncing while I fuck you' },
        { text: 'those hard nipples', ex: "I'm going to bite those hard nipples" },
        {
          text: 'your tight little hole',
          ex: 'your tight little hole is barely stretching around me',
          body: 'vulva',
        },
        { text: 'that fat ass', ex: 'that fat ass looks incredible taking it' },
      ],
      5: [
        { text: 'your used cunt', ex: 'look at your used cunt, dripping with me', body: 'vulva' },
        { text: 'your gaping hole', ex: "your gaping hole hasn't closed yet", body: 'vulva' },
        {
          text: 'your used little hole',
          ex: 'your used little hole is still twitching',
          body: 'vulva',
        },
        { text: 'your ruined cunt', ex: 'nobody else is touching that ruined cunt', body: 'vulva' },
        { text: 'all your holes', ex: "I'm going to fill all your holes tonight", body: 'vulva' },
      ],
    },
  ),
  bankFamily(
    { ...word('anatomy-him', 'Anatomy — his body'), addresses: 'man' },
    {
      1: [
        { text: 'your body', ex: "I can't keep my hands off your body" },
        { text: 'down there', ex: 'I want my mouth down there' },
        { text: 'your hands', ex: 'I love what your hands do to me' },
        { text: 'your arms', ex: 'I could stay in your arms all night' },
        { text: 'your chest', ex: 'your chest looks incredible in that' },
        { text: 'your thighs', ex: 'I want my hands all over your thighs' },
      ],
      2: [
        { text: 'cock', ex: 'I want your cock right now', body: 'penis' },
        { text: 'dick', ex: 'your dick feels so good', body: 'penis' },
        { text: 'balls', ex: 'I want to feel your balls against me', body: 'penis' },
        { text: 'your mouth', ex: 'I want your mouth on me' },
        { text: 'your fingers', ex: 'your fingers are exactly where I need them' },
        { text: 'your tongue', ex: 'I want your tongue on my clit' },
      ],
      3: [
        { text: 'that cock', ex: "I've been thinking about that cock all day", body: 'penis' },
        {
          text: 'your hard cock',
          ex: 'I can feel your hard cock through your jeans',
          body: 'penis',
        },
        { text: 'your load', ex: 'I want your load in me', body: 'penis' },
        { text: 'precum', ex: "you're already leaking precum for me", body: 'penis' },
        { text: 'your shaft', ex: 'running my tongue up your shaft', body: 'penis' },
        { text: 'your tip', ex: 'just the tip, teasing me open', body: 'penis' },
        { text: 'your cum', ex: 'I want your cum in my mouth', body: 'penis' },
        { text: 'your thick cock', ex: 'your thick cock is stretching me open', body: 'penis' },
        { text: 'your tip leaking', ex: 'your tip leaking all over my stomach', body: 'penis' },
        { text: 'your big dick', ex: 'your big dick is too much for me', body: 'penis' },
      ],
      4: [
        { text: 'fat cock', ex: 'that fat cock barely fits', body: 'penis' },
        { text: 'thick cock', ex: 'your thick cock is splitting me open', body: 'penis' },
        { text: 'every inch', ex: 'I want every inch of you', body: 'penis' },
        { text: 'that big fucking cock', ex: 'give me that big fucking cock', body: 'penis' },
        { text: 'your heavy balls', ex: 'your heavy balls slapping against me', body: 'penis' },
        { text: 'your veiny cock', ex: 'I love the look of your veiny cock', body: 'penis' },
        {
          text: 'your cock stretching me',
          ex: 'I can feel your cock stretching me open',
          body: 'penis',
        },
        {
          text: 'that huge fucking dick',
          ex: 'that huge fucking dick is going to ruin me',
          body: 'penis',
        },
      ],
      5: [
        { text: 'that cock that ruins me', ex: 'give me that cock that ruins me', body: 'penis' },
        { text: 'that cock owns me', ex: 'that cock owns me and you know it', body: 'penis' },
        { text: 'that monster', ex: "I don't know how I'm taking that monster", body: 'penis' },
      ],
    },
  ),
  bankFamily(word('sensation', 'State & sensation'), {
    1: [
      { text: 'warm', ex: "you're so warm against me" },
      { text: 'close', ex: "I'm so close already" },
      { text: 'breathless', ex: "you've got me breathless" },
      { text: 'shaking', ex: "I'm shaking and you've barely started" },
      { text: 'trembling', ex: "you're trembling under my hands" },
      { text: 'tingling', ex: "everything's tingling where you touched me" },
    ],
    2: [
      { text: 'wet', ex: "you're already so wet", body: 'vulva' },
      { text: 'hard', ex: "you're so hard for me", body: 'penis' },
      { text: 'aching', ex: "I'm aching for you" },
      { text: 'sensitive', ex: "go slow, I'm so sensitive" },
      { text: 'tight', ex: "you're so tight around me", body: 'vulva' },
      { text: 'needy', ex: 'look how needy you are' },
      { text: 'desperate', ex: "you're getting desperate, aren't you" },
      { text: 'swollen', ex: "you're so swollen already" },
      { text: 'tender', ex: 'everything feels tender now' },
      { text: 'buzzing', ex: "my whole body's still buzzing" },
    ],
    3: [
      { text: 'soaked', ex: "you've got me completely soaked", body: 'vulva' },
      { text: 'dripping', ex: "you're dripping down my hand", body: 'vulva' },
      { text: 'throbbing', ex: 'I can feel you throbbing inside me' },
      { text: 'clenching', ex: "you're clenching around me already", body: 'vulva' },
      { text: 'twitching', ex: "you're still twitching" },
      { text: 'pulsing', ex: 'I can feel you pulsing' },
      { text: 'slick', ex: "you're so slick I slide right in", body: 'vulva' },
      { text: 'quivering', ex: 'your thighs are quivering' },
      { text: 'slippery', ex: "god, you're slippery", body: 'vulva' },
      { text: 'rock hard', ex: "you're rock hard already", body: 'penis' },
      { text: 'leaking', ex: "you're leaking all over me", body: 'penis' },
      {
        text: 'dripping wet',
        ex: "you're dripping wet and I've barely touched you",
        body: 'vulva',
      },
      { text: 'so hard it hurts', ex: "I'm so hard it hurts", body: 'penis' },
      { text: 'soaking through', ex: "you're soaking through your underwear", body: 'vulva' },
      { text: 'sopping', ex: "you're sopping wet", body: 'vulva' },
    ],
    4: [
      { text: 'gushing', ex: "you're gushing all over me", body: 'vulva' },
      { text: 'stretched', ex: "I'm so stretched around you" },
      { text: 'full', ex: "I'm so full of you" },
      { text: 'sloppy', ex: "it's getting so sloppy" },
      { text: 'raw', ex: 'I feel raw in the best way' },
      { text: 'sore', ex: "I'm going to be sore tomorrow" },
      { text: 'ruined', ex: "you've ruined me" },
      { text: 'overflowing', ex: "I'm overflowing with you" },
      { text: 'creaming', ex: "you're creaming all over my cock", body: 'vulva' },
      { text: 'dripping down my thighs', ex: "it's dripping down my thighs" },
      { text: "so full I can't breathe", ex: "I'm so full I can't breathe" },
      { text: 'stuffed', ex: "I'm completely stuffed" },
      { text: 'split open', ex: "you're splitting me open" },
      { text: 'drenched', ex: "I'm absolutely drenched", body: 'vulva' },
      { text: 'stretched open', ex: "you've got me stretched open" },
      { text: 'pounded', ex: 'I want to be pounded' },
    ],
    5: [
      { text: 'wrecked', ex: 'wreck me' },
      { text: 'destroyed', ex: "you've destroyed me" },
      { text: 'used up', ex: 'I feel used up in the best way' },
      { text: 'fucked out', ex: "I'm completely fucked out" },
      { text: 'gaping', ex: "I'm still gaping" },
      { text: 'numb', ex: 'my legs have gone numb' },
      { text: 'spent', ex: "I'm completely spent" },
      { text: 'fucked stupid', ex: "you've fucked me stupid" },
    ],
  }),
  bankFamily(word('names-affectionate', 'Names — affectionate'), {
    1: [
      { text: 'baby', ex: 'come here, baby' },
      { text: 'babe', ex: 'you feel so good, babe' },
      { text: 'beautiful', ex: 'look at me, beautiful' },
      { text: 'gorgeous', ex: "you're gorgeous like this" },
      { text: 'sweetheart', ex: "that's it, sweetheart" },
      { text: 'honey', ex: 'come here, honey' },
      { text: 'love', ex: "I've got you, love" },
      { text: 'my love', ex: "you're my love, always" },
      { text: 'angel', ex: "that's my angel" },
      { text: 'darling', ex: 'open up for me, darling' },
      { text: 'my girl', ex: "that's my girl", addresses: 'girl' },
      { text: 'my everything', ex: "you're my everything" },
    ],
    2: [
      { text: 'pretty girl', ex: 'look at you, pretty girl', addresses: 'girl' },
      { text: 'handsome', ex: 'you look so handsome like that', addresses: 'man' },
      { text: 'my boy', ex: "that's my boy", addresses: 'man' },
      { text: 'sweet thing', ex: 'come here, sweet thing' },
      { text: 'beautiful girl', ex: "you're such a beautiful girl", addresses: 'girl' },
      { text: 'gorgeous girl', ex: "that's it, gorgeous girl", addresses: 'girl' },
    ],
  }),
  bankFamily(word('names-power', 'Names — power & role'), {
    2: [
      { text: 'good girl', ex: "that's it \u2014 such a good girl for me", addresses: 'girl' },
      { text: 'good boy', ex: "that's my good boy", addresses: 'man' },
      { text: 'little one', ex: 'come here, little one' },
    ],
    3: [
      { text: 'sir', ex: 'yes, sir', addresses: 'man' },
      { text: "ma'am", ex: "yes, ma'am", addresses: 'girl' },
      { text: 'mistress', ex: 'please, mistress', addresses: 'girl' },
      { text: 'daddy', ex: "oh daddy, don't stop", addresses: 'man' },
      { text: 'mommy', ex: 'yes, mommy', addresses: 'girl' },
      { text: 'princess', ex: 'on your knees, princess', addresses: 'girl' },
      { text: 'kitten', ex: "that's it, kitten", addresses: 'girl' },
      { text: 'pet', ex: 'good pet' },
      { text: 'babygirl', ex: 'come here, babygirl', addresses: 'girl' },
      { text: 'boy', ex: "you're my boy tonight", addresses: 'man' },
      { text: 'goddess', ex: "you're a goddess", addresses: 'girl' },
      { text: 'queen', ex: 'my queen', addresses: 'girl' },
      { text: 'my king', ex: 'yes, my king', addresses: 'man' },
      { text: 'bunny', ex: 'come here, bunny' },
    ],
    4: [
      { text: 'master', ex: 'yes, master', addresses: 'man' },
      { text: 'owner', ex: "you're my owner" },
      { text: 'my property', ex: "you're my property tonight" },
      { text: 'my toy', ex: "you're just my toy" },
      { text: 'plaything', ex: "you're my plaything" },
      { text: 'doll', ex: "that's it, doll" },
      { text: 'my pet', ex: 'good girl, my pet' },
      { text: 'my good girl', ex: "that's my good girl", addresses: 'girl' },
      { text: 'my little whore', ex: "you're my little whore, aren't you", addresses: 'girl' },
    ],
  }),
  bankFamily(
    { ...word('names-degrading', 'Names — degrading'), addresses: 'girl' },
    {
      3: [
        { text: 'naughty girl', ex: "someone's been a naughty girl tonight" },
        { text: 'dirty girl', ex: "you're such a dirty girl" },
        { text: 'bad girl', ex: "you've been a bad girl" },
        { text: 'filthy little thing', ex: 'you filthy little thing' },
        { text: 'greedy girl', ex: 'greedy girl — you want more already' },
        { text: 'little tease', ex: "you're such a little tease" },
        { text: 'cocktease', ex: "you're a fucking cocktease" },
      ],
      4: [
        { text: 'slut', ex: "that's my slut" },
        { text: 'my slut', ex: "you're my slut and you love it" },
        { text: 'little slut', ex: 'such a good little slut' },
        { text: 'whore', ex: 'you filthy little whore' },
        { text: 'bitch', ex: 'take it, bitch' },
        {
          text: 'brat',
          ex: "you're being such a brat \u2014 want me to do something about it?",
          addresses: 'either',
        },
        { text: 'dirty whore', ex: 'you dirty whore, look at you' },
        { text: 'needy slut', ex: 'you needy slut, begging already' },
        { text: 'cock hungry', ex: "you're so cock hungry tonight" },
        { text: 'filthy slut', ex: "that's it, you filthy slut" },
        { text: 'greedy little slut', ex: 'you greedy little slut, take it all' },
      ],
      5: [
        { text: 'cockslut', ex: "you're my cockslut", addresses: 'either' },
        { text: 'cumslut', ex: 'open — take it, you little cumslut', addresses: 'either' },
        { text: 'cumdump', ex: "you're my cumdump tonight", addresses: 'either' },
        { text: 'fucktoy', ex: "you're just my fucktoy", addresses: 'either' },
        { text: 'fuckdoll', ex: "that's it, my perfect fuckdoll", addresses: 'either' },
        {
          text: 'hole',
          ex: "that's all you are tonight \u2014 a hole for me to use",
          body: 'vulva',
          addresses: 'either',
        },
        { text: 'pathetic little slut', ex: 'look at you, you pathetic little slut' },
        {
          text: 'worthless',
          ex: "say it \u2014 say you're worthless without my cock",
          addresses: 'either',
        },
        { text: 'my filthy whore', ex: 'look at you — my filthy whore, taking every inch' },
        { text: 'dumb slut', ex: "you're such a dumb slut for me" },
        { text: 'desperate little whore', ex: 'you desperate little whore, beg for it' },
        { text: 'breeding slut', ex: "you're my breeding slut tonight" },
        { text: 'anal slut', ex: "you're my anal slut now", addresses: 'either' },
        { text: 'my cumrag', ex: "you're my cumrag", addresses: 'either' },
        {
          text: 'pathetic whore',
          ex: 'you pathetic whore, look at the mess you made',
          addresses: 'either',
        },
        {
          text: 'good little fuckhole',
          ex: "that's it \u2014 my good little fuckhole",
          addresses: 'either',
        },
      ],
    },
  ),
  bankFamily(phrase('claiming', 'Claiming & possession'), {
    2: [
      'mine',
      "you're mine",
      { text: 'my girl', ex: "that's my girl", addresses: 'girl' },
      { text: 'my boy', ex: "that's my boy", addresses: 'man' },
      'all mine',
    ],
    3: [
      'you belong to me',
      'nobody else gets this',
      "say you're mine",
      'who do you belong to',
      'say it',
      "you're mine tonight",
      'own me',
    ],
    4: [
      'I own this pussy',
      'this cunt is mine',
      'mine to use',
      "you're my property",
      'every hole is mine',
      'say my name when you come',
      'this ass is mine',
      'nobody else touches this',
      'this mouth is mine',
      'own me completely',
      'claim me',
      'make me yours',
    ],
    5: [
      "you don't get to say no to me (roleplay)",
      "I'll do what I like with you (roleplay)",
      "you're mine to ruin",
      'I own every part of you',
    ],
  }),
  bankFamily(
    { ...phrase('praise-her', 'Praise & worship — her'), addresses: 'girl' },
    {
      1: [
        "you're beautiful",
        'you feel amazing',
        'I love how you feel',
        "you're perfect",
        "you're amazing",
      ],
      2: [
        'good girl',
        "that's it",
        'just like that',
        "you're doing so well",
        'you feel incredible',
        "god you're gorgeous",
        'so good',
      ],
      3: [
        'you take it so well',
        'look how well you’re taking it',
        'you were made for this',
        'I love how you taste',
        "you're so good at that",
        "that's my girl",
        "you're so fucking tight",
        "you're so beautiful when you come",
        'I love watching you',
      ],
      4: [
        'you take my cock so well',
        "that's my good little slut",
        'perfect fucking pussy',
        'you were made to take this',
        'such a good girl for me',
        'god you suck cock so well',
        'your cunt was made for me',
        'your mouth was made for my cock',
        'you take it like a good girl',
        "you're perfect when you beg",
        'that pussy is perfect',
      ],
      5: [
        "best fucking pussy I've ever had",
        'you were built to be fucked',
        'your cunt was built for my cock',
      ],
    },
  ),
  bankFamily(phrase('degradation', 'Degradation & humiliation'), {
    3: [
      "you love this, don't you",
      'look at the state of you',
      "you're such a mess",
      "you can't help yourself",
    ],
    4: [
      'dirty little slut',
      'filthy girl',
      'look how wet you get for me',
      "you're leaking everywhere",
      'beg like the slut you are',
      "you're pathetic when you want it",
      'is that all it takes',
      'look at you drooling for it',
      "you're so easy",
      'look how desperate you are',
    ],
    5: [
      "you're just a hole",
      'you exist for this',
      "you'd take anything, wouldn't you",
      "say you're my whore",
      'thank me for it',
      'look at yourself',
      "you're nothing but a hole to fuck",
      'dumb little slut',
      "you love being used, don't you",
      "you're a mess and you love it",
      'beg properly',
      "you're just something to fuck",
      'say thank you for my cum',
    ],
  }),
  bankFamily(phrase('commands', 'Commands — general'), {
    1: ['come here', 'kiss me', 'closer', 'slower', 'look at me'],
    2: [
      "don't move",
      'stay still',
      'open your mouth',
      'spread your legs',
      'hands above your head',
      'turn around',
      'bend over',
      'on your knees',
      'take it off',
      'touch yourself',
      'get on the bed',
    ],
    3: [
      'open wider',
      'arch your back',
      "don't look away",
      'say my name',
      'take it',
      "don't stop",
      'keep going',
      'be quiet',
      "don't make a sound",
      'let me hear you',
      'show me',
      'touch yourself for me',
      'hold still',
      'put your hands here',
      'spread wider',
      'legs open',
    ],
    4: [
      'crawl',
      'hold your legs open',
      'keep them open',
      'take it all',
      "don't you dare stop",
      'ask me nicely',
      'hands behind your back',
      'eyes on me',
      'spread that ass',
      'hold your ankles',
      'bend over further',
      'keep still while I finish',
      "say you're mine",
      "tell me you're my slut",
    ],
    5: [
      'gag on it',
      'choke on it',
      'hold your breath',
      'count them',
      "don't spill a drop",
      'present yourself',
      'beg for my cock',
      'keep your mouth open',
      'open your throat',
      'take every inch',
    ],
  }),
  bankFamily(phrase('orgasm-control', 'Commands — orgasm control'), {
    2: ['come for me', 'let go', "don't hold back"],
    3: [
      'not yet',
      'hold it',
      "don't come yet",
      'wait',
      'ask me first',
      'come now',
      "that's it, come",
      'slow down',
      'edge for me',
    ],
    4: [
      "don't come until I say",
      "you'll come when I tell you",
      'again',
      'one more',
      'ask permission',
      'you can come now',
      'good girl, come',
      'come on my cock',
      'hold it for me',
      "you're not done",
      'again, right now',
      'squirt for me',
    ],
    5: [
      "you don't get to come tonight (roleplay)",
      "hold it or you'll be punished (roleplay)",
      "you'll come when I'm done with you",
      "you'll come until I say stop",
      'come until it hurts',
    ],
  }),
  bankFamily(phrase('demands-receiving', 'Demands — the receiving voice'), {
    1: ['touch me', 'kiss me', 'closer', "don't stop", 'keep going'],
    2: [
      'fuck me',
      'harder',
      'deeper',
      'slower',
      'right there',
      'just like that',
      'I want you inside me',
      'I need you',
      'more',
      'kiss me there',
      'taste me',
    ],
    3: [
      'fuck me harder',
      'pound me',
      'pound my pussy',
      'fuck me from behind',
      'ride me',
      'suck my clit',
      'lick my pussy',
      'eat me',
      'finger me',
      'use your mouth',
      'put it in',
      'give it to me',
      "don't be gentle",
      'get in me',
      'rub my clit',
      'fuck me slow',
      'grind on me',
      'go deeper',
      'hit that spot',
      'I want your cock in me',
      'shove it in',
      'fill me',
    ],
    4: [
      'fuck me in the ass',
      'finger my asshole',
      'choke me',
      'stretch my pussy',
      'stretch my ass',
      'fill my mouth',
      'slap my pussy',
      'beat my pussy',
      'put it in my ass',
      'cum in me',
      'cum on me',
      'cum in my pussy',
      'cum in my mouth',
      'fill all my holes',
      'I wanna choke on your dick',
      'pull my hair',
      'spank me',
      'slap my tits',
      'hold me down',
      'spit in my mouth',
      'come on my face',
      'come on my tits',
      'use me',
      'make me beg',
      'ruin me',
      'breed me',
      'fill me up',
      'grab my throat',
      'fuck my throat',
      'stretch me open',
      'finger me while you fuck me',
      'hold my hips',
      'bend me over',
      'take me from behind',
      'fuck me harder than that',
      'rub my clit while you fuck me',
      'fuck me raw',
      'pin me down',
      'make me scream',
      'I want it rough',
      'hold my legs back',
      'put it back in',
    ],
    5: [
      'wreck my pussy',
      'choke me harder',
      'treat me like your whore',
      'use every hole',
      'make me take it',
      "fuck me till I can't walk",
      'destroy me',
      'use me like a toy',
      'split me open',
      'I want to feel it tomorrow',
      'fuck me until I cry',
      'use my throat',
      "don't be nice to me",
      'ruin every hole',
      "don't stop even if I say so (pre-agreed CNC, safeworded)",
    ],
  }),
  bankFamily(phrase('demands-giving', 'Demands — the giving voice'), {
    2: [
      'come here',
      'let me taste you',
      'I want to watch',
      'take it off',
      'sit on me',
      'I wanna taste you',
    ],
    3: [
      'suck that cock',
      'suck my cock',
      'lick my balls',
      'lick my ass',
      'get on your knees',
      'ride me',
      'sit on my face',
      'open your mouth',
      'take it',
      'look at me while you take it',
      'say my name',
      'tell me who owns this',
      'spread them',
      'bounce on it',
      'play with yourself for me',
      'put on a show',
      'get it wet',
      'spit on it',
    ],
    4: [
      'swallow it',
      'take it all',
      'deeper',
      'gag on it',
      'beg for it',
      'tell me what you are',
      'hold still while I use you',
      'arch for me',
      'give me that ass',
      'choke on my cock',
      'take my load',
      'open wider',
      'take it deeper',
      'hold it there',
      'look up at me',
      'suck my balls',
      'milk it',
      'take every inch',
      'squirt for me',
      "I'm gonna cum in your pussy",
      "I'm gonna cum in your mouth",
      "say you're my little slut",
    ],
    5: [
      "you'll take what I give you (roleplay)",
      "open up, I'm not done",
      "you'll take it till I'm finished",
      'beg me for my cum',
      'I wanna feel your juices explode around my cock',
    ],
  }),
  bankFamily(phrase('narration', 'Narration & feedback'), {
    1: ['that feels amazing', 'I love this', 'you feel so good'],
    2: [
      "you're so wet",
      "you're so hard",
      "you're so tight",
      "you're so big",
      'god you fill me',
      'I can feel you',
      'you feel incredible',
    ],
    3: [
      'I can feel you throb',
      'I can feel you clenching',
      "you're dripping down my hand",
      'listen to how wet you are',
      'look how hard you make me',
      "I'm going to come",
      "I've been hard all day",
      'I can still taste you',
      "you're shaking",
      "you're squeezing me",
      'I can hear how wet you are',
    ],
    4: [
      'your cunt is soaking',
      'I can feel you tightening around my cock',
      "you're leaking all over me",
      "I'm going to fill you",
      'watch it go in',
      'look at you taking every inch',
      "you're so fucking wet for me",
      'your pussy is gripping me',
      "you're taking it so deep",
      'your ass is so tight',
      'I can feel you stretching around me',
      "you're throbbing on my cock",
    ],
    5: [
      'listen to that',
      "you're making such a mess",
      'I can feel your cunt begging for it',
      "you're gushing",
      'look how well that little cunt takes it',
    ],
  }),
  bankFamily(phrase('begging', 'Begging & permission'), {
    2: ['please', 'I need it', "please don't stop", 'I want it'],
    3: [
      'please fuck me',
      'can I come',
      'may I come',
      'please let me',
      'I need you inside me',
      "I'm so close",
      'please, more',
      'please give it to me',
    ],
    4: [
      'please sir',
      'please daddy',
      'please let me come',
      "I'll be good",
      "I'll do anything",
      'please use me',
      'may I touch myself',
      'please fill me',
      'I need to come',
      'please cum in me',
    ],
    5: [
      'thank you',
      'thank you for letting me',
      'thank you for using me',
      "please, I'll be your good little slut",
      "I'm begging you",
      'please, I need your cum',
    ],
  }),
  bankFamily(phrase('sexting', 'Sexting & anticipation'), {
    1: ['thinking about you', "can't wait to see you", 'I miss you'],
    2: [
      "I've been thinking about last night",
      'what are you wearing',
      'I want you tonight',
      'come home',
      'are you alone',
    ],
    3: [
      "I'm so hard thinking about you",
      "I'm wet just typing this",
      "tell me what you'd do to me",
      'send me one',
      "I've been thinking about your mouth all day",
      "I'm touching myself",
      'describe it',
    ],
    4: [
      "I've been thinking about your cunt all day",
      "I'm going to ruin you tonight",
      'I want you on your knees when I get home',
      "I'm fucking you the second you walk in",
      "don't touch yourself until I'm home",
      'I want you dripping before I get there',
      "I'm going to fill you tonight",
      "I want your cock the second you're home",
    ],
    5: [
      "I'm going to use every hole tonight",
      "you'd better be ready for me",
      "I'm going to fuck you until you can't stand",
    ],
  }),
  bankFamily(phrase('aftercare', 'Aftercare & tenderness'), {
    1: [
      'come here',
      "I've got you",
      'that was perfect',
      'you did so well',
      'I love you',
      'stay right there',
      "you're incredible",
      'thank you',
    ],
    2: [
      'good girl',
      'you were so good',
      'are you okay',
      'let me hold you',
      "I'm proud of you",
      "you're safe",
      'you took that so well',
      'let me clean you up',
    ],
  }),
  bankFamily(
    phrase(
      'taboo',
      'Taboo fantasy & roleplay',
      'Every entry here is PRE-AGREED, SAFEWORDED ROLEPLAY between consenting adults, and is labelled as roleplay wherever it appears. Nothing here is about minors, real non-consent, or anything illegal.',
    ),
    {
      5: [
        'take it, you don’t get a choice (CNC roleplay)',
        "I'm not asking (CNC roleplay)",
        'fight me (CNC roleplay)',
        'stop struggling (CNC roleplay)',
        'rape me (CNC roleplay)',
        "I'm going to rape you (CNC roleplay)",
        "I'm going to take what I want (CNC roleplay)",
        "you're not getting away (CNC roleplay)",
        "you don't even know my name (stranger roleplay)",
        'boss / employee roleplay',
        'teacher / student roleplay (adults)',
        'doctor / patient roleplay',
        "does he know you're here (cheating roleplay)",
        "we shouldn't be doing this (cheating roleplay)",
        'tell me what he did to you (cuckold / hotwife)',
        'did you let him finish (cuckold / hotwife)',
        'did he fill you (cuckold / hotwife)',
        "I'm going to breed you (breeding)",
        "you're taking every drop (breeding)",
        "I'm putting a baby in you (breeding)",
        'run (primal)',
        "I'll catch you (primal)",
        'found you (primal)',
        'age-gap roleplay (adults)',
        "you're furniture tonight (objectification roleplay)",
        "you're just a hole to use (objectification roleplay)",
        "you shouldn't be here (caught-in-the-act roleplay)",
        'sex-worker roleplay',
        'being shared (fantasy roleplay)',
      ],
    },
  ),
  bankFamily(
    phrase(
      'delivery',
      'Delivery & voice',
      'Not words — how they are said. Half of what lands is not the word.',
    ),
    {
      1: ['whispered', 'in my ear', 'low and slow', 'breathless', 'saying my name'],
      2: ['commanding', 'growled', 'moaning', 'filthy but smiling', 'laughing'],
      3: [
        'loud',
        'silent, just sounds',
        'narrating the whole time',
        'a single word at the right moment',
        'right against my ear',
        'telling me what you’re about to do before you do it',
        'through gritted teeth',
        'begging under your breath',
      ],
      4: ["loud enough that they'd hear"],
    },
  ),
  bankFamily(phrase('oral', 'Oral'), {
    2: ['suck me', 'lick me', 'use your mouth', 'taste me', 'kiss me there', 'kiss it'],
    3: [
      'eat my pussy',
      'suck my cock',
      'lick my clit',
      'suck it',
      'put it in your mouth',
      'sit on my face',
      'lick me clean',
      'get it wet',
      'lick it slowly',
      'swallow me',
      'lick my balls',
      'suck my balls',
      'lick my ass',
      'tongue me',
      'suck it harder',
      'lick my clit faster',
    ],
    4: [
      'deepthroat it',
      'gag on it',
      'choke on my cock',
      'take it all the way',
      'fuck my face',
      'face-fuck me',
      'swallow it',
      "don't spill it",
      'look at me while you suck it',
      'worship it',
      "don't stop until I come in your mouth",
      'hold it in your mouth',
      'fill my mouth',
      'cum in my mouth',
      'rim me',
      'tongue my ass',
      'spit on it',
      'use your throat',
    ],
    5: ['use my throat', 'make me gag', 'leave me drooling', 'fuck my mouth like a pussy'],
  }),
  bankFamily(phrase('anal', 'Anal'), {
    2: ['touch me there', 'play with my ass'],
    3: [
      'finger my ass',
      'finger my asshole',
      'lick my ass',
      'rim me',
      'put a finger in',
      'slowly',
      'work it in',
      'spread my ass',
    ],
    4: [
      'fuck my ass',
      'put it in my ass',
      'stretch my ass',
      'take my ass',
      'in my ass',
      'plug me',
      'pound my ass',
      'all the way',
      'take it deeper',
      'cum in my ass',
      'finger my ass while you fuck me',
      'spit on my ass',
      'fuck my ass raw',
    ],
    5: [
      'ruin my ass',
      'both holes',
      'use my ass like a pussy',
      'fill all my holes',
      'destroy my ass',
    ],
  }),
  bankFamily(phrase('cum', 'Cum & finishing'), {
    2: ['come for me', "I'm close", "I'm going to come"],
    3: [
      'cum in me',
      'cum on me',
      'come with me',
      'I want to feel you come',
      'make me come',
      'finish in me',
      'inside me',
      'where do you want it',
    ],
    4: [
      'cum in my pussy',
      'cum in my mouth',
      'cum in my ass',
      'fill me up',
      'come on my face',
      'come on my tits',
      'come on my ass',
      'come on my back',
      'swallow it',
      'come all over me',
      'breed me',
      'paint me',
      'give me your load',
      "don't pull out",
      'in my throat',
      'let me taste it',
      "don't waste a drop",
      'give me every drop',
    ],
    5: [
      'make a mess of me',
      'I want to be dripping with it',
      'put it back in after',
      'fill both',
      'I want it leaking out of me',
      'fill all my holes',
    ],
  }),
  bankFamily(phrase('impact', 'Impact, restraint & pain'), {
    2: ['harder', 'pull my hair', 'hold me down'],
    3: [
      'spank me',
      'slap my ass',
      'grab my throat',
      'pin me',
      'bite me',
      'scratch me',
      'squeeze',
      'harder than that',
      'again',
      'spank me daddy',
    ],
    4: [
      'choke me',
      'slap my pussy',
      'beat my pussy',
      'slap my tits',
      'slap my face',
      'mark me',
      'leave a bruise',
      'tie me up',
      'hold my wrists',
      'harder, I can take it',
      'hold me down while you do it',
      'choke me while you fuck me',
      'spank me while I ride you',
    ],
    5: [
      'choke me harder',
      'hurt me a little',
      'make it sting',
      "don't be careful with me",
      "leave marks I'll see tomorrow",
    ],
  }),
  bankFamily(phrase('watched', 'Being watched / shared'), {
    3: [
      'I want to watch you',
      'watch me',
      'look at us',
      'imagine someone seeing this',
      'tell me a fantasy',
    ],
    4: [
      'would you let them watch',
      'tell me what he did',
      'I want to watch someone else make you come (fantasy)',
      'what if someone walked in',
    ],
    5: [
      'tell me how he fucked you (roleplay)',
      'I want to see you take someone else (roleplay)',
      'did you let him cum in you (roleplay)',
    ],
  }),
  bankFamily(
    { ...phrase('praise-him', 'Praise & worship — him'), addresses: 'man' },
    {
      1: ['you feel so good', 'I love your hands', 'I love your mouth'],
      2: ["you're so hard for me", 'you feel huge', 'I love your cock', "you're so good at that"],
      3: [
        'you fuck me so well',
        'nobody fills me like you',
        "you're so big",
        'I love how you use me',
        'you know exactly what you’re doing',
        'god, that cock',
        'your dick is huge',
      ],
      4: [
        'your cock ruins me',
        'you fuck me better than anyone',
        'you make me forget my name',
        'you fill me completely',
        'I love how you take what you want',
        'your dick is too big for my little cunt',
        'I love how you use my holes',
      ],
      5: ["I'd let you do anything to me", 'you own this pussy'],
    },
  ),
  bankFamily(phrase('toys', 'Toys & objects'), {
    2: ['use it on me', 'get the toy', 'use your fingers and it'],
    3: [
      'fuck me with it',
      'hold it there',
      'turn it up',
      'put it inside me',
      'use it while you watch',
    ],
    4: [
      'both at once',
      'put the plug in',
      'leave it in',
      'make me come with it while you watch',
      'fuck me with it until I beg',
      'one in each hole',
    ],
    5: ["don't stop till the toy's done with me"],
  }),
  bankFamily(phrase('public-risk', 'Public & risk'), {
    2: ['be quiet', 'someone might hear', 'not here'],
    3: [
      "they'll hear us",
      'right here',
      "don't stop, someone's coming",
      'keep your voice down',
      "quick, before they're back",
    ],
    4: [
      "hold still, don't make a sound",
      'take it right here',
      'nobody knows what you’re doing',
      'under the table',
      'in the car',
    ],
    5: ['let them hear'],
  }),
  bankFamily(phrase('teasing', 'Teasing & denial'), {
    2: ['not yet', "you want it, don't you", 'patience'],
    3: [
      'ask me nicely',
      'say please',
      "you'll get it when I decide",
      'look how badly you want it',
      'almost',
      'I could keep you like this all night',
    ],
    4: [
      'beg me',
      "maybe I'll let you",
      "not until you've earned it",
      "you'll wait",
      'ask again, properly',
      'tell me how badly you want my cock',
    ],
    5: ['I could stop right now', "you'll take what I decide to give you"],
  }),
  bankFamily(
    phrase(
      'consent',
      'Consent & check-ins',
      'The language that makes the rest safe to want. Rated like everything else, because for some people being asked IS part of it and for others it breaks the spell — and partners get that wrong constantly.',
    ),
    {
      1: ['is this okay', 'you okay', 'too much?', 'more?', 'do you like that'],
      2: [
        "tell me if it's too much",
        'you can stop me',
        'colour?',
        'green / amber / red',
        'say the word and I stop',
        'we can stop any time',
      ],
      3: [
        'do you want more',
        'harder?',
        'can I',
        'do you want me to stop',
        'is this still good',
        'tell me what you need',
      ],
      4: ['you did so well, are you alright', 'was that too far', 'come back to me'],
    },
  ),
  bankFamily(phrase('comparisons', 'Comparisons & ego'), {
    2: ['nobody does that like you'],
    3: [
      'nobody fucks me like you',
      "I've never come like that",
      "you're the best I've had",
      "no one's ever made me feel like this",
    ],
    4: [
      'you ruined me for anyone else',
      "I don't want anyone else",
      "I've never done that with anyone else",
      "you're the biggest I've had",
      "nobody's ever filled me like this",
    ],
  }),
  bankFamily(phrase('morning-after', 'The morning after / next day'), {
    1: ["I'm still thinking about last night", 'last night was incredible'],
    2: ["I'm still sore", 'I can still feel you', 'I woke up wanting you', "I didn't sleep"],
    3: [
      "I'm sore in the best way",
      'I could still taste you this morning',
      "I've been thinking about it all morning",
    ],
    4: [
      'I want it again before work',
      "I'm still dripping from last night",
      'I can still feel where you were',
      "I'm still leaking you",
    ],
  }),
  bankFamily(phrase('size-fit', 'Size & fit'), {
    2: ["you're big", 'you feel huge', "it's a lot"],
    3: [
      'your dick is huge',
      "you're so big",
      'I can feel every inch',
      "you're stretching me",
      'it barely fits',
      "go slow, you're big",
    ],
    4: [
      'your dick is too big for my little cunt',
      "you're splitting me open",
      "I can't take it all",
      'take it all anyway',
      'make it fit',
      "you're too big for my ass",
      'stretch me around it',
    ],
    5: ['ruin me with it', "I don't care if it doesn't fit"],
  }),
  bankFamily(phrase('squirt', 'Squirting, wetness & mess'), {
    2: ["I'm so wet", 'look how wet I am'],
    3: [
      'I wanna squirt all over you',
      'make me squirt',
      "I'm going to squirt",
      "I'm soaking",
      "you're making me drip",
    ],
    4: [
      'squirt for me',
      'soak me',
      'look what you did to me',
      "I'm soaking the sheets",
      'you made a mess of me',
      "I'm dripping down my legs",
    ],
    5: ['I want to ruin the bed', "make me squirt until I can't take it"],
  }),
  bankFamily(phrase('taste', 'Taste & fluids'), {
    1: ['kiss me'],
    2: ['taste me', 'I wanna taste you', 'let me taste'],
    3: [
      'lick it off',
      'lick my fingers',
      'taste yourself on me',
      'I love how you taste',
      'get it on your tongue',
    ],
    4: [
      'spit it in my mouth',
      'share it',
      'kiss me after',
      'lick it off my tits',
      "don't swallow yet",
    ],
    5: ['let me lick you clean'],
  }),
  bankFamily(
    phrase(
      'role-lines',
      'Role-name lines',
      'The name inside a whole sentence, which is what people actually say.',
    ),
    {
      2: ['yes sir', "yes ma'am"],
      3: [
        'oh daddy',
        'yes daddy',
        'please daddy',
        'thank you daddy',
        'yes mistress',
        'please sir',
        'thank you sir',
      ],
      4: [
        'spank me daddy',
        'fuck me daddy',
        'harder daddy',
        'deeper daddy',
        "I'm your good girl daddy",
        'cum in me daddy',
        "yes daddy, I'm yours",
      ],
      5: ['use me daddy', "I'll be good for you daddy"],
    },
  ),
  bankFamily(
    phrase(
      'self-labelling',
      'Self-labelling',
      'Claiming it about yourself is a different act from being called it, and usually a bigger step — scoring them together would hide exactly that.',
    ),
    {
      2: ["I'm yours", "I'm all yours"],
      3: [
        "I'm your little slut",
        "I'm your slut",
        "I'm your good girl",
        'I belong to you',
        "I'm your dirty girl",
      ],
      4: [
        "I'm your whore",
        "I'm your fucktoy",
        "I'm your cumslut",
        "use me, I'm yours",
        "I'm your hole",
        'I exist for your cock',
      ],
      5: ["I'm nothing but your fucktoy", "I'm your worthless little slut"],
    },
  ),
]);
