import { bankFamily, buildBank, type Bank, type BankFamily } from '../bank';

/**
 * 74-adaptive-tests §13 — the **Dirty Talk bank**: ~1,100 words and phrases across 36 families, tier 1 (tame)
 * → 5 (extreme). This is the deterministic, free, instant half of the test; the adaptive half probes what it
 * leaves ambiguous.
 *
 * **Boundary (absolute, and the only thing standing in front of any of it):** consensual adults; taboo
 * material strictly as **pre-agreed, safeworded roleplay** between adults who both know that is what it is —
 * which is where the ravishment/CNC register lives (`taboo`), worded as roleplay; never minors, never real
 * non-consent, never illegal acts. Carried by the content + the model, never a keyword filter (the
 * `@selfos/core/intimacy/topics` rule).
 *
 * Every family is rated in BOTH directions. What you love to HEAR and what you can get out of your own mouth
 * diverge wildly, and that gap is the single most useful thing this test finds (74 §3.2) — a `say` rating well
 * under its `hear` rating is what produces the `wantsToSay` goal list the practice session runs on.
 *
 * Anatomy inside a phrase is resolved per person at render time from the intake answers (46 `activityRows`),
 * so "stretch my pussy" / "stretch my ass" / a neutral form appear as appropriate.
 */

const word = (id: string, label: string, note?: string): BankFamily => ({
  id,
  label,
  kind: 'word',
  directions: ['hear', 'say'],
  ...(note ? { note } : {}),
});
const phrase = (id: string, label: string, note?: string): BankFamily => ({
  id,
  label,
  kind: 'phrase',
  directions: ['hear', 'say'],
  ...(note ? { note } : {}),
});

export const DIRTY_TALK_BANK: Bank = buildBank([
  bankFamily(word('anatomy-her', 'Anatomy — her body'), {
    1: [
      'down there',
      'between your legs',
      'your body',
      'your chest',
      'your curves',
      'your waist',
      'your hips',
    ],
    2: [
      'pussy',
      'tits',
      'ass',
      'nipples',
      'clit',
      'thighs',
      'mouth',
      'throat',
      'breasts',
      'bum',
      'lips',
      'collarbone',
    ],
    3: [
      'cunt',
      'asshole',
      'hole',
      'that ass',
      'those tits',
      'your slit',
      'your opening',
      'your cunt lips',
      'your tight cunt',
      'your little cunt',
      'your holes',
    ],
    4: [
      'your tight little ass',
      'that greedy cunt',
      'your slick cunt',
      'your fuckhole',
      'your dripping hole',
      'your puffy lips',
      'your swollen clit',
      'that soaking cunt',
      'your perfect tits',
      'those hard nipples',
      'your tight little hole',
      'that fat ass',
    ],
    5: [
      'your used cunt',
      'your gaping hole',
      'your used little hole',
      'your ruined cunt',
      'all your holes',
    ],
  }),
  bankFamily(word('anatomy-him', 'Anatomy — his body'), {
    1: ['your body', 'down there', 'your hands', 'your arms', 'your chest', 'your thighs'],
    2: ['cock', 'dick', 'balls', 'your mouth', 'your fingers', 'your tongue'],
    3: [
      'that cock',
      'your hard cock',
      'your load',
      'precum',
      'your shaft',
      'your tip',
      'your cum',
      'your thick cock',
      'your tip leaking',
      'your big dick',
    ],
    4: [
      'fat cock',
      'thick cock',
      'every inch',
      'that big fucking cock',
      'your heavy balls',
      'your veiny cock',
      'your cock stretching me',
      'that huge fucking dick',
    ],
    5: ['that cock that ruins me', 'that cock owns me', 'that monster'],
  }),
  bankFamily(word('sensation', 'State & sensation'), {
    1: ['warm', 'close', 'breathless', 'shaking', 'trembling', 'tingling'],
    2: [
      'wet',
      'hard',
      'aching',
      'sensitive',
      'tight',
      'needy',
      'desperate',
      'swollen',
      'tender',
      'buzzing',
    ],
    3: [
      'soaked',
      'dripping',
      'throbbing',
      'clenching',
      'twitching',
      'pulsing',
      'slick',
      'quivering',
      'slippery',
      'rock hard',
      'leaking',
      'dripping wet',
      'so hard it hurts',
      'soaking through',
      'sopping',
    ],
    4: [
      'gushing',
      'stretched',
      'full',
      'sloppy',
      'raw',
      'sore',
      'ruined',
      'overflowing',
      'creaming',
      'dripping down my thighs',
      "so full I can't breathe",
      'stuffed',
      'split open',
      'drenched',
      'stretched open',
      'pounded',
    ],
    5: [
      'wrecked',
      'destroyed',
      'used up',
      'fucked out',
      'gaping',
      'numb',
      'spent',
      'fucked stupid',
    ],
  }),
  bankFamily(word('names-affectionate', 'Names — affectionate'), {
    1: [
      'baby',
      'babe',
      'beautiful',
      'gorgeous',
      'sweetheart',
      'honey',
      'love',
      'my love',
      'angel',
      'darling',
      'my girl',
      'my everything',
    ],
    2: ['pretty girl', 'handsome', 'my boy', 'sweet thing', 'beautiful girl', 'gorgeous girl'],
  }),
  bankFamily(word('names-power', 'Names — power & role'), {
    2: ['good girl', 'good boy', 'little one'],
    3: [
      'sir',
      "ma'am",
      'mistress',
      'daddy',
      'mommy',
      'princess',
      'kitten',
      'pet',
      'babygirl',
      'boy',
      'goddess',
      'queen',
      'my king',
      'bunny',
    ],
    4: [
      'master',
      'owner',
      'my property',
      'my toy',
      'plaything',
      'doll',
      'my pet',
      'my good girl',
      'my little whore',
    ],
  }),
  bankFamily(word('names-degrading', 'Names — degrading'), {
    3: [
      'naughty girl',
      'dirty girl',
      'bad girl',
      'filthy little thing',
      'greedy girl',
      'little tease',
      'cocktease',
    ],
    4: [
      'slut',
      'my slut',
      'little slut',
      'whore',
      'bitch',
      'brat',
      'dirty whore',
      'needy slut',
      'cock hungry',
      'filthy slut',
      'greedy little slut',
    ],
    5: [
      'cockslut',
      'cumslut',
      'cumdump',
      'fucktoy',
      'fuckdoll',
      'hole',
      'pathetic little slut',
      'worthless',
      'my filthy whore',
      'dumb slut',
      'desperate little whore',
      'breeding slut',
      'anal slut',
      'my cumrag',
      'pathetic whore',
      'good little fuckhole',
    ],
  }),
  bankFamily(phrase('claiming', 'Claiming & possession'), {
    2: ['mine', "you're mine", 'my girl', 'my boy', 'all mine'],
    3: [
      'you belong to me',
      'nobody else gets this',
      "say you're mine",
      'who do you belong to',
      'say it',
      "you're mine tonight",
      'own me',
    ],
    4: [
      'I own this pussy',
      'this cunt is mine',
      'mine to use',
      "you're my property",
      'every hole is mine',
      'say my name when you come',
      'this ass is mine',
      'nobody else touches this',
      'this mouth is mine',
      'own me completely',
      'claim me',
      'make me yours',
    ],
    5: [
      "you don't get to say no to me (roleplay)",
      "I'll do what I like with you (roleplay)",
      "you're mine to ruin",
      'I own every part of you',
    ],
  }),
  bankFamily(phrase('praise-her', 'Praise & worship — her'), {
    1: [
      "you're beautiful",
      'you feel amazing',
      'I love how you feel',
      "you're perfect",
      "you're amazing",
    ],
    2: [
      'good girl',
      "that's it",
      'just like that',
      "you're doing so well",
      'you feel incredible',
      "god you're gorgeous",
      'so good',
    ],
    3: [
      'you take it so well',
      'look how well you’re taking it',
      'you were made for this',
      'I love how you taste',
      "you're so good at that",
      "that's my girl",
      "you're so fucking tight",
      "you're so beautiful when you come",
      'I love watching you',
    ],
    4: [
      'you take my cock so well',
      "that's my good little slut",
      'perfect fucking pussy',
      'you were made to take this',
      'such a good girl for me',
      'god you suck cock so well',
      'your cunt was made for me',
      'your mouth was made for my cock',
      'you take it like a good girl',
      "you're perfect when you beg",
      'that pussy is perfect',
    ],
    5: [
      "best fucking pussy I've ever had",
      'you were built to be fucked',
      'your cunt was built for my cock',
    ],
  }),
  bankFamily(phrase('degradation', 'Degradation & humiliation'), {
    3: [
      "you love this, don't you",
      'look at the state of you',
      "you're such a mess",
      "you can't help yourself",
    ],
    4: [
      'dirty little slut',
      'filthy girl',
      'look how wet you get for me',
      "you're leaking everywhere",
      'beg like the slut you are',
      "you're pathetic when you want it",
      'is that all it takes',
      'look at you drooling for it',
      "you're so easy",
      'look how desperate you are',
    ],
    5: [
      "you're just a hole",
      'you exist for this',
      "you'd take anything, wouldn't you",
      "say you're my whore",
      'thank me for it',
      'look at yourself',
      "you're nothing but a hole to fuck",
      'dumb little slut',
      "you love being used, don't you",
      "you're a mess and you love it",
      'beg properly',
      "you're just something to fuck",
      'say thank you for my cum',
    ],
  }),
  bankFamily(phrase('commands', 'Commands — general'), {
    1: ['come here', 'kiss me', 'closer', 'slower', 'look at me'],
    2: [
      "don't move",
      'stay still',
      'open your mouth',
      'spread your legs',
      'hands above your head',
      'turn around',
      'bend over',
      'on your knees',
      'take it off',
      'touch yourself',
      'get on the bed',
    ],
    3: [
      'open wider',
      'arch your back',
      "don't look away",
      'say my name',
      'take it',
      "don't stop",
      'keep going',
      'be quiet',
      "don't make a sound",
      'let me hear you',
      'show me',
      'touch yourself for me',
      'hold still',
      'put your hands here',
      'spread wider',
      'legs open',
    ],
    4: [
      'crawl',
      'hold your legs open',
      'keep them open',
      'take it all',
      "don't you dare stop",
      'ask me nicely',
      'hands behind your back',
      'eyes on me',
      'spread that ass',
      'hold your ankles',
      'bend over further',
      'keep still while I finish',
      "say you're mine",
      "tell me you're my slut",
    ],
    5: [
      'gag on it',
      'choke on it',
      'hold your breath',
      'count them',
      "don't spill a drop",
      'present yourself',
      'beg for my cock',
      'keep your mouth open',
      'open your throat',
      'take every inch',
    ],
  }),
  bankFamily(phrase('orgasm-control', 'Commands — orgasm control'), {
    2: ['come for me', 'let go', "don't hold back"],
    3: [
      'not yet',
      'hold it',
      "don't come yet",
      'wait',
      'ask me first',
      'come now',
      "that's it, come",
      'slow down',
      'edge for me',
    ],
    4: [
      "don't come until I say",
      "you'll come when I tell you",
      'again',
      'one more',
      'ask permission',
      'you can come now',
      'good girl, come',
      'come on my cock',
      'hold it for me',
      "you're not done",
      'again, right now',
      'squirt for me',
    ],
    5: [
      "you don't get to come tonight (roleplay)",
      "hold it or you'll be punished (roleplay)",
      "you'll come when I'm done with you",
      "you'll come until I say stop",
      'come until it hurts',
    ],
  }),
  bankFamily(phrase('demands-receiving', 'Demands — the receiving voice'), {
    1: ['touch me', 'kiss me', 'closer', "don't stop", 'keep going'],
    2: [
      'fuck me',
      'harder',
      'deeper',
      'slower',
      'right there',
      'just like that',
      'I want you inside me',
      'I need you',
      'more',
      'kiss me there',
      'taste me',
    ],
    3: [
      'fuck me harder',
      'pound me',
      'pound my pussy',
      'fuck me from behind',
      'ride me',
      'suck my clit',
      'lick my pussy',
      'eat me',
      'finger me',
      'use your mouth',
      'put it in',
      'give it to me',
      "don't be gentle",
      'get in me',
      'rub my clit',
      'fuck me slow',
      'grind on me',
      'go deeper',
      'hit that spot',
      'I want your cock in me',
      'shove it in',
      'fill me',
    ],
    4: [
      'fuck me in the ass',
      'finger my asshole',
      'choke me',
      'stretch my pussy',
      'stretch my ass',
      'fill my mouth',
      'slap my pussy',
      'beat my pussy',
      'put it in my ass',
      'cum in me',
      'cum on me',
      'cum in my pussy',
      'cum in my mouth',
      'fill all my holes',
      'I wanna choke on your dick',
      'pull my hair',
      'spank me',
      'slap my tits',
      'hold me down',
      'spit in my mouth',
      'come on my face',
      'come on my tits',
      'use me',
      'make me beg',
      'ruin me',
      'breed me',
      'fill me up',
      'grab my throat',
      'fuck my throat',
      'stretch me open',
      'finger me while you fuck me',
      'hold my hips',
      'bend me over',
      'take me from behind',
      'fuck me harder than that',
      'rub my clit while you fuck me',
      'fuck me raw',
      'pin me down',
      'make me scream',
      'I want it rough',
      'hold my legs back',
      'put it back in',
    ],
    5: [
      'wreck my pussy',
      'choke me harder',
      'treat me like your whore',
      'use every hole',
      'make me take it',
      "fuck me till I can't walk",
      'destroy me',
      'use me like a toy',
      'split me open',
      'I want to feel it tomorrow',
      'fuck me until I cry',
      'use my throat',
      "don't be nice to me",
      'ruin every hole',
      "don't stop even if I say so (pre-agreed CNC, safeworded)",
    ],
  }),
  bankFamily(phrase('demands-giving', 'Demands — the giving voice'), {
    2: [
      'come here',
      'let me taste you',
      'I want to watch',
      'take it off',
      'sit on me',
      'I wanna taste you',
    ],
    3: [
      'suck that cock',
      'suck my cock',
      'lick my balls',
      'lick my ass',
      'get on your knees',
      'ride me',
      'sit on my face',
      'open your mouth',
      'take it',
      'look at me while you take it',
      'say my name',
      'tell me who owns this',
      'spread them',
      'bounce on it',
      'play with yourself for me',
      'put on a show',
      'get it wet',
      'spit on it',
    ],
    4: [
      'swallow it',
      'take it all',
      'deeper',
      'gag on it',
      'beg for it',
      'tell me what you are',
      'hold still while I use you',
      'arch for me',
      'give me that ass',
      'choke on my cock',
      'take my load',
      'open wider',
      'take it deeper',
      'hold it there',
      'look up at me',
      'suck my balls',
      'milk it',
      'take every inch',
      'squirt for me',
      "I'm gonna cum in your pussy",
      "I'm gonna cum in your mouth",
      "say you're my little slut",
    ],
    5: [
      "you'll take what I give you (roleplay)",
      "open up, I'm not done",
      "you'll take it till I'm finished",
      'beg me for my cum',
      'I wanna feel your juices explode around my cock',
    ],
  }),
  bankFamily(phrase('narration', 'Narration & feedback'), {
    1: ['that feels amazing', 'I love this', 'you feel so good'],
    2: [
      "you're so wet",
      "you're so hard",
      "you're so tight",
      "you're so big",
      'god you fill me',
      'I can feel you',
      'you feel incredible',
    ],
    3: [
      'I can feel you throb',
      'I can feel you clenching',
      "you're dripping down my hand",
      'listen to how wet you are',
      'look how hard you make me',
      "I'm going to come",
      "I've been hard all day",
      'I can still taste you',
      "you're shaking",
      "you're squeezing me",
      'I can hear how wet you are',
    ],
    4: [
      'your cunt is soaking',
      'I can feel you tightening around my cock',
      "you're leaking all over me",
      "I'm going to fill you",
      'watch it go in',
      'look at you taking every inch',
      "you're so fucking wet for me",
      'your pussy is gripping me',
      "you're taking it so deep",
      'your ass is so tight',
      'I can feel you stretching around me',
      "you're throbbing on my cock",
    ],
    5: [
      'listen to that',
      "you're making such a mess",
      'I can feel your cunt begging for it',
      "you're gushing",
      'look how well that little cunt takes it',
    ],
  }),
  bankFamily(phrase('begging', 'Begging & permission'), {
    2: ['please', 'I need it', "please don't stop", 'I want it'],
    3: [
      'please fuck me',
      'can I come',
      'may I come',
      'please let me',
      'I need you inside me',
      "I'm so close",
      'please, more',
      'please give it to me',
    ],
    4: [
      'please sir',
      'please daddy',
      'please let me come',
      "I'll be good",
      "I'll do anything",
      'please use me',
      'may I touch myself',
      'please fill me',
      'I need to come',
      'please cum in me',
    ],
    5: [
      'thank you',
      'thank you for letting me',
      'thank you for using me',
      "please, I'll be your good little slut",
      "I'm begging you",
      'please, I need your cum',
    ],
  }),
  bankFamily(phrase('sexting', 'Sexting & anticipation'), {
    1: ['thinking about you', "can't wait to see you", 'I miss you'],
    2: [
      "I've been thinking about last night",
      'what are you wearing',
      'I want you tonight',
      'come home',
      'are you alone',
    ],
    3: [
      "I'm so hard thinking about you",
      "I'm wet just typing this",
      "tell me what you'd do to me",
      'send me one',
      "I've been thinking about your mouth all day",
      "I'm touching myself",
      'describe it',
    ],
    4: [
      "I've been thinking about your cunt all day",
      "I'm going to ruin you tonight",
      'I want you on your knees when I get home',
      "I'm fucking you the second you walk in",
      "don't touch yourself until I'm home",
      'I want you dripping before I get there',
      "I'm going to fill you tonight",
      "I want your cock the second you're home",
    ],
    5: [
      "I'm going to use every hole tonight",
      "you'd better be ready for me",
      "I'm going to fuck you until you can't stand",
    ],
  }),
  bankFamily(phrase('aftercare', 'Aftercare & tenderness'), {
    1: [
      'come here',
      "I've got you",
      'that was perfect',
      'you did so well',
      'I love you',
      'stay right there',
      "you're incredible",
      'thank you',
    ],
    2: [
      'good girl',
      'you were so good',
      'are you okay',
      'let me hold you',
      "I'm proud of you",
      "you're safe",
      'you took that so well',
      'let me clean you up',
    ],
  }),
  bankFamily(
    phrase(
      'taboo',
      'Taboo fantasy & roleplay',
      'Every entry here is PRE-AGREED, SAFEWORDED ROLEPLAY between consenting adults, and is labelled as roleplay wherever it appears. Nothing here is about minors, real non-consent, or anything illegal.',
    ),
    {
      5: [
        'take it, you don’t get a choice (CNC roleplay)',
        "I'm not asking (CNC roleplay)",
        'fight me (CNC roleplay)',
        'stop struggling (CNC roleplay)',
        'rape me (CNC roleplay)',
        "I'm going to rape you (CNC roleplay)",
        "I'm going to take what I want (CNC roleplay)",
        "you're not getting away (CNC roleplay)",
        "you don't even know my name (stranger roleplay)",
        'boss / employee roleplay',
        'teacher / student roleplay (adults)',
        'doctor / patient roleplay',
        "does he know you're here (cheating roleplay)",
        "we shouldn't be doing this (cheating roleplay)",
        'tell me what he did to you (cuckold / hotwife)',
        'did you let him finish (cuckold / hotwife)',
        'did he fill you (cuckold / hotwife)',
        "I'm going to breed you (breeding)",
        "you're taking every drop (breeding)",
        "I'm putting a baby in you (breeding)",
        'run (primal)',
        "I'll catch you (primal)",
        'found you (primal)',
        'age-gap roleplay (adults)',
        "you're furniture tonight (objectification roleplay)",
        "you're just a hole to use (objectification roleplay)",
        "you shouldn't be here (caught-in-the-act roleplay)",
        'sex-worker roleplay',
        'being shared (fantasy roleplay)',
      ],
    },
  ),
  bankFamily(
    phrase(
      'delivery',
      'Delivery & voice',
      'Not words — how they are said. Half of what lands is not the word.',
    ),
    {
      1: ['whispered', 'in my ear', 'low and slow', 'breathless', 'saying my name'],
      2: ['commanding', 'growled', 'moaning', 'filthy but smiling', 'laughing'],
      3: [
        'loud',
        'silent, just sounds',
        'narrating the whole time',
        'a single word at the right moment',
        'right against my ear',
        'telling me what you’re about to do before you do it',
        'through gritted teeth',
        'begging under your breath',
      ],
      4: ["loud enough that they'd hear"],
    },
  ),
  bankFamily(phrase('oral', 'Oral'), {
    2: ['suck me', 'lick me', 'use your mouth', 'taste me', 'kiss me there', 'kiss it'],
    3: [
      'eat my pussy',
      'suck my cock',
      'lick my clit',
      'suck it',
      'put it in your mouth',
      'sit on my face',
      'lick me clean',
      'get it wet',
      'lick it slowly',
      'swallow me',
      'lick my balls',
      'suck my balls',
      'lick my ass',
      'tongue me',
      'suck it harder',
      'lick my clit faster',
    ],
    4: [
      'deepthroat it',
      'gag on it',
      'choke on my cock',
      'take it all the way',
      'fuck my face',
      'face-fuck me',
      'swallow it',
      "don't spill it",
      'look at me while you suck it',
      'worship it',
      "don't stop until I come in your mouth",
      'hold it in your mouth',
      'fill my mouth',
      'cum in my mouth',
      'rim me',
      'tongue my ass',
      'spit on it',
      'use your throat',
    ],
    5: ['use my throat', 'make me gag', 'leave me drooling', 'fuck my mouth like a pussy'],
  }),
  bankFamily(phrase('anal', 'Anal'), {
    2: ['touch me there', 'play with my ass'],
    3: [
      'finger my ass',
      'finger my asshole',
      'lick my ass',
      'rim me',
      'put a finger in',
      'slowly',
      'work it in',
      'spread my ass',
    ],
    4: [
      'fuck my ass',
      'put it in my ass',
      'stretch my ass',
      'take my ass',
      'in my ass',
      'plug me',
      'pound my ass',
      'all the way',
      'take it deeper',
      'cum in my ass',
      'finger my ass while you fuck me',
      'spit on my ass',
      'fuck my ass raw',
    ],
    5: [
      'ruin my ass',
      'both holes',
      'use my ass like a pussy',
      'fill all my holes',
      'destroy my ass',
    ],
  }),
  bankFamily(phrase('cum', 'Cum & finishing'), {
    2: ['come for me', "I'm close", "I'm going to come"],
    3: [
      'cum in me',
      'cum on me',
      'come with me',
      'I want to feel you come',
      'make me come',
      'finish in me',
      'inside me',
      'where do you want it',
    ],
    4: [
      'cum in my pussy',
      'cum in my mouth',
      'cum in my ass',
      'fill me up',
      'come on my face',
      'come on my tits',
      'come on my ass',
      'come on my back',
      'swallow it',
      'come all over me',
      'breed me',
      'paint me',
      'give me your load',
      "don't pull out",
      'in my throat',
      'let me taste it',
      "don't waste a drop",
      'give me every drop',
    ],
    5: [
      'make a mess of me',
      'I want to be dripping with it',
      'put it back in after',
      'fill both',
      'I want it leaking out of me',
      'fill all my holes',
    ],
  }),
  bankFamily(phrase('impact', 'Impact, restraint & pain'), {
    2: ['harder', 'pull my hair', 'hold me down'],
    3: [
      'spank me',
      'slap my ass',
      'grab my throat',
      'pin me',
      'bite me',
      'scratch me',
      'squeeze',
      'harder than that',
      'again',
      'spank me daddy',
    ],
    4: [
      'choke me',
      'slap my pussy',
      'beat my pussy',
      'slap my tits',
      'slap my face',
      'mark me',
      'leave a bruise',
      'tie me up',
      'hold my wrists',
      'harder, I can take it',
      'hold me down while you do it',
      'choke me while you fuck me',
      'spank me while I ride you',
    ],
    5: [
      'choke me harder',
      'hurt me a little',
      'make it sting',
      "don't be careful with me",
      "leave marks I'll see tomorrow",
    ],
  }),
  bankFamily(phrase('watched', 'Being watched / shared'), {
    3: [
      'I want to watch you',
      'watch me',
      'look at us',
      'imagine someone seeing this',
      'tell me a fantasy',
    ],
    4: [
      'would you let them watch',
      'tell me what he did',
      'I want to watch someone else make you come (fantasy)',
      'what if someone walked in',
    ],
    5: [
      'tell me how he fucked you (roleplay)',
      'I want to see you take someone else (roleplay)',
      'did you let him cum in you (roleplay)',
    ],
  }),
  bankFamily(phrase('praise-him', 'Praise & worship — him'), {
    1: ['you feel so good', 'I love your hands', 'I love your mouth'],
    2: ["you're so hard for me", 'you feel huge', 'I love your cock', "you're so good at that"],
    3: [
      'you fuck me so well',
      'nobody fills me like you',
      "you're so big",
      'I love how you use me',
      'you know exactly what you’re doing',
      'god, that cock',
      'your dick is huge',
    ],
    4: [
      'your cock ruins me',
      'you fuck me better than anyone',
      'you make me forget my name',
      'you fill me completely',
      'I love how you take what you want',
      'your dick is too big for my little cunt',
      'I love how you use my holes',
    ],
    5: ["I'd let you do anything to me", 'you own this pussy'],
  }),
  bankFamily(phrase('toys', 'Toys & objects'), {
    2: ['use it on me', 'get the toy', 'use your fingers and it'],
    3: [
      'fuck me with it',
      'hold it there',
      'turn it up',
      'put it inside me',
      'use it while you watch',
    ],
    4: [
      'both at once',
      'put the plug in',
      'leave it in',
      'make me come with it while you watch',
      'fuck me with it until I beg',
      'one in each hole',
    ],
    5: ["don't stop till the toy's done with me"],
  }),
  bankFamily(phrase('public-risk', 'Public & risk'), {
    2: ['be quiet', 'someone might hear', 'not here'],
    3: [
      "they'll hear us",
      'right here',
      "don't stop, someone's coming",
      'keep your voice down',
      "quick, before they're back",
    ],
    4: [
      "hold still, don't make a sound",
      'take it right here',
      'nobody knows what you’re doing',
      'under the table',
      'in the car',
    ],
    5: ['let them hear'],
  }),
  bankFamily(phrase('teasing', 'Teasing & denial'), {
    2: ['not yet', "you want it, don't you", 'patience'],
    3: [
      'ask me nicely',
      'say please',
      "you'll get it when I decide",
      'look how badly you want it',
      'almost',
      'I could keep you like this all night',
    ],
    4: [
      'beg me',
      "maybe I'll let you",
      "not until you've earned it",
      "you'll wait",
      'ask again, properly',
      'tell me how badly you want my cock',
    ],
    5: ['I could stop right now', "you'll take what I decide to give you"],
  }),
  bankFamily(
    phrase(
      'consent',
      'Consent & check-ins',
      'The language that makes the rest safe to want. Rated like everything else, because for some people being asked IS part of it and for others it breaks the spell — and partners get that wrong constantly.',
    ),
    {
      1: ['is this okay', 'you okay', 'too much?', 'more?', 'do you like that'],
      2: [
        "tell me if it's too much",
        'you can stop me',
        'colour?',
        'green / amber / red',
        'say the word and I stop',
        'we can stop any time',
      ],
      3: [
        'do you want more',
        'harder?',
        'can I',
        'do you want me to stop',
        'is this still good',
        'tell me what you need',
      ],
      4: ['you did so well, are you alright', 'was that too far', 'come back to me'],
    },
  ),
  bankFamily(phrase('comparisons', 'Comparisons & ego'), {
    2: ['nobody does that like you'],
    3: [
      'nobody fucks me like you',
      "I've never come like that",
      "you're the best I've had",
      "no one's ever made me feel like this",
    ],
    4: [
      'you ruined me for anyone else',
      "I don't want anyone else",
      "I've never done that with anyone else",
      "you're the biggest I've had",
      "nobody's ever filled me like this",
    ],
  }),
  bankFamily(phrase('morning-after', 'The morning after / next day'), {
    1: ["I'm still thinking about last night", 'last night was incredible'],
    2: ["I'm still sore", 'I can still feel you', 'I woke up wanting you', "I didn't sleep"],
    3: [
      "I'm sore in the best way",
      'I could still taste you this morning',
      "I've been thinking about it all morning",
    ],
    4: [
      'I want it again before work',
      "I'm still dripping from last night",
      'I can still feel where you were',
      "I'm still leaking you",
    ],
  }),
  bankFamily(phrase('size-fit', 'Size & fit'), {
    2: ["you're big", 'you feel huge', "it's a lot"],
    3: [
      'your dick is huge',
      "you're so big",
      'I can feel every inch',
      "you're stretching me",
      'it barely fits',
      "go slow, you're big",
    ],
    4: [
      'your dick is too big for my little cunt',
      "you're splitting me open",
      "I can't take it all",
      'take it all anyway',
      'make it fit',
      "you're too big for my ass",
      'stretch me around it',
    ],
    5: ['ruin me with it', "I don't care if it doesn't fit"],
  }),
  bankFamily(phrase('squirt', 'Squirting, wetness & mess'), {
    2: ["I'm so wet", 'look how wet I am'],
    3: [
      'I wanna squirt all over you',
      'make me squirt',
      "I'm going to squirt",
      "I'm soaking",
      "you're making me drip",
    ],
    4: [
      'squirt for me',
      'soak me',
      'look what you did to me',
      "I'm soaking the sheets",
      'you made a mess of me',
      "I'm dripping down my legs",
    ],
    5: ['I want to ruin the bed', "make me squirt until I can't take it"],
  }),
  bankFamily(phrase('taste', 'Taste & fluids'), {
    1: ['kiss me'],
    2: ['taste me', 'I wanna taste you', 'let me taste'],
    3: [
      'lick it off',
      'lick my fingers',
      'taste yourself on me',
      'I love how you taste',
      'get it on your tongue',
    ],
    4: [
      'spit it in my mouth',
      'share it',
      'kiss me after',
      'lick it off my tits',
      "don't swallow yet",
    ],
    5: ['let me lick you clean'],
  }),
  bankFamily(
    phrase(
      'role-lines',
      'Role-name lines',
      'The name inside a whole sentence, which is what people actually say.',
    ),
    {
      2: ['yes sir', "yes ma'am"],
      3: [
        'oh daddy',
        'yes daddy',
        'please daddy',
        'thank you daddy',
        'yes mistress',
        'please sir',
        'thank you sir',
      ],
      4: [
        'spank me daddy',
        'fuck me daddy',
        'harder daddy',
        'deeper daddy',
        "I'm your good girl daddy",
        'cum in me daddy',
        "yes daddy, I'm yours",
      ],
      5: ['use me daddy', "I'll be good for you daddy"],
    },
  ),
  bankFamily(
    phrase(
      'self-labelling',
      'Self-labelling',
      'Claiming it about yourself is a different act from being called it, and usually a bigger step — scoring them together would hide exactly that.',
    ),
    {
      2: ["I'm yours", "I'm all yours"],
      3: [
        "I'm your little slut",
        "I'm your slut",
        "I'm your good girl",
        'I belong to you',
        "I'm your dirty girl",
      ],
      4: [
        "I'm your whore",
        "I'm your fucktoy",
        "I'm your cumslut",
        "use me, I'm yours",
        "I'm your hole",
        'I exist for your cock',
      ],
      5: ["I'm nothing but your fucktoy", "I'm your worthless little slut"],
    },
  ),
]);
