import type { SelfosBridge } from '@shared/channels';
import type { BootState } from '@shared/schemas';
import { DEFAULT_ROLES } from '@shared/capabilities';
import { useSessionStore } from '../stores/sessionStore';

const READY: BootState = { phase: 'ready', vaultPath: '/vault', hasSettings: true };
const ONBOARDING: BootState = { phase: 'onboarding', vaultPath: null, hasSettings: false };

/** Install a fully-stubbed `window.selfos` bridge for tests; pass overrides for the bits you care about. */
export function installMockBridge(overrides: Partial<SelfosBridge> = {}): SelfosBridge {
  const bridge: SelfosBridge = {
    getBootState: () => Promise.resolve(READY),
    refreshBootState: () => Promise.resolve(READY),
    selectVaultFolder: () => Promise.resolve(null),
    useVault: () => Promise.resolve(READY),
    unlinkVault: () => Promise.resolve(ONBOARDING),
    getConflicts: () => Promise.resolve([]),
    vaultSyncReadiness: () => Promise.resolve({ ready: true }),
    revealVault: () => Promise.resolve(),
    onVaultChanged: () => () => {},
    platform: 'web',
    onFullscreenChanged: () => () => {},
    getAppVersion: () => Promise.resolve('0.0.0'),
    getSettings: () => Promise.resolve({ vault: {}, device: {} }),
    setSetting: () => Promise.resolve(),
    resetSetting: () => Promise.resolve(),
    secretSet: () => Promise.resolve(),
    secretHas: () => Promise.resolve(false),
    secretClear: () => Promise.resolve(),
    claudeTest: () => Promise.resolve({ ok: true, text: 'ok' }),
    openaiTest: () => Promise.resolve({ ok: true, text: 'ok' }),
    aiKeyStatus: () =>
      Promise.resolve({
        hasSharedKey: false,
        hasDeviceOverride: false,
        resolvedReady: false,
        source: 'none' as const,
      }),
    aiSetSharedKey: () => Promise.resolve(),
    aiShareDeviceKey: () => Promise.resolve(),
    aiClearSharedKey: () => Promise.resolve(),
    devicesList: () => Promise.resolve([]),
    devicesRename: () => Promise.resolve(),
    keysRotate: () =>
      Promise.resolve({
        ok: true as const,
        recoveryPhrase: 'word '.repeat(12).trim(),
        reencryptedFileCount: 0,
        revokedDeviceIds: [],
        cancelledInviteCount: 0,
      }),
    keysRotateStatus: () => Promise.resolve(null),
    householdStatus: () =>
      Promise.resolve({
        vaultInitialized: true,
        hasMasterKey: true,
        hasOwner: true,
        activePersonId: 'owner-1',
        pendingJoinPersonId: null,
      }),
    householdSetup: () => Promise.resolve({ recoveryPhrase: 'TEST-PHRASE', ownerId: 'owner-1' }),
    unlockWithRecoveryPhrase: () => Promise.resolve({ ok: true }),
    getActivePerson: () => Promise.resolve(null),
    peopleList: () => Promise.resolve([]),
    peopleSave: (input) =>
      Promise.resolve({
        id: input.id ?? 'new-id',
        schemaVersion: 1,
        displayName: input.displayName,
        isSubject: input.isSubject,
        tags: input.tags,
        createdAt: 'now',
        updatedAt: 'now',
      }),
    peopleDelete: () => Promise.resolve(),
    relationshipsList: () => Promise.resolve([]),
    relationshipsSave: (input) =>
      Promise.resolve({
        id: input.id ?? 'new-rel',
        schemaVersion: 1,
        fromPersonId: input.fromPersonId,
        toPersonId: input.toPersonId,
        type: input.type,
        createdAt: 'now',
        updatedAt: 'now',
      }),
    relationshipsDelete: () => Promise.resolve(),
    accessGet: () =>
      Promise.resolve({
        roles: DEFAULT_ROLES,
        accounts: [{ personId: 'owner-1', roleId: 'owner', hasPin: false }],
      }),
    accessSaveRole: () => Promise.resolve({ roles: DEFAULT_ROLES, accounts: [] }),
    accessSetAccount: () => Promise.resolve({ roles: DEFAULT_ROLES, accounts: [] }),
    accessRemoveAccount: () => Promise.resolve({ roles: DEFAULT_ROLES, accounts: [] }),
    invitesCreate: () =>
      Promise.resolve({ code: 'amber-tide-fox-quill-river-stone', expiresAt: '' }),
    invitesList: () => Promise.resolve([]),
    invitesCancel: () => Promise.resolve(),
    invitesRedeem: () => Promise.resolve({ ok: true, displayName: 'Wife' }),
    invitesCompleteJoin: () => Promise.resolve({ ok: true }),
    sessionSetActive: (input) =>
      Promise.resolve({
        ok: true,
        person: {
          id: input.personId,
          schemaVersion: 1,
          displayName: 'Someone',
          isSubject: true,
          tags: [],
          createdAt: 'now',
          updatedAt: 'now',
        },
      }),
    usageSummary: () =>
      Promise.resolve({
        totalCostUsd: 0,
        inputTokens: 0,
        outputTokens: 0,
        cacheWriteTokens: 0,
        cacheReadTokens: 0,
        cacheSavingsUsd: 0,
        sessionCount: 0,
        avgCostPerSession: 0,
        avgCostPerType: 0,
        byType: {},
        byModel: {},
        byPerson: {},
      }),
    budgetGet: () => Promise.resolve({ app: null, person: null }),
    budgetGetPerson: () =>
      Promise.resolve({ limitUsd: 10, period: 'week' as const, warnRatio: 0.8 }),
    budgetSetApp: () => Promise.resolve(),
    budgetSetPerson: () => Promise.resolve(),
    budgetStatus: () =>
      Promise.resolve({
        person: { state: 'none', budgetRatio: 0, spentUsd: 0, limitUsd: null, period: null },
        app: { state: 'none', budgetRatio: 0, spentUsd: 0, limitUsd: null, period: null },
      }),
    chatStream: (input) =>
      Promise.resolve({
        ok: true,
        conversation: {
          id: input.conversationId,
          schemaVersion: 1,
          personId: 'owner-1',
          title: input.userText,
          createdAt: 'now',
          updatedAt: 'now',
          messages: [
            {
              role: 'user',
              content: input.userText,
              ts: 'now',
              ...(input.attachments && input.attachments.length > 0
                ? { attachments: input.attachments }
                : {}),
            },
            { role: 'assistant', content: 'I hear you.', ts: 'now' },
          ],
        },
        usage: {
          id: 'u',
          schemaVersion: 1,
          type: 'chat',
          personId: 'owner-1',
          model: 'claude-sonnet-4-6',
          at: 'now',
          inputTokens: 100,
          outputTokens: 10,
          cacheWriteTokens: 0,
          cacheReadTokens: 0,
          costUsd: 0.001,
        },
      }),
    chatRetry: () =>
      Promise.resolve({
        ok: false as const,
        reason: 'ERROR' as const,
        message: 'There’s nothing to retry here.',
      }),
    onChatChunk: () => () => {},
    conversationStoreAttachment: (input) =>
      Promise.resolve({
        id: 'att-1',
        kind: 'image',
        mime: input.mime,
        path: `people/owner-1/conversations/${input.conversationId}/attachments/att-1.enc`,
        ...(input.width !== undefined ? { width: input.width } : {}),
        ...(input.height !== undefined ? { height: input.height } : {}),
        ...(input.bytes !== undefined ? { bytes: input.bytes } : {}),
      }),
    conversationGetAttachment: () =>
      Promise.resolve({
        mime: 'image/png',
        dataBase64:
          'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
      }),
    conversationExportAttachment: () => Promise.resolve('/tmp/session-image.png'),
    conversationsList: () => Promise.resolve([]),
    conversationsGet: () => Promise.resolve(null),
    conversationsRename: () => Promise.resolve(),
    conversationsDelete: () => Promise.resolve(),
    sessionsSetStatus: () => Promise.resolve(null),
    sessionsEndAndSummarize: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'not configured' }),
    sessionsStartGuided: () => Promise.resolve(null),
    guidedGetState: () => Promise.resolve({ cache: null, adultAcknowledged: false }),
    guidedSuggest: () =>
      Promise.resolve({ ok: false, reason: 'DENIED', message: 'not configured' }),
    guidedAcknowledgeAdult: () => Promise.resolve({ cache: null, adultAcknowledged: true }),
    testsList: () => Promise.resolve({ tests: [], adultAcknowledged: false }),
    testsGet: () => Promise.resolve(null),
    testsTake: () => Promise.resolve(null),
    testsResults: () => Promise.resolve([]),
    testsNarrate: () => Promise.resolve({ ok: false, reason: 'AI_OFF', message: 'not configured' }),
    testsAcknowledgeAdult: () => Promise.resolve({ tests: [], adultAcknowledged: true }),
    testsDeleteResult: () => Promise.resolve([]),
    testsDeleteAll: () => Promise.resolve(),
    usageSessionCosts: () => Promise.resolve({}),
    questionnairesList: () => Promise.resolve([]),
    questionnairesSendStates: () => Promise.resolve({}),
    questionnairesSentOverview: () => Promise.resolve({}),
    questionnairesShareLink: () => Promise.resolve(null),
    questionnairesGet: () => Promise.resolve(null),
    questionnairesSave: (input) =>
      Promise.resolve({
        id: input.id ?? 'new-q',
        schemaVersion: 1,
        version: 1,
        title: input.title,
        type: input.type,
        sensitivity: input.sensitivity,
        questions: input.questions,
        createdAt: 'now',
        updatedAt: 'now',
      }),
    questionnairesDelete: () => Promise.resolve(),
    questionnairesValidate: () => Promise.resolve([]),
    questionnairesSetFavorite: () => Promise.resolve(),
    questionnairesListTypes: () => Promise.resolve([]),
    questionnairesAddType: (name) => Promise.resolve([name]),
    questionnairesIntimacyTopics: () =>
      Promise.resolve({
        builtIn: { activities: [], fantasies: [] },
        custom: { activities: [], fantasies: [] },
      }),
    questionnairesAddIntimacyTopic: () =>
      Promise.resolve({
        builtIn: { activities: [], fantasies: [] },
        custom: { activities: [], fantasies: [] },
      }),
    questionnairesRemoveIntimacyTopic: () =>
      Promise.resolve({
        builtIn: { activities: [], fantasies: [] },
        custom: { activities: [], fantasies: [] },
      }),
    questionnairesSuggestIntimacyTopics: () =>
      Promise.resolve({
        ok: true as const,
        suggestions: { activities: [], fantasies: [] },
      }),
    questionnairesStoreImage: (input) =>
      Promise.resolve({ imagePath: 'questionnaires/media/mock.enc', mime: input.mime }),
    questionnairesGetImage: () => Promise.resolve(null),
    questionnairesDeleteImage: () => Promise.resolve(),
    questionnairesGenerate: () => Promise.resolve({ ok: true, questions: [] }),
    questionnairesImproveQuestion: () => Promise.resolve({ ok: true, prompt: 'improved' }),
    gapfinderSuggest: () => Promise.resolve({ ok: true, suggestions: [] }),
    questionnaireSuggestionsList: () => Promise.resolve([]),
    questionnaireSuggestionsGenerate: () => Promise.resolve({ ok: true, saved: [], added: 0 }),
    questionnaireSuggestionDelete: () => Promise.resolve([]),
    questionnaireSuggestionMaterialize: () => Promise.resolve({ ok: true, questions: [] }),
    insightsList: () => Promise.resolve([]),
    memoryOutboundSharing: () => Promise.resolve({ items: [] }),
    insightsAnalyze: () => Promise.resolve({ ok: false, reason: 'NO_RESPONSE' }),
    insightsApprove: () => Promise.resolve(null),
    insightsUpdate: () => Promise.resolve(null),
    insightsDelete: () => Promise.resolve(),
    insightsFlag: () => Promise.resolve(null),
    memoryRefresh: () => Promise.resolve({ ok: true, reconciledCount: 0, mergedCount: 0 }),
    memoryReconcileState: () => Promise.resolve({ proposals: [] }),
    memoryResolveProposal: () => Promise.resolve(),
    goalsList: () => Promise.resolve([]),
    goalsSetStatus: () => Promise.resolve(null),
    goalsUpdate: () => Promise.resolve(null),
    goalsDelete: () => Promise.resolve(),
    goalsCreate: () => Promise.resolve(null),
    goalsSuggest: () => Promise.resolve({ ok: false, message: 'Not available.' }),
    coachingGetPrefs: () => Promise.resolve({ schemaVersion: 1 }),
    coachingSetPrefs: (input) => Promise.resolve({ schemaVersion: 1, ...input }),
    coachingGetSynthesis: () => Promise.resolve(null),
    coachingSynthesize: () =>
      Promise.resolve({ ok: false, reason: 'EMPTY', message: 'Nothing yet.' }),
    autoCheckinsGetConfig: () => Promise.resolve({ schemaVersion: 1, enabled: false, targets: [] }),
    autoCheckinsSetConfig: (input) =>
      Promise.resolve({ schemaVersion: 1, enabled: false, targets: [], ...input }),
    autoCheckinsEnsureSeed: () =>
      Promise.resolve({ seeded: false, config: { schemaVersion: 1, enabled: false, targets: [] } }),
    autoCheckinsRun: () => Promise.resolve({ ok: false, reason: 'SKIPPED', message: 'Off.' }),
    storyBookTypes: () => Promise.resolve([]),
    storyList: () => Promise.resolve([]),
    storyCreate: () => Promise.resolve(null),
    storyGet: () => Promise.resolve(null),
    storyGenerateFoundations: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'Not available.' }),
    storySaveOutline: () => Promise.resolve(null),
    storyApproveOutline: () => Promise.resolve(null),
    storyUpdate: () => Promise.resolve(null),
    storyDelete: () => Promise.resolve(),
    storyRewriteFromScratch: () => Promise.resolve(null),
    storyGenerateChapters: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'Not available.' }),
    storyRegenerateChapter: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'Not available.' }),
    storyReviewChapter: () => Promise.resolve(null),
    storyGetMarkup: (input) =>
      Promise.resolve({ schemaVersion: 1, chapterId: input.chapterId, marks: [] }),
    storyMark: (input) =>
      Promise.resolve({ schemaVersion: 1, chapterId: input.chapterId, marks: [input.mark] }),
    storyUpdateMark: () => Promise.resolve(null),
    storyRemoveMark: (input) =>
      Promise.resolve({ schemaVersion: 1, chapterId: input.chapterId, marks: [] }),
    storyApplyMarkup: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'Not available.' }),
    storyEditPassage: () => Promise.resolve(null),
    storyPinQuote: () => Promise.resolve(null),
    storyTodos: () => Promise.resolve({ schemaVersion: 1, todos: [] }),
    storyExclusions: () => Promise.resolve([]),
    storyExclude: (input) =>
      Promise.resolve({
        exclusions: [{ id: 'x1', kind: input.kind, value: input.value, createdAt: 'now' }],
        bundle: {
          manifest: {
            id: input.bookId,
            schemaVersion: 1,
            personId: 'me',
            type: 'biography',
            title: 'Book',
            config: { voice: 'third', style: 'warm', length: 'standard', autoRefresh: true },
            status: 'ready',
            sharedWith: [],
            createdAt: 'now',
            updatedAt: 'now',
          },
          outline: null,
          timeline: null,
          chapters: [],
        },
        staled: 0,
      }),
    storyUnexclude: () => Promise.resolve([]),
    storyTodoToQuestions: () =>
      Promise.resolve({ ok: false, reason: 'ERROR', message: 'Not available.' }),
    storyRefreshCheck: () => Promise.resolve({ staled: 0, rewritten: 0, bundle: null }),
    storyProposals: () => Promise.resolve([]),
    storyResolveProposal: () => Promise.resolve({ ok: true, proposals: [], bundle: null }),
    storyHomeSignal: () =>
      Promise.resolve({
        hasBook: false,
        staleChapters: 0,
        pendingProposals: 0,
        unwrittenChapters: 0,
        signature: '',
      }),
    storyCompleteness: () =>
      Promise.resolve({ stage: 'beginning' as const, ratio: 0, covered: 0, total: 12 }),
    storyInterviewCheck: () => Promise.resolve({ outcome: 'noBook' as const }),
    storyGaps: () => Promise.resolve({ gaps: [], partCoverage: [], hasOpenCheckin: false }),
    storyAskGap: () =>
      Promise.resolve({ ok: false as const, reason: 'ERROR' as const, message: 'x' }),
    storyAnsweredCheckIns: () => Promise.resolve([]),
    storyPublish: () => Promise.resolve({ ok: false as const, message: 'Not available.' }),
    storyReaders: () => Promise.resolve([]),
    storyGrantReader: () => Promise.resolve([]),
    storyRevokeReader: () => Promise.resolve([]),
    storyReaderFeatured: () => Promise.resolve(false),
    storySharedBooks: () => Promise.resolve([]),
    storyReadShared: () => Promise.resolve(null),
    storyReadOwnBook: () => Promise.resolve(null),
    storySetReadPosition: () => Promise.resolve(),
    storyMarkSharedRead: () => Promise.resolve(),
    storyGenerateFullDraft: () => Promise.resolve({ ok: false, reason: 'ERROR', message: '' }),
    onStoryProgress: () => () => {},
    onImageProgress: () => () => {},
    storyReadSharedImage: () => Promise.resolve(null),
    storyExportMarkdown: () => Promise.resolve(null),
    storyExportPdf: () => Promise.resolve(null),
    storyImages: () => Promise.resolve([]),
    storyGenerateImage: () => Promise.resolve({ ok: false, reason: 'NO_CONSENT', message: 'off' }),
    storyGetImage: () => Promise.resolve(null),
    storyDeleteImage: () => Promise.resolve(),
    storyUploadPhoto: () => Promise.resolve(null),
    storyAnalyzePhoto: () => Promise.resolve({ ok: false, reason: 'NO_KEY', message: 'off' }),
    storyAnswerPhoto: () => Promise.resolve(),
    storyPhotoAnswers: () => Promise.resolve([]),
    storySuggestPlacement: () => Promise.resolve({ ok: true, afterAnchor: 'p0' }),
    storySetPlacement: () => Promise.resolve(null),
    storyRemovePlacement: () => Promise.resolve(null),
    relationshipsGetSynthesis: () => Promise.resolve(null),
    relationshipsSynthesize: () =>
      Promise.resolve({ ok: false, reason: 'EMPTY', message: 'Nothing yet.' }),
    challengesStart: () => Promise.resolve({ conversationId: 'c-challenge' }),
    challengesStartReflection: () => Promise.resolve({ conversationId: 'c-reflect' }),
    challengesList: () => Promise.resolve([]),
    challengesGet: () => Promise.resolve(null),
    challengesSetStatus: () => Promise.resolve(null),
    challengesCheckIn: () => Promise.resolve({ ok: false, reason: 'NOT_FOUND', message: 'Gone.' }),
    challengesSnooze: () => Promise.resolve(null),
    challengesSeedGoal: () => Promise.resolve(null),
    challengesDelete: () => Promise.resolve(),
    challengesSuggest: () =>
      Promise.resolve({ ok: false, reason: 'EMPTY', message: 'Nothing yet.' }),
    challengesGetSuggestion: () => Promise.resolve(null),
    challengesClearSuggestion: () => Promise.resolve(),
    // Together / couples sessions (58).
    togetherList: () => Promise.resolve([]),
    togetherGet: () => Promise.resolve(null),
    togetherCreate: () => Promise.resolve({ ok: false, reason: 'NO_EDGE', message: 'No partner.' }),
    togetherAccept: () => Promise.resolve(null),
    togetherDecline: () => Promise.resolve(),
    togetherSetPaused: () => Promise.resolve(null),
    togetherLeave: () => Promise.resolve(null),
    togetherWithdraw: () => Promise.resolve(false),
    togetherMarkRead: () => Promise.resolve(),
    togetherSendMessage: () =>
      Promise.resolve({ ok: false, reason: 'NOT_ALLOWED', message: 'Not available.' }),
    togetherRetry: () =>
      Promise.resolve({ ok: false, reason: 'NOT_ALLOWED', message: 'Not available.' }),
    onTogetherChunk: () => () => {},
    togetherPrepOpen: () => Promise.resolve(null),
    togetherStoreAttachment: () =>
      Promise.resolve({ ok: false, reason: 'NOT_FOUND', message: 'Not available.' }),
    togetherGetAttachment: () => Promise.resolve(null),
    togetherCatalog: () => Promise.resolve([]),
    togetherAcknowledgeAdult: () => Promise.resolve(false),
    togetherYnmStatus: () =>
      Promise.resolve({
        youAcked: false,
        eligible: false,
        youOptedIn: false,
        partnerOptedIn: false,
        ready: false,
      }),
    togetherYnmOptIn: () =>
      Promise.resolve({
        youAcked: false,
        eligible: false,
        youOptedIn: false,
        partnerOptedIn: false,
        ready: false,
      }),
    togetherYnmRevoke: () =>
      Promise.resolve({
        youAcked: false,
        eligible: false,
        youOptedIn: false,
        partnerOptedIn: false,
        ready: false,
      }),
    togetherYnmOverlap: () => Promise.resolve({ ready: false, items: [] }),
    togetherPulse: () =>
      Promise.resolve({
        checkInSeries: [],
        sessionSeries: [],
        hasCheckIns: false,
        alignment: { ready: false },
      }),
    togetherPulseLog: () =>
      Promise.resolve({
        checkInSeries: [],
        sessionSeries: [],
        hasCheckIns: false,
        alignment: { ready: false },
      }),
    togetherJointChallenges: () => Promise.resolve([]),
    togetherSuggestions: () => Promise.resolve([]),
    togetherWrapUp: () =>
      Promise.resolve({ ok: false, reason: 'NOT_ALLOWED', message: 'Not available.' }),
    togetherGetReport: () => Promise.resolve({ report: null, stale: false, agreements: [] }),
    togetherSaveAgreement: () => Promise.resolve(null),
    togetherMyAgreements: () => Promise.resolve([]),
    togetherDoneCommitments: () => Promise.resolve([]),
    togetherSetAgreementStatus: () => Promise.resolve(null),
    assignmentsCreate: (input) =>
      Promise.resolve({
        assignment: {
          id: 'new-a',
          schemaVersion: 1,
          questionnaireId: input.questionnaireId,
          senderPersonId: 'owner-1',
          recipient: { kind: 'person' as const, personId: 'recipient-1' },
          channel: 'inApp' as const,
          privacy: input.privacy ?? 'standard',
          senderVisibleToRecipient: input.senderVisibleToRecipient ?? true,
          status: 'sent' as const,
          createdAt: 'now',
          updatedAt: 'now',
        },
      }),
    assignmentsInbox: () => Promise.resolve([]),
    assignmentsSetFavorite: () => Promise.resolve(),
    assignmentsGet: () => Promise.resolve(null),
    assignmentsOpen: () => Promise.resolve(),
    assignmentsSaveProgress: () => Promise.resolve(),
    assignmentsReopen: () => Promise.resolve(),
    assignmentsSubmit: () => Promise.resolve(),
    assignmentsDecline: () => Promise.resolve(),
    assignmentsResults: () => Promise.resolve([]),
    assignmentsTrends: () => Promise.resolve([]),
    assignmentsAggregate: () => Promise.resolve({ questions: [] }),
    assignmentsDelete: () => Promise.resolve(),
    assignmentsCreateCompatibility: () =>
      Promise.resolve({ ok: true, compatibilityGroupId: 'group-1' }),
    assignmentsCompatibility: () => Promise.resolve([]),
    assignmentsAlign: () =>
      Promise.resolve({ ok: false, reason: 'NOT_READY', message: 'Not ready.' }),
    assignmentsPublishCompatResult: () =>
      Promise.resolve({ ok: false, reason: 'NOT_READY', message: 'Not ready.' }),
    assignmentsDistillContextOnly: () =>
      Promise.resolve({ ok: false, reason: 'NOT_READY', message: 'Not ready.' }),
    assignmentsRevealRaw: () => Promise.resolve(null),
    assignmentsCreateRelayLink: () =>
      Promise.resolve({ assignmentId: 'a1', link: 'https://relay.test/q/t#k=k', pin: '000000' }),
    assignmentsDrain: () => Promise.resolve({ drained: 0, declined: 0 }),
    assignmentsRevoke: () => Promise.resolve(),
    assignmentsReshare: () => Promise.resolve(null),
    assignmentsReAsk: (input) =>
      Promise.resolve({
        assignment: {
          id: 'reask-a',
          schemaVersion: 1,
          questionnaireId: input.questionnaireId,
          senderPersonId: 'owner-1',
          recipient: { kind: 'person' as const, personId: 'recipient-1' },
          channel: 'inApp' as const,
          privacy: 'standard' as const,
          senderVisibleToRecipient: true,
          status: 'sent' as const,
          createdAt: 'now',
          updatedAt: 'now',
        },
      }),
    assignmentsExportResults: () => Promise.resolve('/tmp/results.csv'),
    relayStatus: () => Promise.resolve({ configured: false, updateAvailable: false }),
    relayConnect: () => Promise.resolve({ configured: false, updateAvailable: false }),
    relayUpdate: () => Promise.resolve({ configured: false, updateAvailable: false }),
    relayTeardown: () => Promise.resolve({ configured: false, updateAvailable: false }),
    dreamsList: () => Promise.resolve([]),
    dreamGet: () => Promise.resolve(null),
    dreamSave: (input) =>
      Promise.resolve({
        id: input.id ?? 'new-dream',
        schemaVersion: 1,
        personId: 'owner-1',
        narrative: input.narrative,
        lucid: input.lucid,
        nightmare: input.nightmare,
        tags: input.tags,
        people: input.people,
        sensitivity: input.sensitivity,
        status: 'captured' as const,
        createdAt: 'now',
        updatedAt: 'now',
      }),
    dreamDelete: () => Promise.resolve(),
    dreamStartReflection: (input) =>
      Promise.resolve({
        ok: true,
        conversation: {
          id: input.dreamId,
          schemaVersion: 1,
          personId: 'owner-1',
          title: 'Dream',
          createdAt: 'now',
          updatedAt: 'now',
          messages: [
            {
              role: 'assistant',
              content:
                'You were back in your childhood house, the rooms rearranging. What were you feeling as it shifted?',
              ts: 'now',
            },
          ],
        },
      }),
    dreamAnalyzeTurn: (input) =>
      Promise.resolve({
        ok: true,
        conversation: {
          id: input.dreamId,
          schemaVersion: 1,
          personId: 'owner-1',
          title: 'Dream',
          createdAt: 'now',
          updatedAt: 'now',
          messages: [
            { role: 'user', content: input.userText, ts: 'now' },
            { role: 'assistant', content: 'Tell me more about how it felt.', ts: 'now' },
          ],
        },
        usage: {
          id: 'u',
          schemaVersion: 1,
          type: 'dream.analyze',
          personId: 'owner-1',
          sessionId: input.dreamId,
          model: 'claude-sonnet-4-6',
          at: 'now',
          inputTokens: 100,
          outputTokens: 10,
          cacheWriteTokens: 0,
          cacheReadTokens: 0,
          costUsd: 0.001,
        },
      }),
    onDreamChunk: () => () => {},
    dreamGetAnalysis: () => Promise.resolve(null),
    dreamGetConversation: () => Promise.resolve(null),
    dreamSynthesize: (input) =>
      Promise.resolve({
        ok: true,
        analysis: {
          id: 'analysis-1',
          schemaVersion: 1,
          dreamId: input.dreamId,
          personId: 'owner-1',
          summary: 'A dream of shifting rooms.',
          emotionalLandscape: 'Unsettled but curious.',
          wakingLifeConnections: 'Perhaps a sense of change at home.',
          notableImages: 'The rearranging house, as imaginative reflection.',
          reflectiveQuestions: ['What feels in flux right now?'],
          tags: { emotions: [], symbols: [], settings: [], themes: [], people: [] },
          edited: false,
          generatedAt: 'now',
          updatedAt: 'now',
        },
        usage: {
          id: 'u',
          schemaVersion: 1,
          type: 'dream.analyze',
          personId: 'owner-1',
          sessionId: input.dreamId,
          model: 'claude-sonnet-4-6',
          at: 'now',
          inputTokens: 200,
          outputTokens: 50,
          cacheWriteTokens: 0,
          cacheReadTokens: 0,
          costUsd: 0.003,
        },
      }),
    dreamUpdateAnalysis: () => Promise.resolve(null),
    dreamApprove: () => Promise.resolve({ ok: true, insightId: 'insight-1' }),
    dreamRemoveFromContext: () => Promise.resolve(),
    dreamPatternStats: (input) =>
      Promise.resolve({
        window: input.window,
        dreamCount: 0,
        analyzedCount: 0,
        symbols: [],
        themes: [],
        people: [],
        emotions: [],
        lucidCount: 0,
        nightmareCount: 0,
        moodTrend: [],
        vividnessTrend: [],
        nightmareNudge: false,
      }),
    dreamGetPatternSummary: () => Promise.resolve(null),
    dreamPatternNarrative: () =>
      Promise.resolve({
        ok: true,
        summary: {
          schemaVersion: 1,
          personId: 'owner-1',
          narrative: 'Across your recent dreams, a thread of searching recurs.',
          windowFrom: '2026-06-01',
          windowTo: '2026-06-11',
          computedAt: 'now',
        },
        usage: {
          id: 'u',
          schemaVersion: 1,
          type: 'dream.patterns',
          personId: 'owner-1',
          model: 'claude-sonnet-4-6',
          at: 'now',
          inputTokens: 30,
          outputTokens: 20,
          cacheWriteTokens: 0,
          cacheReadTokens: 0,
          costUsd: 0.001,
        },
      }),
    dreamApprovePatternNarrative: () => Promise.resolve({ ok: true, insightId: 'insight-2' }),
    dreamRemovePatternNarrative: () => Promise.resolve(),
    dreamShareTargets: () => Promise.resolve([]),
    dreamGetInsight: () => Promise.resolve(null),
    dreamSetFactShare: () => Promise.resolve({ ok: true }),
    dreamGenerateImage: () => Promise.resolve({ ok: true, mime: 'image/png' }),
    dreamGetImage: () => Promise.resolve(null),
    dreamDeleteImage: () => Promise.resolve(),
    dreamExportImage: () => Promise.resolve(null),
    dreamSetImageShare: () => Promise.resolve({ ok: true }),
    dreamGetSharedImage: () => Promise.resolve(null),
    dreamListSharedImages: () => Promise.resolve([]),
    intakeGetState: () =>
      Promise.resolve({
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'inProgress',
          sections: [],
          startedAt: 'now',
          updatedAt: 'now',
        },
        sections: [],
        aiAvailable: false,
        adultAcknowledged: false,
      }),
    intakeRunTurn: (input) =>
      Promise.resolve({
        ok: true,
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'inProgress',
          sections: [
            {
              id: input.sectionId,
              status: 'inProgress',
              restricted: false,
              messages: [
                { role: 'user', content: input.userText, ts: 'now' },
                { role: 'assistant', content: 'Thank you for sharing that.', ts: 'now' },
              ],
              answers: {},
            },
          ],
          startedAt: 'now',
          updatedAt: 'now',
        },
        usage: {
          id: 'u',
          schemaVersion: 1,
          type: 'intake.interview',
          personId: 'owner-1',
          model: 'claude-sonnet-4-6',
          at: 'now',
          inputTokens: 10,
          outputTokens: 10,
          cacheWriteTokens: 0,
          cacheReadTokens: 0,
          costUsd: 0.001,
        },
      }),
    onIntakeChunk: () => () => {},
    intakeSkipSection: () =>
      Promise.resolve({
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'inProgress',
          sections: [],
          startedAt: 'now',
          updatedAt: 'now',
        },
        sections: [],
        aiAvailable: false,
        adultAcknowledged: false,
      }),
    intakeSubmitForm: () =>
      Promise.resolve({
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'inProgress',
          sections: [],
          startedAt: 'now',
          updatedAt: 'now',
        },
        sections: [],
        aiAvailable: false,
        adultAcknowledged: false,
      }),
    intakeSetAnswerSharing: () => Promise.resolve(true),
    profileSuggestions: () => Promise.resolve([]),
    profileAcceptSuggestion: () => Promise.resolve([]),
    profileDismissSuggestion: () => Promise.resolve([]),
    intakeAcknowledgeAdult: () =>
      Promise.resolve({
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'inProgress',
          sections: [],
          startedAt: 'now',
          updatedAt: 'now',
        },
        sections: [],
        aiAvailable: true,
        adultAcknowledged: true,
      }),
    intakeSynthesize: () =>
      Promise.resolve({
        ok: true,
        session: {
          id: 'intake-1',
          schemaVersion: 1,
          personId: 'owner-1',
          status: 'complete',
          sections: [],
          startedAt: 'now',
          updatedAt: 'now',
          portrait: 'Here is what I have come to understand about you.',
          insightId: 'intake-insight-1',
        },
        portrait: 'Here is what I have come to understand about you.',
        insightId: 'intake-insight-1',
      }),
    getSidebarCollapsed: () => Promise.resolve(false),
    setSidebarCollapsed: () => Promise.resolve(),
    getDiscoveryDismissals: () => Promise.resolve([]),
    setDiscoveryDismissals: () => Promise.resolve(),
    getNotificationState: () => Promise.resolve({ read: {}, dismissed: {} }),
    setNotificationState: () => Promise.resolve(),
    notificationsResponsesArrived: () => Promise.resolve([]),
    notificationsAnswersUpdated: () => Promise.resolve([]),
    notificationsRemindersDue: () => Promise.resolve([]),
    openExternal: () => Promise.resolve(),
    updatesCheck: () => Promise.resolve(null),
    updatesGetState: () => Promise.resolve(null),
    ...overrides,
  };
  window.selfos = bridge;
  return bridge;
}

export function clearMockBridge(): void {
  delete window.selfos;
}

/**
 * Make the active person the Owner (the full-access role) for a test — the replacement for the removed
 * super-admin bypass (roles refactor 2026-06-15). Reuses the existing active person id when set.
 */
export function elevateToOwner(): void {
  const state = useSessionStore.getState();
  const personId = state.activePerson?.id ?? 'owner-1';
  useSessionStore.setState({
    activePerson: state.activePerson ?? {
      id: personId,
      schemaVersion: 1,
      displayName: 'Owner',
      isSubject: true,
      tags: [],
      createdAt: 'now',
      updatedAt: 'now',
    },
    access: {
      roles: DEFAULT_ROLES,
      accounts: [{ personId, roleId: 'owner', hasPin: false }],
    },
  });
}
