import type { TestDefinition } from '../types';
import type { Question } from '../../schemas';

/**
 * Big Five personality — IPIP-120 (50-self-assessments §4.2). Five broad domains, 24 items each (120 total),
 * each domain rendered as one `matrix` Question whose row `key`s are the stable item ids the subscales
 * reference. Items are public-domain-style IPIP originals in the "describes me" register — NOT verbatim
 * copyrighted text. Roughly half of each domain's items are negatively worded and reverse-keyed (`-` prefix
 * in the subscale `items`), the standard IPIP balance the scorer flips on the 1..5 scale.
 */

const POINT_LABELS = [
  'Very inaccurate',
  'Moderately inaccurate',
  'Neither',
  'Moderately accurate',
  'Very accurate',
];

const openness: Question = {
  id: 'bigfive-openness',
  type: 'matrix',
  prompt: 'How well does each statement describe you?',
  help: 'There are no right answers — go with your gut.',
  required: true,
  matrix: {
    rows: [
      { key: 'o1', label: 'Have a vivid imagination' },
      { key: 'o2', label: 'Have difficulty understanding abstract ideas' },
      { key: 'o3', label: 'Am full of ideas' },
      { key: 'o4', label: 'Am not interested in abstract ideas' },
      { key: 'o5', label: 'Enjoy thinking about deep questions' },
      { key: 'o6', label: 'Avoid philosophical discussions' },
      { key: 'o7', label: 'Love to reflect on things' },
      { key: 'o8', label: 'Do not enjoy going to art museums' },
      { key: 'o9', label: 'See beauty in things others might not notice' },
      { key: 'o10', label: 'Rarely look for a deeper meaning in things' },
      { key: 'o11', label: 'Am curious about many different things' },
      { key: 'o12', label: 'Dislike changes to my routine' },
      { key: 'o13', label: 'Enjoy trying new and foreign foods' },
      { key: 'o14', label: 'Prefer the familiar to the unfamiliar' },
      { key: 'o15', label: 'Have a rich vocabulary' },
      { key: 'o16', label: 'Have trouble imagining things' },
      { key: 'o17', label: 'Am drawn to creative pursuits' },
      { key: 'o18', label: 'Seldom get lost in thought' },
      { key: 'o19', label: 'Like to play with ideas' },
      { key: 'o20', label: 'Am not interested in theoretical discussions' },
      { key: 'o21', label: 'Enjoy hearing new perspectives' },
      { key: 'o22', label: 'Tend to vote for conservative, traditional choices' },
      { key: 'o23', label: 'Appreciate unusual and original work' },
      { key: 'o24', label: 'Find abstract concepts hard to follow' },
    ],
    min: 1,
    max: 5,
    pointLabels: POINT_LABELS,
  },
};

const conscientiousness: Question = {
  id: 'bigfive-conscientiousness',
  type: 'matrix',
  prompt: 'How well does each statement describe you?',
  help: 'There are no right answers — go with your gut.',
  required: true,
  matrix: {
    rows: [
      { key: 'c1', label: 'Get chores done right away' },
      { key: 'c2', label: 'Leave my belongings around' },
      { key: 'c3', label: 'Like order and tidiness' },
      { key: 'c4', label: 'Make a mess of things' },
      { key: 'c5', label: 'Follow a schedule' },
      { key: 'c6', label: 'Often forget to put things back in their place' },
      { key: 'c7', label: 'Pay attention to details' },
      { key: 'c8', label: 'Shirk my duties' },
      { key: 'c9', label: 'Get things done on time' },
      { key: 'c10', label: 'Find it hard to get down to work' },
      { key: 'c11', label: 'Carry out my plans' },
      { key: 'c12', label: 'Waste my time' },
      { key: 'c13', label: 'Am always prepared' },
      { key: 'c14', label: 'Leave a task unfinished' },
      { key: 'c15', label: 'Work hard toward my goals' },
      { key: 'c16', label: 'Do just enough work to get by' },
      { key: 'c17', label: 'Keep my promises' },
      { key: 'c18', label: 'Need a push to get started' },
      { key: 'c19', label: 'Stick to my commitments' },
      { key: 'c20', label: 'Act without thinking it through' },
      { key: 'c21', label: 'Set high standards for myself and meet them' },
      { key: 'c22', label: 'Neglect my responsibilities' },
      { key: 'c23', label: 'Double-check my work for mistakes' },
      { key: 'c24', label: 'Have difficulty sticking to a plan' },
    ],
    min: 1,
    max: 5,
    pointLabels: POINT_LABELS,
  },
};

const extraversion: Question = {
  id: 'bigfive-extraversion',
  type: 'matrix',
  prompt: 'How well does each statement describe you?',
  help: 'There are no right answers — go with your gut.',
  required: true,
  matrix: {
    rows: [
      { key: 'e1', label: 'Am the life of the party' },
      { key: 'e2', label: 'Keep in the background' },
      { key: 'e3', label: 'Start conversations easily' },
      { key: 'e4', label: "Don't talk a lot" },
      { key: 'e5', label: 'Feel comfortable around people' },
      { key: 'e6', label: 'Find it hard to approach others' },
      { key: 'e7', label: 'Talk to many different people at parties' },
      { key: 'e8', label: 'Prefer to stay home rather than go out' },
      { key: 'e9', label: 'Make friends easily' },
      { key: 'e10', label: 'Keep my thoughts to myself' },
      { key: 'e11', label: 'Take charge in a group' },
      { key: 'e12', label: 'Wait for others to lead the way' },
      { key: 'e13', label: 'Enjoy being the center of attention' },
      { key: 'e14', label: 'Dislike drawing attention to myself' },
      { key: 'e15', label: 'Radiate energy and enthusiasm' },
      { key: 'e16', label: 'Am quiet around strangers' },
      { key: 'e17', label: 'Light up a room when I enter' },
      { key: 'e18', label: 'Find it draining to be around lots of people' },
      { key: 'e19', label: 'Seek out lively social gatherings' },
      { key: 'e20', label: 'Have little to say' },
      { key: 'e21', label: 'Express myself readily to others' },
      { key: 'e22', label: 'Tend to keep to myself' },
      { key: 'e23', label: 'Feel energized after time with friends' },
      { key: 'e24', label: 'Avoid large crowds when I can' },
    ],
    min: 1,
    max: 5,
    pointLabels: POINT_LABELS,
  },
};

const agreeableness: Question = {
  id: 'bigfive-agreeableness',
  type: 'matrix',
  prompt: 'How well does each statement describe you?',
  help: 'There are no right answers — go with your gut.',
  required: true,
  matrix: {
    rows: [
      { key: 'a1', label: "Sympathize with others' feelings" },
      { key: 'a2', label: "Am not interested in other people's problems" },
      { key: 'a3', label: "Feel others' emotions" },
      { key: 'a4', label: 'Feel little concern for others' },
      { key: 'a5', label: 'Take time out for others' },
      { key: 'a6', label: 'Insult people when I am annoyed' },
      { key: 'a7', label: 'Make people feel at ease' },
      { key: 'a8', label: 'Am hard to get to know' },
      { key: 'a9', label: 'Have a soft heart' },
      { key: 'a10', label: "Am indifferent to others' needs" },
      { key: 'a11', label: 'Treat everyone with kindness' },
      { key: 'a12', label: 'Hold grudges against people' },
      { key: 'a13', label: 'Trust what others say' },
      { key: 'a14', label: 'Suspect hidden motives in others' },
      { key: 'a15', label: 'Go out of my way to help someone' },
      { key: 'a16', label: 'Look down on people I disagree with' },
      { key: 'a17', label: 'Forgive others easily' },
      { key: 'a18', label: 'Can be cold and aloof' },
      { key: 'a19', label: 'Believe people are basically good' },
      { key: 'a20', label: 'Get back at people who wrong me' },
      { key: 'a21', label: 'Am considerate of how others feel' },
      { key: 'a22', label: 'Find it hard to compromise' },
      { key: 'a23', label: 'Put others before myself when needed' },
      { key: 'a24', label: 'Am quick to point out flaws in others' },
    ],
    min: 1,
    max: 5,
    pointLabels: POINT_LABELS,
  },
};

const neuroticism: Question = {
  id: 'bigfive-neuroticism',
  type: 'matrix',
  prompt: 'How well does each statement describe you?',
  help: 'There are no right answers — go with your gut.',
  required: true,
  matrix: {
    rows: [
      { key: 'n1', label: 'Get stressed out easily' },
      { key: 'n2', label: 'Am relaxed most of the time' },
      { key: 'n3', label: 'Worry about things' },
      { key: 'n4', label: 'Seldom feel anxious' },
      { key: 'n5', label: 'Get upset easily' },
      { key: 'n6', label: 'Stay calm under pressure' },
      { key: 'n7', label: 'Have frequent mood swings' },
      { key: 'n8', label: 'Rarely feel blue' },
      { key: 'n9', label: 'Am easily disturbed' },
      { key: 'n10', label: 'Keep my emotions even' },
      { key: 'n11', label: 'Get irritated easily' },
      { key: 'n12', label: 'Rarely lose my temper' },
      { key: 'n13', label: 'Often feel sad' },
      { key: 'n14', label: 'Feel comfortable with myself' },
      { key: 'n15', label: 'Panic easily when things go wrong' },
      { key: 'n16', label: 'Am not easily bothered by things' },
      { key: 'n17', label: 'Dwell on my mistakes' },
      { key: 'n18', label: 'Recover quickly from setbacks' },
      { key: 'n19', label: 'Feel overwhelmed by my feelings' },
      { key: 'n20', label: 'Handle difficult situations well' },
      { key: 'n21', label: 'Often worry about what could go wrong' },
      { key: 'n22', label: 'Rarely feel tense or on edge' },
      { key: 'n23', label: 'Take offense easily' },
      { key: 'n24', label: 'Am content with how things are' },
    ],
    min: 1,
    max: 5,
    pointLabels: POINT_LABELS,
  },
};

const BANDS = [
  { upTo: 0.33, label: 'leans lower' },
  { upTo: 0.66, label: 'balanced' },
  { upTo: 1, label: 'leans higher' },
];

export const BIG_FIVE: TestDefinition = {
  id: 'bigfive-ipip-120',
  group: 'personality',
  title: 'Big Five personality',
  instrument: 'IPIP',
  blurb:
    'Five broad dimensions of personality — openness, conscientiousness, extraversion, agreeableness, and emotional sensitivity.',
  framing: 'A reflection of how you answered today, not a verdict or a diagnosis.',
  estimatedMinutes: 20,
  version: 1,
  items: [openness, conscientiousness, extraversion, agreeableness, neuroticism],
  scoring: {
    method: 'subscales',
    scale: { min: 1, max: 5 },
    subscales: [
      {
        key: 'bigfive.openness',
        label: 'Openness',
        aggregate: 'sum',
        items: [
          'o1',
          '-o2',
          'o3',
          '-o4',
          'o5',
          '-o6',
          'o7',
          '-o8',
          'o9',
          '-o10',
          'o11',
          '-o12',
          'o13',
          '-o14',
          'o15',
          '-o16',
          'o17',
          '-o18',
          'o19',
          '-o20',
          'o21',
          '-o22',
          'o23',
          '-o24',
        ],
        normalize: { min: 24, max: 120, out: 'unit' },
        bands: BANDS,
      },
      {
        key: 'bigfive.conscientiousness',
        label: 'Conscientiousness',
        aggregate: 'sum',
        items: [
          'c1',
          '-c2',
          'c3',
          '-c4',
          'c5',
          '-c6',
          'c7',
          '-c8',
          'c9',
          '-c10',
          'c11',
          '-c12',
          'c13',
          '-c14',
          'c15',
          '-c16',
          'c17',
          '-c18',
          'c19',
          '-c20',
          'c21',
          '-c22',
          'c23',
          '-c24',
        ],
        normalize: { min: 24, max: 120, out: 'unit' },
        bands: BANDS,
      },
      {
        key: 'bigfive.extraversion',
        label: 'Extraversion',
        aggregate: 'sum',
        items: [
          'e1',
          '-e2',
          'e3',
          '-e4',
          'e5',
          '-e6',
          'e7',
          '-e8',
          'e9',
          '-e10',
          'e11',
          '-e12',
          'e13',
          '-e14',
          'e15',
          '-e16',
          'e17',
          '-e18',
          'e19',
          '-e20',
          'e21',
          '-e22',
          'e23',
          '-e24',
        ],
        normalize: { min: 24, max: 120, out: 'unit' },
        bands: BANDS,
      },
      {
        key: 'bigfive.agreeableness',
        label: 'Agreeableness',
        aggregate: 'sum',
        items: [
          'a1',
          '-a2',
          'a3',
          '-a4',
          'a5',
          '-a6',
          'a7',
          '-a8',
          'a9',
          '-a10',
          'a11',
          '-a12',
          'a13',
          '-a14',
          'a15',
          '-a16',
          'a17',
          '-a18',
          'a19',
          '-a20',
          'a21',
          '-a22',
          'a23',
          '-a24',
        ],
        normalize: { min: 24, max: 120, out: 'unit' },
        bands: BANDS,
      },
      {
        key: 'bigfive.neuroticism',
        label: 'Neuroticism',
        aggregate: 'sum',
        items: [
          'n1',
          '-n2',
          'n3',
          '-n4',
          'n5',
          '-n6',
          'n7',
          '-n8',
          'n9',
          '-n10',
          'n11',
          '-n12',
          'n13',
          '-n14',
          'n15',
          '-n16',
          'n17',
          '-n18',
          'n19',
          '-n20',
          'n21',
          '-n22',
          'n23',
          '-n24',
        ],
        normalize: { min: 24, max: 120, out: 'unit' },
        bands: BANDS,
      },
    ],
  },
};
